force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_State_Code__c</fullName>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GST#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7) OR (3 AND 8 AND 2) OR (3 AND 9 AND 7) OR (10 AND 7)</booleanFilter>
        <errorMessage>Invalid Mapping of Standard Reason and GST Type</errorMessage>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_GST_Applicable__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ with taxes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Zero Rated Supply- FTWZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non Taxable as transactions within same Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GST__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/ARTL_GST_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GST State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__Premises__c/fields/ARTL_Pincode__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>ARTL_Pincode__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactPremiseRelationTriggerHandler.cls
/**
* Class to implement the trigger handler for ContactPremiseRelation Object
*
* @Author  Salesforce
*
*/

public class ContactPremiseRelationTriggerHandler extends TriggerHandler{
    List<ContactPremiseRelation__c> newContactPremiseRelationMap = (List<ContactPremiseRelation__c>) Trigger.New;
    Map<Id, ContactPremiseRelation__c> oldContactPremiseRelationMap = (Map<Id, ContactPremiseRelation__c>) Trigger.oldMap;
    
    public ContactPremiseRelationTriggerHandler() {
        this.newContactPremiseRelationMap = (List<ContactPremiseRelation__c>) Trigger.New;
        this.oldContactPremiseRelationMap = (Map<Id, ContactPremiseRelation__c>) Trigger.oldMap;
    }
    Map<Id,String> IPMap = new Map<Id,String>();
    
    public override void beforeInsert(){
        
        if (Trigger.isInsert && Trigger.isBefore) {
            
            Map<Id,vlocity_cmt__Premises__c > conPremise;
            Map<Id,GST__c> conGST;
            
            if(newContactPremiseRelationMap.size()>0){
                
                Set<Id> premiseState = new Set<Id>();
                for(ContactPremiseRelation__c con: newContactPremiseRelationMap){
                    premiseState.add(con.Premises__c);
                }
                Set<Id> GSTState = new Set<Id>();
                for(ContactPremiseRelation__c con2: newContactPremiseRelationMap){
                    GSTState.add(con2.GST__c);
                }
                if(premiseState.size()>0)
                    conPremise = new Map<Id,vlocity_cmt__Premises__c >([SELECT id,vlocity_cmt__State__c,ARTL_Pincode__r.ARTL_State_Code__c FROM vlocity_cmt__Premises__c where Id IN :premiseState]);
                if(GSTState.size()>0)
                    conGST = new Map<id,GST__c>([SELECT id,ARTL_Address__StateCode__s, ARTL_GST_State_Code__c FROM GST__c where Id In :GSTState ]);
                
                for(ContactPremiseRelation__c Relation: newContactPremiseRelationMap){
                    if(conPremise.size()>0 && conGST.size()>0 && Relation.Premises__c!= NULL && Relation.GST__c!=NULL){
                        if(Integer.valueOf(conPremise.get(Relation.Premises__c).ARTL_Pincode__r.ARTL_State_Code__c) != Integer.valueOf(conGST.get(Relation.GST__c).ARTL_GST_State_Code__c)) {
                            Relation.addError('State Code of the GST does not match with the State Code of the related Contact');
                        }                        
                    }
                }
            }
        }
    }
    
}