force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Term__c.field-meta.xml
<CustomField>
    <fullName>PO_Term__c</fullName>
    <label>PO Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Value__c.field-meta.xml
<CustomField>
    <fullName>PO_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PO Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AssetId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AssetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For quotes of changes to existing Assets, this identifies the Asset that is being changed by this line item.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quoted Changes</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_MACD_CreateBillingStagingTest.cls
@isTest
private class ARTL_MACD_CreateBillingStagingTest {
    
    @isTest
    static void testGetOrderRelDetails2() {
          Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User user = new User(LastName = 'Jackson',FirstName='Michael', Alias = 'jl', Email = 'Michael.Jackson@testorg.com',
                             Username = 'Michael.Jackson@testorg.com', ProfileId = profileId.id,TimeZoneSidKey = 'GMT', 
                             LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US');
        // string userId = UserInfo.getUserId();
        insert user;
        System.runAs(user){
            
            // create test data for order, Account, Quote, Opportunity
            Account acc = new Account();
            acc.name='Parent Test';
            acc.BillingStreet = '3022  Strother Street';
            acc.BillingCity = 'Into';
            acc.BillingState = 'Alabama';
            acc.BillingPostalCode = '35222';
            acc.BillingCountry = 'US';
            
            insert acc ;
            
            Product2[] products = new Product2[2];
            
            products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
            products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
            
            insert products;
            
            PricebookEntry[] pbes = new PricebookEntry[products.size()];
            Id pbId = Test.getStandardPricebookId();
            
            for (Integer i=0; i<products.size(); i++)
            {
                pbes[i] = new PricebookEntry(product2Id = products[i].id, IsActive = true, unitPrice = 10, pricebook2id = pbId, useStandardPrice = false);
            }
            
            insert pbes;
            
            
            vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, vlocity_cmt__IsActive__c = true, vlocity_cmt__Code__c = 'TestPricebook5');
            insert pl1;
            
            Opportunity  opp = new Opportunity ();
            opp.name= 'EPC Deal AA';
            opp.accountId = acc.id;
            opp.vlocity_cmt__PriceListId__c = pl1.Id;
            opp.CloseDate = System.today();
            opp.StageName = 'Initial';
            opp.Pricebook2Id = pbId;
            insert opp;
            
            
            
            Quote qtest = new Quote();
            qtest.name = 'Quote - EPC Deal AA';
            qtest.Status = 'Draft';
            qtest.OpportunityId = opp.Id;
            qtest.Pricebook2Id = pbId;
            qtest.vlocity_cmt__PriceListId__c = pl1.Id;
            qtest.vlocity_cmt__PoDate__c = Date.today();
            qtest.vlocity_cmt__PoNumber__c = '12345';
            qtest.PO_Term__c = '12';
            qtest.PO_Value__c = 1222;
            qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
            insert qtest;
            
            
            
            QuoteLineItem  qouteLine = new QuoteLineItem ();
            qouteLine.UnitPrice = 1;
            qouteLine.Quantity = 1;
            qouteLine.Product2Id = products[0].Id;
            qouteLine.vlocity_cmt__Product2Id__c = products[0].Id;
            qouteLine.QuoteId =qtest.Id;
            qouteLine.PricebookEntryId=pbes[0].Id;
            qouteLine.vlocity_cmt__ServiceAccountId__c =acc.id;
            insert qouteLine;
            
            ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
            PurchaseOrder.ARTL_PO_Number__c = '111111';
            PurchaseOrder.Quote_Line_Item__c = qouteLine.id;
            insert PurchaseOrder;
            
            Asset ast = new Asset();
            ast.Name = 'MyNewAssetforTestClass';
            ast.AccountId = acc.Id;
            ast.vlocity_cmt__AssetReferenceId__c = '123';
            ast.vlocity_cmt__BillingAccountId__c  = acc.Id;
            ast.vlocity_cmt__ServiceAccountId__c   = acc.Id;
            ast.ARTL_Purchase_Order__c = PurchaseOrder.id;
            insert ast;  
            QuoteLineItem  qouteLine2 = new QuoteLineItem ();
            qouteLine2.UnitPrice = 1;
            qouteLine2.Quantity = 1;
            qouteLine2.vlocity_cmt__AssetId__c = ast.id;
            qouteLine2.Product2Id = products[1].Id;
            qouteLine2.vlocity_cmt__Product2Id__c = products[1].Id;
            qouteLine2.QuoteId =qtest.Id;
            qouteLine2.PricebookEntryId=pbes[0].Id;
            insert qouteLine2;
            
            
            
            List<Order> orderList = new List<Order>();
            Order ord = new Order(AccountId = acc.id,vlocity_cmt__QuoteId__c = qtest.Id ,
                                  effectiveDate = Date.today(), pricebook2id = pbId, status = 'Draft',
                                  vlocity_cmt__PriceListId__c = pl1.Id);
            orderList.add(ord);
            insert orderList;
            Test.startTest();
            
            List<String> assetIdList = new List<String>{ast.vlocity_cmt__AssetReferenceId__c};
                List<QuoteLineItem> qLIList = new List<QuoteLineItem>{qouteLine2};
                    Map<String, Object> input = new Map<String, Object>();
            Map<String, Object> option = new Map<String, Object>();
            Map<String, Object> output = new Map<String, Object>();
            input.put('quoteId',qtest.id);
            
            
            // Call the method to be tested
            ARTL_MACD_CreateBillingStaging.createBillingStaging(assetIdList, qLIList);
            /*ARTL_MACD_CreateBillingStagingIP callableInstance = new ARTL_MACD_CreateBillingStagingIP();
            callableInstance.call('CreateBS', new Map<String, Object>{
                'input' => input,
                    'output' => output,
                    'options' => option
                    });*/
            
            Test.stopTest();
            
        }
    }
}