force-app/main/default/objects/Order/fields/ARTL_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Shifting</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>L1-L3 Construct Change</fullName>
            </value>
            <value>
                <fullName>Rate Revision</fullName>
            </value>
            <value>
                <fullName>Rebilling</fullName>
            </value>
            <value>
                <fullName>LSI Transfer</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Network Change</fullName>
            </value>
            <value>
                <fullName>Hardware Replacement</fullName>
            </value>
            <value>
                <fullName>Suspend</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
            <value>
                <fullName>PO Renewal</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__SupersededOrderItemId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__SupersededOrderItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Order Item on Superseded Order that this Order Item record overrides.</description>
    <label>Superseded Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Superseding Order Products</relationshipLabel>
    <relationshipName>SupersedingOrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__SupplementalAction__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__SupplementalAction__c</fullName>
    <description>The action that is requested with respect to the action requested in superseded order item.</description>
    <label>Supplemental Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Change</fullName>
            </value>
            <value>
                <fullName>Amend</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/XLI_Technical_Attribute__c.object-meta.xml
<CustomObject>
    <label>XLI Technical Attribute</label>
    <nameField>
        <displayFormat>XLI-{000000}</displayFormat>
        <label>XLI Technical Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>XLI Technical Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/ARTL_Status__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/AttributeMetadataChanges__c.field-meta.xml
<CustomField>
    <fullName>AttributeMetadataChanges__c</fullName>
    <label>AttributeMetadataChanges</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>XLI Technical Attributes</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>XLI Technical Attributes</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Root_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Root_Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>XLI Technical Attributes (Root Quote Line Item)</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Technical_Attribute__c</fullName>
    <description>Same as vlocity_cmt__AttributeSelectedValues__c</description>
    <label>Technical Attribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Attribute_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Technical_Attribute_Metadata__c</fullName>
    <label>Technical Attribute Metadata</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Product__c.field-meta.xml
<CustomField>
    <fullName>Technical_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>XLI Technical Attributes</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderItemTriggerHandlerHelper.cls
public class OrderItemTriggerHandlerHelper {
    
    /*public static void createPMApprovalTask(map<Id,OrderItem> newmap){
     	List<Task> lsttobeInsert = new List<Task>();
        for(OrderItem oli : [Select Id,QuoteLineItemId,Order.Record_Type_Name__c,Order.vlocity_cmt__QuoteId__r.PM__c,
                             vlocity_cmt__ParentItemId__c
                            FROM OrderItem WHERE Id IN: newmap.keyset() AND vlocity_cmt__ParentItemId__c = null]){
            if(oli.vlocity_cmt__ParentItemId__c == null){
                lsttobeInsert.add(new Task(
                Subject ='PM Approval',
                WhatId = oli.OrderId,
                Type = 'PM Approval',
                ARTL_TaskType__c ='PM Approval',    
                Quote_Line_Item__c = oli.QuoteLineItemId,
                ARTL_Order_Type__c = oli.Order.Record_Type_Name__c,  
                OwnerId = oli.Order.vlocity_cmt__QuoteId__r.PM__c != null ? oli.Order.vlocity_cmt__QuoteId__r.PM__c : UserInfo.getUserId()
                ));
            }
        }
        if(!lsttobeInsert.isEmpty()){
            insert lsttobeInsert;
        }
    }*/
    /*public static void updateTechnicalAttribute(List<OrderItem> lstOrderItems){
        Map<String,OrderItem> mapOfQuoteLineWithOLI = new Map<String,OrderItem>();
        for(OrderItem oli : lstOrderItems){
            if(oli.QuoteLineItemId != null)
            	mapOfQuoteLineWithOLI.put(oli.QuoteLineItemId, oli);
        }
        List<XLI_Technical_Attribute__c> lstExistingXLI = [Select Id, Order_Line_Item__c,Quote_Line_Item__c
                                                          FROM XLI_Technical_Attribute__c
                                                          WHERE Quote_Line_Item__c IN:mapOfQuoteLineWithOLI.keySet()];
        if(!lstExistingXLI.IsEmpty()){
            for(XLI_Technical_Attribute__c xli: lstExistingXLI){
                if(xli.Quote_Line_Item__c != null && mapOfQuoteLineWithOLI.containsKey(xli.Quote_Line_Item__c)){
                    OrderItem objoli = new OrderItem();
                    xli.Order_Line_Item__c = mapOfQuoteLineWithOLI.get(xli.Quote_Line_Item__c).Id;
                }
            }
            update lstExistingXLI;
        }
    }*/
    //SFDC-1933
    /*public static void createandUpdateXLI(List<OrderItem> lstOrderItems){
        Set<Id> setOfrootItemIds = new Set<Id>();
        Map<String, OrderItem> mapOfwithOrder = new Map<String, OrderItem>();
        for(OrderItem oli: lstOrderItems){
            if(oli.vlocity_cmt__ParentItemId__c  == null && oli.vlocity_cmt__SupersededOrderItemId__c != null){
                mapOfwithOrder.put(oli.vlocity_cmt__SupersededOrderItemId__c, oli);
            }
        }
        List<XLI_Technical_Attribute__c> lstOfxlitobeUpsert = new List<XLI_Technical_Attribute__c>();
        for(XLI_Technical_Attribute__c xli : [Select Id,AttributeMetadataChanges__c,Order_Line_Item__c,Quote_Line_Item__c,
                                              Root_Quote_Line_Item__c,ARTL_Status__c,Technical_Attribute__c,
                                              Technical_Attribute_Metadata__c,
                                              Technical_Product__c FROM XLI_Technical_Attribute__c 
                                              WHERE Order_Line_Item__c IN:mapOfwithOrder.keySet() 
                                              AND Order_Line_Item__r.Order.vlocity_cmt__SupplementalAction__c = 'Amend'
                                              AND ARTL_Status__c = 'Active']){
                XLI_Technical_Attribute__c cloneObj = xli.clone();
                cloneObj.Id = null;
				if(mapOfwithOrder.containsKey(xli.Order_Line_Item__c)){
                      cloneObj.Order_Line_Item__c = mapOfwithOrder.get(xli.Order_Line_Item__c).Id;
                      xli.ARTL_Status__c = 'InActive';
                    lstOfxlitobeUpsert.add(cloneObj);
                    lstOfxlitobeUpsert.add(xli);
				}                                     
            	                                      
        }
        if(!lstOfxlitobeUpsert.isEmpty()){
            upsert lstOfxlitobeUpsert;
        }
    }*/
}