force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/ARTL_Bulk_Upload_Staging__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_Bulk_Upload_Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/ARTL_Bulk_Upload_Iteration__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bulk_Upload_Iteration__c</fullName>
    <label>ARTL Bulk Upload Iteration</label>
    <referenceTo>ARTL_Bulk_Upload_Iteration__c</referenceTo>
    <relationshipLabel>ARTL Bulk Upload Stagings</relationshipLabel>
    <relationshipName>ARTL_Bulk_Upload_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BUC</fullName>
            </value>
            <value>
                <fullName>Quota</fullName>
            </value>
            <value>
                <fullName>Asset_to_Quote</fullName>
                <label>Asset to Quote</label>
            </value>
            <value>
                <fullName>BCPDCP_Contact</fullName>
            </value>
            <value>
                <fullName>Party_Contact</fullName>
            </value>
            <value>
                <fullName>BCPDCP_Contact_Update</fullName>
            </value>
            <value>
                <fullName>Party_Contact_Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_AssetBulkUploadCtrl.cls
public without sharing class ARTL_AssetBulkUploadCtrl {
    
    private static String STAGING_TYPE = 'Asset_to_Quote';

    @AuraEnabled
    public static List<Decimal> checkLsi(List<Decimal> lsiList , String iterationId){
        System.debug('lsiList=' + lsiList + '=');
        System.debug('iterationId=' + iterationId + '=');
        try {
            List<Decimal> invalidLsiList = new List<Decimal>();
            Set<Decimal> existingLsiSet = new Set<Decimal>();

            List<Asset> assetList = [Select ARTL_LSI__c From Asset Where ARTL_LSI__c IN : lsiList];
            for(Asset lsi : assetList){
                existingLsiSet.add(lsi.ARTL_LSI__c);
            }

            if(!existingLsiSet.isEmpty()){
                for(Decimal lsi : lsiList){
                    if(!existingLsiSet.contains(lsi)){
                        invalidLsiList.add(lsi);
                    }
                }
            }

            if(invalidLsiList.isEmpty()){
                createStagingRecords(lsiList, iterationId);
            }
            
            return invalidLsiList;
        } catch (Exception e) {
            System.debug('e.getMessage()=' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @TestVisible
    private static void createStagingRecords(List<Decimal> lsiList , String iterationId){
        List<sObject> lstStageToInsert = new List<sObject>();
        ARTL_Bulk_Upload_Staging__c stagingRecord = new ARTL_Bulk_Upload_Staging__c();
        if(iterationId.contains('"')) iterationId = iterationId.remove('"');

        for(Decimal lsi : lsiList) {
            stagingRecord = new ARTL_Bulk_Upload_Staging__c();
            
            stagingRecord.Record_Id__c = String.valueOf(lsi);
            stagingRecord.Type__c = STAGING_TYPE;
            stagingRecord.ARTL_Bulk_Upload_Iteration__c = iterationId;

            lstStageToInsert.add(stagingRecord);
        }
        System.debug('lstStageToInsert=' + lstStageToInsert.size() + '=');
        insert lstStageToInsert;
    }
}