force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/ARTL_Bulk_Upload_Staging__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_Bulk_Upload_Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/ARTL_Bulk_Upload_Iteration__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bulk_Upload_Iteration__c</fullName>
    <label>ARTL Bulk Upload Iteration</label>
    <referenceTo>ARTL_Bulk_Upload_Iteration__c</referenceTo>
    <relationshipLabel>ARTL Bulk Upload Stagings</relationshipLabel>
    <relationshipName>ARTL_Bulk_Upload_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>GST_Applicable__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GST Applicable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Standard_Reason__c</fullName>
    <label>Standard Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_GST_Applicable__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>UIN</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Non-SEZ</fullName>
            </value>
            <value>
                <fullName>Applied For</fullName>
            </value>
            <value>
                <fullName>SEZ with taxes</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- FTWZ</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- Export</fullName>
            </value>
            <value>
                <fullName>Non Taxable as transactions within same Company</fullName>
            </value>
            <value>
                <fullName>Airtel- Foreign Legal Entity</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Exempt-Trust/Entities 12AA</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- SEZ</fullName>
            </value>
            <value>
                <fullName>J&amp;K delivery - Out of GST Preview</fullName>
            </value>
            <value>
                <fullName>Exempt Supply - Trust/Entities 12AA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GST#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7) OR (3 AND 8 AND 2) OR (3 AND 9 AND 7) OR (10 AND 7)</booleanFilter>
        <errorMessage>Invalid Mapping of Standard Reason and GST Type</errorMessage>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_GST_Applicable__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ with taxes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Zero Rated Supply- FTWZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non Taxable as transactions within same Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GST__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>Standard_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Standard Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_BCPDCPBulkUpdateBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-09-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class ARTL_BCPDCPBulkUpdateBatch implements Database.Batchable<sObject>, Database.Stateful{
    String iterationid;
    public ARTL_BCPDCPBulkUpdateBatch(String iterationid) {
        this.iterationid = iterationid;
    }

    /* Id batchJobId = Database.executeBatch(new ARTL_BCPDCPBulkUpdateBatch('a7i720000002i8DAAQ'), 200); 
        System.debug('batchJobId = ' + batchJobId);
    */
    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('this.iterationid-->'+this.iterationid);
        String query = 'SELECT Record_Id__c, First_Name__c, Last_Name__c, Email_Address__c, Phone__c, Role__c, Designation__c, Street__c, City__c, State__c, Country__c, Pincode__c, Status__c, GST__c, GST_Applicable__c, Standard_Reason__c, ARTL_Bulk_Upload_Iteration__c FROM ARTL_Bulk_Upload_Staging__c WHERE ARTL_Bulk_Upload_Iteration__c = \''+this.iterationid+'\'';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<ARTL_Bulk_Upload_Staging__c> stagingRecordList){
        ARTL_UpdateBcpDcpLwcController.isUpdateBcpDcp = true;
        Set<String> cprIdSet = new Set<String>();
        Set<Id> contactIdSet = new Set<Id>();
        Set<Id> premiseIdSet = new Set<Id>();
        Set<Id> gstIdSet = new Set<Id>();
        List<sObject> recordsToUpdate = new List<sObject>();
        Set<String> gstNameSet = new Set<String>();
        Map<String,GST__c> gstNameMap = new Map<String,GST__c>();

        Map<Id,Id> cprIdWithStagingIdMap = new Map<Id,Id>();
        Map<Id,Id> cprRelatedIdWithcptIdMap = new Map<Id,Id>();
        Map<Id, ARTL_Bulk_Upload_Staging__c> stagingIdWithStagingRecordMap = new Map<Id, ARTL_Bulk_Upload_Staging__c>();

        for(ARTL_Bulk_Upload_Staging__c stagingrec : stagingRecordList) {
            cprIdSet.add(stagingrec.Record_Id__c);
            gstNameSet.add(stagingrec.GST__c);

            cprIdWithStagingIdMap.put(stagingrec.Record_Id__c, stagingrec.Id);
        }

        List<GST__c> gstList = [SELECT Id, Name FROM GST__c WHERE Name in: gstNameSet];

        for(GST__c gst : gstList) {
            gstNameMap.put(gst.Name, gst);
        }

        Map<Id,ContactPremiseRelation__c> cprMap = new Map<Id,ContactPremiseRelation__c>([SELECT Id, Contact__c, Premises__c, GST__c, ARTL_Standard_Reason__c FROM ContactPremiseRelation__c WHERE Id in: cprIdSet]);
        
        for(ContactPremiseRelation__c cpr : cprMap.values()) {
            contactIdSet.add(cpr.Contact__c);
            premiseIdSet.add(cpr.Premises__c);
            gstIdSet.add(cpr.GST__c);

            cprRelatedIdWithcptIdMap.put(cpr.Contact__c, cpr.Id);
            cprRelatedIdWithcptIdMap.put(cpr.Premises__c, cpr.Id);
            cprRelatedIdWithcptIdMap.put(cpr.Id, cpr.Id);
        }

        Map<Id,Contact> contactMap = new Map<Id,Contact>([SELECT Id, FirstName, LastName, Email, MobilePhone, ARTL_Designation__c, ARTL_Contact_Role__c FROM Contact WHERE Id in: contactIdSet]);
        Map<Id,vlocity_cmt__Premises__c> premiseMap = new Map<Id,vlocity_cmt__Premises__c>([SELECT Id, vlocity_cmt__StreetAddress__c, vlocity_cmt__City__c, vlocity_cmt__State__c, vlocity_cmt__Country__c, vlocity_cmt__PostalCode__c FROM vlocity_cmt__Premises__c WHERE Id in: premiseIdSet]);
        Map<Id,GST__c> gstMap = new Map<Id,GST__c>([SELECT Id, Name FROM GST__c WHERE Id in: gstIdSet]);

        for(ARTL_Bulk_Upload_Staging__c stagingRec: stagingRecordList) {
            ContactPremiseRelation__c cpr = cprMap.get((Id)stagingRec.Record_Id__c);
            Contact con = contactMap.get(cprMap.get((Id)stagingRec.Record_Id__c).Contact__c);
            vlocity_cmt__Premises__c prem = premiseMap.get(cprMap.get((Id)stagingRec.Record_Id__c).Premises__c);
            GST__c gst = gstMap.get(cprMap.get((Id)stagingRec.Record_Id__c).GST__c);
            
            if(String.isNotBlank(stagingRec.First_Name__c)) {
                con.FirstName = stagingRec.First_Name__c;
            }
            if(String.isNotBlank(stagingRec.Last_Name__c)) {
                con.LastName = stagingRec.Last_Name__c;
            }
            if(String.isNotBlank(stagingRec.Email_Address__c)) {
                con.Email = stagingRec.Email_Address__c;
            }
            if(String.isNotBlank(stagingRec.Phone__c)) {
                con.MobilePhone = stagingRec.Phone__c;
            }
            if(String.isNotBlank(stagingRec.Designation__c)) {
                con.ARTL_Designation__c = stagingRec.Designation__c;
            }
            if(String.isNotBlank(stagingRec.Role__c)) {
                con.ARTL_Contact_Role__c = stagingRec.Role__c;
            }

            if(String.isNotBlank(stagingRec.Standard_Reason__c)) {
                cpr.ARTL_Standard_Reason__c = stagingRec.Standard_Reason__c;
            }

            if(String.isNotBlank(stagingRec.Street__c)) {
                prem.vlocity_cmt__StreetAddress__c = stagingRec.Street__c;
            }
            if(String.isNotBlank(stagingRec.City__c)) {
                prem.vlocity_cmt__City__c = stagingRec.City__c;
            }
            if(String.isNotBlank(stagingRec.State__c)) {
                prem.vlocity_cmt__State__c = stagingRec.State__c;
            }
            if(String.isNotBlank(stagingRec.Country__c)) {
                prem.vlocity_cmt__Country__c = stagingRec.Country__c;
            }
            if(String.isNotBlank(stagingRec.Pincode__c)) {
                prem.vlocity_cmt__PostalCode__c = stagingRec.Pincode__c;
            }
            if(gstNameMap.containsKey(stagingRec.GST__c) && String.isNotBlank(stagingRec.GST__c)) {
                System.debug('stagingRec.GST__c--->'+gstNameMap.get(stagingRec.GST__c).Id);
                cpr.GST__c = gstNameMap.get(stagingRec.GST__c).Id;
            }

            recordsToUpdate.add(prem);
            recordsToUpdate.add(cpr);
            recordsToUpdate.add(con);
        }

        if(!recordsToUpdate.isEmpty()) {
            List<Database.SaveResult> srList = new List<Database.SaveResult>();
            try {
                System.debug('sat recordsToUpdate=' + recordsToUpdate.size());
                
                srList = Database.update(recordsToUpdate, false);
                System.debug('sat srList=' + srList.size());
            } catch (Exception e) {
                System.debug('sat error=' + e.getMessage());
            }
            

            //stagingIdWithStagingRecordMap
            //cprIdWithStagingIdMap
            //cprRelatedIdWithcptIdMap
            
            System.debug('sat srList=' + srList.size());
            for (Database.SaveResult sr : srList) {
                ARTL_Bulk_Upload_Staging__c stagingRecord = new ARTL_Bulk_Upload_Staging__c();
                stagingRecord.Id = cprIdWithStagingIdMap.get(cprRelatedIdWithcptIdMap.get(sr.getId()));

                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                    stagingRecord.Status__c = 'Success';
                }
                else {
                    stagingRecord.Status__c = 'Failed';
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Account fields that affected this error: ' + err.getFields());
                        stagingRecord.Errors__c = err.getMessage();
                    }
                }

                stagingIdWithStagingRecordMap.put(stagingRecord.Id, stagingRecord);
            }

            update stagingIdWithStagingRecordMap.values();
        }
    }

    public void finish(Database.BatchableContext bc){
        //System.debug('sat this.iterationid=' + this.iterationid + '=');
        Artl_BcpDcpCtrl.handleNotification(this.iterationid);
    }
}