force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/ARTL_Bulk_Upload_Staging__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_Bulk_Upload_Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/ARTL_Bulk_Upload_Iteration__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bulk_Upload_Iteration__c</fullName>
    <label>ARTL Bulk Upload Iteration</label>
    <referenceTo>ARTL_Bulk_Upload_Iteration__c</referenceTo>
    <relationshipLabel>ARTL Bulk Upload Stagings</relationshipLabel>
    <relationshipName>ARTL_Bulk_Upload_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>Standard_Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Standard Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_BCPDCPBulkDataUpdateController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-12-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ARTL_BCPDCPBulkDataUpdateController {
	@AuraEnabled
    public static Integer saveStageRecs(List<Object> objList){
        List<ARTL_Bulk_Upload_Staging__c> stageList = new List<ARTL_Bulk_Upload_Staging__c>();
        if(!(objList.isEmpty())){   
            ARTL_Bulk_Upload_Iteration__c itr = new ARTL_Bulk_Upload_Iteration__c();
            itr.Name = 'BCPDCPBulkDataUpdate';
            insert itr;
            for(Object obj : objList){
                Map<String, Object> objRow = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(obj));
                ARTL_Bulk_Upload_Staging__c bus = new ARTL_Bulk_Upload_Staging__c();
                bus.Record_Id__c = (String)objRow.get('ID');
                bus.First_Name__c = (String)objRow.get('NewFirstName');
                bus.Last_Name__c = (String)objRow.get('NewLastName');
                bus.Email_Address__c = (String)objRow.get('NewEmail');
                bus.Phone__c = (String)objRow.get('NewMobilePhone');
                bus.Role__c = (String)objRow.get('NewRole');
                bus.Designation__c = (String)objRow.get('NewDesignation');
                bus.Street__c = (String)objRow.get('NewStreet');
                bus.City__c = (String)objRow.get('NewCity');
                bus.State__c = (String)objRow.get('NewState');
                bus.Country__c = (String)objRow.get('NewCountry');
                bus.Pincode__c = (String)objRow.get('NewPostalCode');
                bus.Standard_Reason__c = (String)objRow.get('NewStandardReason');
                bus.GST__c = (String)objRow.get('NewGST');
                bus.Status__c = 'Pending';
                bus.ARTL_Bulk_Upload_Iteration__c = itr.Id;
                stageList.add(bus);
            }
            insert stageList;
            if(!Test.isRunningTest()) {
                Id batchJobId = Database.executeBatch(new ARTL_BCPDCPBulkUpdateBatch(itr.Id), 200);
                System.debug('batchJobId-->'+batchJobId);      
            }
        }
        return stageList.size();
    }
}