force-app/main/default/objects/ARTL_Document__c/ARTL_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Document__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>organizationDocument</fullName>
                <label>ORGANIZATION_DOCUMENT</label>
            </value>
            <value>
                <fullName>authorizedSignatory</fullName>
                <label>AUTHORIZED_SIGNATORY</label>
            </value>
            <value>
                <fullName>order</fullName>
                <label>ORDER</label>
            </value>
            <value>
                <fullName>email</fullName>
                <label>EMAIL</label>
            </value>
            <value>
                <fullName>serviceHandover</fullName>
                <label>SERVICE_HANDOVER</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store documents of contact authorized signatory</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST certificate</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>TnC</fullName>
            </value>
            <value>
                <fullName>AutSigDoc</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>Caf</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>OrderTemplate</fullName>
            </value>
            <value>
                <fullName>KDM</fullName>
            </value>
            <value>
                <fullName>DOA</fullName>
            </value>
            <value>
                <fullName>Welcome_Email</fullName>
            </value>
            <value>
                <fullName>LOC_Email</fullName>
            </value>
            <value>
                <fullName>Project_Status</fullName>
            </value>
            <value>
                <fullName>ServiceDocuments</fullName>
            </value>
            <value>
                <fullName>Site_Activation</fullName>
            </value>
            <value>
                <fullName>PM_Approval</fullName>
            </value>
            <value>
                <fullName>CPE_Recovery</fullName>
            </value>
            <value>
                <fullName>POI</fullName>
            </value>
            <value>
                <fullName>LOA</fullName>
            </value>
            <value>
                <fullName>LOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/s3_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>s3_Document_URL__c</fullName>
    <description>Used to store s3 URL received from Document Upload Callout Response</description>
    <encryptionScheme>None</encryptionScheme>
    <label>s3 Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>poe</fullName>
                <label>POE</label>
            </value>
            <value>
                <fullName>live_photo</fullName>
                <label>LIVE_PHOTO</label>
            </value>
            <value>
                <fullName>order</fullName>
                <label>ORDER</label>
            </value>
            <value>
                <fullName>cust</fullName>
                <label>CUST</label>
            </value>
            <value>
                <fullName>misc</fullName>
                <label>MISC</label>
            </value>
            <value>
                <fullName>template</fullName>
                <label>TEMPLATE</label>
            </value>
            <value>
                <fullName>airtelRepresentative</fullName>
                <label>AIRTEL_REPRESENTATIVE</label>
            </value>
            <value>
                <fullName>airtelApprovals</fullName>
                <label>AIRTEL_APPROVALS</label>
            </value>
            <value>
                <fullName>wEmail</fullName>
                <label>WELCOME_EMAIL</label>
            </value>
            <value>
                <fullName>loc</fullName>
                <label>LOC</label>
            </value>
            <value>
                <fullName>projectProgress</fullName>
                <label>PROJECT_PROGRESS</label>
            </value>
            <value>
                <fullName>serviceHandover</fullName>
                <label>SERVICE_HANDOVER</label>
            </value>
            <value>
                <fullName>site</fullName>
                <label>SITE</label>
            </value>
            <value>
                <fullName>pm</fullName>
                <label>PM</label>
            </value>
            <value>
                <fullName>cpe</fullName>
                <label>CPE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_DocumentDownloadController.cls
/******************************************************************************************************
* @Author       : arka.bhattacharjee@salesforce.com
* @Company      : Salesforce
* @Date         : 05-Dec-2023
* @Test Class   : ARTL_DocumentDownloadControllerTest
* @Description  : Controller for artl_DocumentDownload LWC
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect      Developer             Date             Comment
*                         Arka Bhattacharjee    05-Dec-2023      Initial Dev
*******************************************************************************************************/
public class ARTL_DocumentDownloadController {
/******************************************************************************************************
 * Method Name        : getDocumentsWire
 * Method Description : Get the Documents
*******************************************************************************************************/    
    @AuraEnabled(cacheable=true)
    public static List<ARTL_Document__c> getDocumentsWire(String recId, String objAPIName){
        return ARTL_DocumentDownloadController.getDocuments(recId, objAPIName);
    }
/******************************************************************************************************
 * Method Name        : getDocuments
 * Method Description : Get the Documents
*******************************************************************************************************/
    @AuraEnabled
    public static List<ARTL_Document__c> getDocuments(String recId, String objAPIName){
        List<ARTL_Document__c> docList = new List<ARTL_Document__c>();
        if(objAPIName == 'Account'){
            docList = [Select Id, Document_Name__c, toLabel(Category__c), toLabel(Type__c), s3_Document_URL__c, Error_Message__c 
                       From ARTL_Document__c Where Account__c = :recId Order By CreatedDate DESC];
        } else if(objAPIName == 'Contact'){
            docList = [Select Id, Document_Name__c, toLabel(Category__c), toLabel(Type__c), s3_Document_URL__c, Error_Message__c 
                       From ARTL_Document__c Where Contact__c = :recId Order By CreatedDate DESC];
        } else if(objAPIName == 'Opportunity'){
            docList = [Select Id, Document_Name__c, toLabel(Category__c), toLabel(Type__c), s3_Document_URL__c, Error_Message__c 
                       From ARTL_Document__c Where Opportunity__c = :recId Order By CreatedDate DESC];
        } else if(objAPIName == 'Quote'){
            docList = [Select Id, Document_Name__c, toLabel(Category__c), toLabel(Type__c), s3_Document_URL__c, Error_Message__c 
                       From ARTL_Document__c Where Quote__c = :recId Order By CreatedDate DESC];
        } else if(objAPIName == 'Order'){
            docList = [Select Id, Document_Name__c, toLabel(Category__c), toLabel(Type__c), s3_Document_URL__c, Error_Message__c 
                       From ARTL_Document__c Where Order__c = :recId Order By CreatedDate DESC];
        }
        return docList;
    }
/******************************************************************************************************
 * Method Name        : makeDocDownloadloadCallout
 * Method Description : Call IP for Doc Download Callout
*******************************************************************************************************/
    @AuraEnabled
    public static Map<String,Object> makeDocDownloadloadCallout(String docId){
        Map<String,Object> response = new Map<String,Object>();
        try{
            Map<String,Object> input = new Map<String,Object>();
            input.put('processName', 'DocumentDownload');
            //input.put('c', 'Basic YWRtaW46aUBtT3AzblMzYzIzMnQ=');
            input.put('source', 'leo');
            input.put('ContextId', docId);    
            Map<String,Object> outMap = new Map<String,Object>();
            ARTL_CalloutEventHandler ceh = new ARTL_CalloutEventHandler();
            ceh.invokeMethod('initiateCallout', input, outMap, null);
            response = (Map<String,Object>)outMap.get('response');
        }catch(Exception ex){
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_DocumentDownloadController:makeDocDownloadloadCallout',
                              '', new Map<String,Object>{'Exception'=>ex.getMessage() , 'LineNumber' => ex.getLineNumber()}, ex);
        }
        return response;
    }
}