force-app/main/default/objects/ARTL_Document__c/ARTL_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Document__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>organizationDocument</fullName>
                <label>ORGANIZATION_DOCUMENT</label>
            </value>
            <value>
                <fullName>authorizedSignatory</fullName>
                <label>AUTHORIZED_SIGNATORY</label>
            </value>
            <value>
                <fullName>order</fullName>
                <label>ORDER</label>
            </value>
            <value>
                <fullName>email</fullName>
                <label>EMAIL</label>
            </value>
            <value>
                <fullName>serviceHandover</fullName>
                <label>SERVICE_HANDOVER</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST certificate</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>TnC</fullName>
            </value>
            <value>
                <fullName>AutSigDoc</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>Caf</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
            <value>
                <fullName>OrderTemplate</fullName>
            </value>
            <value>
                <fullName>KDM</fullName>
            </value>
            <value>
                <fullName>DOA</fullName>
            </value>
            <value>
                <fullName>Welcome_Email</fullName>
            </value>
            <value>
                <fullName>LOC_Email</fullName>
            </value>
            <value>
                <fullName>Project_Status</fullName>
            </value>
            <value>
                <fullName>ServiceDocuments</fullName>
            </value>
            <value>
                <fullName>Site_Activation</fullName>
            </value>
            <value>
                <fullName>PM_Approval</fullName>
            </value>
            <value>
                <fullName>CPE_Recovery</fullName>
            </value>
            <value>
                <fullName>POI</fullName>
            </value>
            <value>
                <fullName>LOA</fullName>
            </value>
            <value>
                <fullName>LOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>poe</fullName>
                <label>POE</label>
            </value>
            <value>
                <fullName>live_photo</fullName>
                <label>LIVE_PHOTO</label>
            </value>
            <value>
                <fullName>order</fullName>
                <label>ORDER</label>
            </value>
            <value>
                <fullName>cust</fullName>
                <label>CUST</label>
            </value>
            <value>
                <fullName>misc</fullName>
                <label>MISC</label>
            </value>
            <value>
                <fullName>template</fullName>
                <label>TEMPLATE</label>
            </value>
            <value>
                <fullName>airtelRepresentative</fullName>
                <label>AIRTEL_REPRESENTATIVE</label>
            </value>
            <value>
                <fullName>airtelApprovals</fullName>
                <label>AIRTEL_APPROVALS</label>
            </value>
            <value>
                <fullName>wEmail</fullName>
                <label>WELCOME_EMAIL</label>
            </value>
            <value>
                <fullName>loc</fullName>
                <label>LOC</label>
            </value>
            <value>
                <fullName>projectProgress</fullName>
                <label>PROJECT_PROGRESS</label>
            </value>
            <value>
                <fullName>serviceHandover</fullName>
                <label>SERVICE_HANDOVER</label>
            </value>
            <value>
                <fullName>site</fullName>
                <label>SITE</label>
            </value>
            <value>
                <fullName>pm</fullName>
                <label>PM</label>
            </value>
            <value>
                <fullName>cpe</fullName>
                <label>CPE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/PO_Group__c.field-meta.xml
<CustomField>
    <fullName>PO_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Group</label>
    <referenceTo>PO_Group__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Upload_Config__mdt/Document_Upload_Config__mdt.object-meta.xml
<CustomObject>
    <label>Document Upload Config</label>
    <pluralLabel>Document Upload Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Document_Upload_Config__mdt/fields/Mandatory_for_OV_Approval__c.field-meta.xml
<CustomField>
    <fullName>Mandatory_for_OV_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory for OV Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Upload_Config__mdt/fields/Object_Level__c.field-meta.xml
<CustomField>
    <fullName>Object_Level__c</fullName>
    <label>Object Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Upload_Config__mdt/fields/Product_Codes__c.field-meta.xml
<CustomField>
    <fullName>Product_Codes__c</fullName>
    <label>Product Codes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PO_Group__c/PO_Group__c.object-meta.xml
<CustomObject>
    <label>PO Group</label>
    <nameField>
        <displayFormat>71-8{0000000}</displayFormat>
        <label>PO Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PO_Group__c/fields/ARTL_PO_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Group_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Group Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Term__c.field-meta.xml
<CustomField>
    <fullName>PO_Term__c</fullName>
    <label>PO Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Value__c.field-meta.xml
<CustomField>
    <fullName>PO_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PO Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_DocumentUploadControllerTest.cls
/******************************************************************************************************
* @Author       : arka.bhattacharjee@salesforce.com
* @Company      : Salesforce
* @Date         : 27-Dec-2023
* @Test Class   :
* @Description  : Test Class for ARTL_DocumentUploadController
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect      Developer             Date             Comment
*                         Arka Bhattacharjee    27-Dec-2023      Initial Dev
*******************************************************************************************************/
@isTest
public class ARTL_DocumentUploadControllerTest {
/******************************************************************************************************
 * Method Name        : setup
 * Method Description : Test Data 
*******************************************************************************************************/
    @testSetup 
    static void setup() {
         Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId);
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId);
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId);
        insert accounts;
        
        Product2[] products = new Product2[2];
        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();
        
        for (Integer i=0; i<products.size(); i++){
            pbes[i] = new PricebookEntry(product2Id = products[i].id, 
                                         IsActive = true, 
                                         unitPrice = 10, 
                                         pricebook2id = pbId, 
                                         useStandardPrice = false);
        }
        
        insert pbes;
        
        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, 
                                                                      vlocity_cmt__IsActive__c = true, 
                                                                      vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = accounts[0].id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;
        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
        qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
        
        PO_Group__c poGroup = new PO_Group__c();
        poGroup.ARTL_PO_Group_Number__c = '123';
        insert poGroup;
        
        PO_Group__c poGroup1 = new PO_Group__c();
        poGroup1.ARTL_PO_Group_Number__c = '1234';
        insert poGroup1;
        
        ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
        PurchaseOrder.ARTL_PO_Number__c = '111111';
        PurchaseOrder.PO_Group__c = poGroup.id;
        insert PurchaseOrder;
        
        QuoteLineItem  quoteLine1 = new QuoteLineItem ();
        quoteLine1.UnitPrice = 1;
        quoteLine1.Quantity = 1;
        quoteLine1.Product2Id = products[1].Id;
        quoteLine1.vlocity_cmt__Product2Id__c = products[1].Id;
        quoteLine1.QuoteId =qtest.Id;
        quoteLine1.PricebookEntryId=pbes[0].Id;
        quoteLine1.vlocity_cmt__Action__c='Change';
        quoteLine1.ARTL_Purchase_Order__c = PurchaseOrder.Id;
        quoteLine1.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine1.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        insert quoteLine1;
        
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'GST certificate';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        
        insert cv;
        
        ARTL_Document__c doc = new ARTL_Document__c();
        doc.Category__c = 'organizationDocument';
        doc.Type__c = 'poe';
        doc.Document_Name__c = 'PAN';
        doc.quote__c=qtest.id;
        insert doc;
        
       /* Document_Upload_Config__mdt DConfig= new Document_Upload_Config__mdt();
		
		DConfig.MasterLabel='GST certificate';
		Dconfig.DeveloperName='GST_certificate_Internet';
		Dconfig.Mandatory_for_OV_Approval__c=true;
		Dconfig.Object_Level__c='Quote';
		Dconfig.Product_Codes__c='3c6df3ca-4424-4131-bde3-c3ea5d5b5925';
		insert Dconfig;*/
        
       
    }
/******************************************************************************************************
 * Class Name        : UploadMockCallout
 * Class Description : Creating Mock Callout and HTTP Response for Test Class 
*******************************************************************************************************/
    public class UploadMockCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"identifier":"00000","source":"leo","document":{"name":"Test","urls":[{"url":"www.example.com"}]}}');
            response.setStatusCode(200);
            return response; 
        }
    }
/******************************************************************************************************
 * Method Name        : testDocUpload
 * Method Description : Testing Doc Upload Callout method
*******************************************************************************************************/
    @isTest
    public static void testDocUpload(){
        ARTL_Document__c doc = [Select Id From ARTL_Document__c Limit 1];
        ContentVersion cv = [SELECT Id, Title, ContentDocumentId FROM ContentVersion Limit 1];
        Test.setMock(HttpCalloutMock.class, new UploadMockCallout());
        Test.startTest();
        ARTL_DocumentUploadController.makeDocUploadCallout(doc.Id,cv.Id);
        Test.stopTest();
    }
/******************************************************************************************************
 * Method Name        : testDocUploadErr
 * Method Description : Testing Doc Upload Callout catch method
*******************************************************************************************************/
    @isTest
    public static void testDocUploadErr(){
        Test.startTest();
        ARTL_DocumentUploadController.makeDocUploadCallout('','');
        ARTL_DocumentUploadController.makeAPICallout(null);
        Test.stopTest();
    }
    @isTest
    public static void testValidateDoc(){
        Test.startTest();
        ARTL_DocumentUploadController.validateDoc([select id from quote limit 1].Id,'Quote');
        Test.stopTest();
    }
}