force-app/main/default/objects/Product2/fields/ARTL_LSIRequired__c.field-meta.xml
<CustomField>
    <fullName>ARTL_LSIRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LSI Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/vlocity_cmt__Type__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Shifting</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Rate Revision</fullName>
            </value>
            <value>
                <fullName>Rebilling</fullName>
            </value>
            <value>
                <fullName>L1-L3 Construct Change</fullName>
            </value>
            <value>
                <fullName>PO Renewal</fullName>
            </value>
            <value>
                <fullName>LSI Transfer</fullName>
            </value>
            <value>
                <fullName>Hardware Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Validation_Status__c</fullName>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrichment Completed</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>To be Validated</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Validation_Message__c.field-meta.xml
<CustomField>
    <fullName>Validation_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Validation Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_QuoteValidationController.cls
public without sharing class ARTL_QuoteValidationController {

    private static final String RATE_REVISION = 'Rate Revision';
    private static final String REBILLING = 'Rebilling';
    private static final String FX_VALIDATION_FAILED_MSG = 'Fx Validation Failed. ';
    private static final String FX_VALIDATION_FAILED_MSG_LSI = 'Fx Validation has been failed for following Line Items: ';
    
    @AuraEnabled
    public static String checkQuoteValidation(Id recId) {
       
        List<QuoteLineItem> quoteLineItems = [
            SELECT Id, ARTL_LSI__c
            FROM QuoteLineItem
            WHERE QuoteId = :recId AND vlocity_cmt__Product2Id__r.ARTL_LSIRequired__c = true AND 
            ( (ARTL_Validation_Status__c != 'To be Validated' AND ARTL_Validation_Status__c != 'Passed') OR
            ARTL_Validation_Status__c = 'Failed' ) 
            LIMIT 1
        ];
        
        if (!quoteLineItems.isEmpty()) {
            return  string.valueof(quoteLineItems[0].ARTL_LSI__c) ;
        }
        else {
            //KB: IF QLIs are exist to be validated then doing FX Validation
            List<QuoteLineItem> qliUpdateList = new List<QuoteLineItem> ();
            Set<String> failedLIs = new Set<String>();
            for(QuoteLineItem obj: [SELECT Id, lineNumber, ARTL_Effective_Change_Date__c, ARTL_Effective_Date__c  
                                    FROM QuoteLineItem
                                    WHERE QuoteId = :recId AND 
                                    (quote.vlocity_cmt__Type__c = :RATE_REVISION OR quote.vlocity_cmt__Type__c = :REBILLING)] 
            ){
                if(obj.ARTL_Effective_Change_Date__c == null || obj.ARTL_Effective_Date__c == null || 
                    (obj.ARTL_Effective_Change_Date__c < (obj.ARTL_Effective_Date__c).date())
                ){
                    qliUpdateList.add(new QuoteLineItem(id = obj.id, ARTL_Validation_Status__c = 'Failed', Validation_Message__c = FX_VALIDATION_FAILED_MSG));
                    failedLIs.add(obj.lineNumber);
                }
            }
            if(!qliUpdateList.isEmpty()){
                update qliUpdateList;
                return FX_VALIDATION_FAILED_MSG_LSI + String.join((Iterable<String>)failedLIs, ', ');
            }else{

                ARTL_ValidateStagingData batchClassInstance = new ARTL_ValidateStagingData(string.valueof(recId),false);
                Database.executeBatch(batchClassInstance);
            }
                
        }
       return 'In-Progress';
    }

    @AuraEnabled(cacheable=true)
    public static Id getReportId(){

        List<report> report=[SELECT Id FROM Report WHERE Name='ARTL QLI Validation'];
        if(report.size()>0){
            return report[0].Id;
        }
        else{
            return null;
        }
    }

    
}