force-app/main/default/objects/ARTL_Integration_Details__c/ARTL_Integration_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Details</label>
</CustomObject>

force-app/main/default/objects/ARTL_Integration_Details__c/fields/ARTL_API_Key__c.field-meta.xml
<CustomField>
    <fullName>ARTL_API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Integration_Details__c/fields/ARTL_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_State__c.field-meta.xml
<CustomField>
    <fullName>ARTL_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli and Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>International Cities</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_State_Code__c</fullName>
    <label>State Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_FeasibilityAddressVerificationBTest.cls
/******************************************************************************************************
* @Author:      Saurav Madhusoodanan TV  <smadhusoodanantv@salesforce.com >
* @Company:     Salesforce
* @Date:        21/12/2023
* @Reviewer:
* @Review Date:
* @Description: Test class for ARTL_FeasibilityAddressVerificationBatch
* ++++++++++++++++++++++ Changes Implemented / Modification Log ++++++++++++++++++++++++++++++++++++++
* UserStory / Defect      Developer             Date           Comment
* ------------------      ---------------       -----------    ----------------------------------------
* 
*******************************************************************************************************/
@isTest
public class ARTL_FeasibilityAddressVerificationBTest {

    @isTest
    static void positiveTest() {
        // Get a user for test execution context
        User usr = ARTL_ValidateStagingDataHelper.getUser();

        // Run test as the specified user
        System.runAs(usr) {
            // Start test execution
            Test.startTest();

            // Create test data for Accounts, PriceLists, Opportunities, Quotes, QuoteGroups, PinCodes, Integration Details, and QuoteMembers
            List<Account> accountList = ARTL_TestDataFactory.createAccount('Business', true, 1);
            Set<Id> accountIdSet = new Set<Id>{accountList[0].Id};

            List<vlocity_cmt__PriceList__c> vlocityPriceList = ARTL_TestDataFactory.createVlocityPriceList(Test.getStandardPricebookId(), true, 1);

            List<Opportunity> opportunityList = ARTL_TestDataFactory.createOpportunity(accountIdSet, 'Prospecting', vlocityPriceList[0].Id, true, 1);

            List<Quote> quoteList = ARTL_TestDataFactory.createQuote(opportunityList[0].Id, vlocityPriceList[0].Id, Test.getStandardPricebookId(), true, 1);

            vlocity_cmt__QuoteGroup__c testGroup = new vlocity_cmt__QuoteGroup__c(Name = 'Test Group', vlocity_cmt__QuoteId__c = quoteList[0].Id, vlocity_cmt__ExpectedMemberCount__c = 4);
            insert testGroup;

            ARTL_Pincode__c pinCodeRecord = new ARTL_Pincode__c(Name = '110031', ARTL_City__c = 'New Delhi', ARTL_State__c = 'Delhi', ARTL_State_Code__c = '7', ARTL_Country__c = 'India');
            insert pinCodeRecord;

            ARTL_Integration_Details__c integrationDetails = new ARTL_Integration_Details__c(
                Name = 'AddressVerification',
                ARTL_Endpoint__c = 'https://b2benterprisebusiness.airtel.com/b2b-oft/feasibility/map/address',
                ARTL_API_Key__c = 'YWZjMWM0NTgtN2JiMi01ZWYzLThjNzMtZTBkMDEyNTA4ODQz'
            );
            insert integrationDetails;

            ARTL_TestDataFactory.createQuoteMembers2(quoteList[0].Id, 'Durant Avenue', testGroup.Id, 3, 'Location');

            // Create a mock HTTP response with sample data
            HttpMockFactory mock = new HttpMockFactory(
                200,
                'Success',
                '{"requestId":"10192781055999244191703129660372","data":{"address":{"id":"TPT1027600654-2113830758TPT_GIS","originalAddressString":"Mumbai,India","addressString":"barca zindia house, parel, mumbai","locality":"parel","sublocality":"barca zindia house","state":"maharashtra","city":"Mumbai","pincode":"400012","latitude":"18.996425","longitude":"72.840438","highRise":false,"errorMargin":"50","source":"GIS","pinCode":"400012"}}}'
            );

            // Set up the mock HTTP callout
            Test.setMock(HttpCalloutMock.class, mock);

            // Execute the batch job and get the batch process ID
            String batchProcessId = Database.executeBatch(new ARTL_FeasibilityAddressVerificationBatch(quoteList[0].Id));

            // Assert that the batch process ID is not null, indicating a successful execution
            System.assertNotEquals(null, batchProcessId);

            // Stop test execution
            Test.stopTest();
        }
    }
}