force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000000}</displayFormat>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
                <default>true</default>
                <label>2024</label>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Config__mdt/ARTL_Bulk_Upload_Config__mdt.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Config</label>
    <pluralLabel>ARTL_Bulk_Upload_Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Config__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Config__mdt/fields/File_Header_CSV__c.field-meta.xml
<CustomField>
    <fullName>File_Header_CSV__c</fullName>
    <label>File Header CSV</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Config__mdt/fields/Object_Fields__c.field-meta.xml
<CustomField>
    <fullName>Object_Fields__c</fullName>
    <label>Object Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/recordTypes/BUC.recordType-meta.xml
<RecordType>
    <fullName>BUC</fullName>
    <active>true</active>
    <label>BUC</label>
</RecordType>

force-app/main/default/classes/ARTL_BulkUploadCtrlTest.cls
@isTest
public class ARTL_BulkUploadCtrlTest {
        
    @testSetup
    public static void testData(){
        ARTL_Bulk_Upload_Config__mdt obj = NEW ARTL_Bulk_Upload_Config__mdt();
        obj.Field_API_Name__c = 'Account Number,Fiscal Year,Product Category,Total Competitor Spend,Spends with Airtel,Key Competitor and Comments,Account Plan';
        obj.File_Header_CSV__c = 'Account_Number__c,Fiscal_Year__c,Product_Category__c,Total_Competitor_Spends__c,Spends_with_Airtel__c,Key_Competitor_and_Comments__c,Account_Plan__c';
        obj.Object_Fields__c = 'Account_Number__c,Fiscal_Year__c,Product_Category__c,Total_Competitor_Spends__c,Spends_with_Airtel__c,Key_Competitor_and_Comments__c,Account_Plan__c,Account_Name__c';
        obj.DeveloperName = 'BUC';
        obj.Template_URL__c = 'www.google.com';
        //insert obj;
        
        ARTL_Bulk_Upload_Iteration__c  ite = NEW ARTL_Bulk_Upload_Iteration__c ();
        ite.Name = 'BUC';
        ite.File_Name__c = 'sample.csv';
        insert ite;
        
    }

    @isTest
    public static void getMetadataConfigTest(){
        Test.startTest();
        Map<String,Object> res = ARTL_BulkUploadCtrl.getMetadataConfig();
        Test.stopTest();
    }
    
    @isTest
    public static void createIterationTest(){
        String fileName = 'test.csv';
        String typeIs = 'BUC';
        Test.startTest();
        string iteId = ARTL_BulkUploadCtrl.createIteration(fileName,typeIs);
        Test.stopTest();
    }
    
    @isTest
    public static void inititeValidationBatchTest(){
        String typeIs = 'BUC';
        List<ARTL_Bulk_Upload_Iteration__c> ite = [SELECT id FROM ARTL_Bulk_Upload_Iteration__c limit 1];
        Test.startTest();
        ARTL_BulkUploadCtrl.inititeValidationBatch(ite[0].Id,typeIs);
        Test.stopTest();
    }
    
    @isTest
    public static void uploadDataTest(){
        List<Object> csv = new List<Object>();
        Object str = 'BS-00000050,2023,Multiplay,7643,3336,testtest1,AP-0000022, BS-00000050,2023,Multiplay,7646,333,testtest2,';
        csv.add(str);
        String header = 'Account Number,Fiscal Year,Product Category,Total Competitor Spends,Spends with Airtel,Key Competitor and Comments,Account Plan';
        String typeObj = 'BUC';
        List<ARTL_Bulk_Upload_Iteration__c> ite = [SELECT id FROM ARTL_Bulk_Upload_Iteration__c limit 1];
        Test.startTest();
        ARTL_BulkUploadCtrl.uploadData(csv,header,typeObj,ite[0].Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getTemplateTest(){
        Test.startTest();
        ARTL_BulkUploadCtrl.getTemplate('BUC');
        Test.stopTest() ;
    }
}