force-app/main/default/objects/Account/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_Pincode_City__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Pincode_City__c</fullName>
    <formula>Name +  &apos; - &apos; + ARTL_City__c</formula>
    <label>Pincode City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_State__c.field-meta.xml
<CustomField>
    <fullName>ARTL_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli and Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>International Cities</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Alternate_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_BCP_DCP_Search_String__c.field-meta.xml
<CustomField>
    <fullName>ARTL_BCP_DCP_Search_String__c</fullName>
    <formula>BCP_DCP_Number__c + &apos; - &apos; + Contact__r.FirstName + &apos; - &apos; + Contact__r.LastName + &apos; - &apos; + Contact__r.Phone + &apos; - &apos; +
    Contact__r.Email + &apos; - &apos; + Premises__r.vlocity_cmt__StreetAddress__c + &apos; - &apos; + Premises__r.vlocity_cmt__City__c +
    &apos; - &apos; + Premises__r.vlocity_cmt__State__c + &apos; - &apos; + Premises__r.vlocity_cmt__PostalCode__c + &apos; - &apos; + GST__r.Name + &apos; - &apos; +
    TEXT(ARTL_Standard_Reason__c)</formula>
    <label>BCP/DCP Search String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <label>GST Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_NBA_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NBA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NBA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__Premises__c/fields/ARTL_Pincode__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>ARTL_Pincode__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_UpdateBcpDcpLwcController.cls
/**
* @description       : Used in ARTL_updateBcpDcpLwc for Update BCP/DCP functionality
* @test class        : ARTL_UpdateBcpDcpLwcControllerTest
* @author            : Rishab Kalra
* @last modified on  : 12-27-2023
**/
public without sharing class ARTL_UpdateBcpDcpLwcController {
    public static boolean isUpdateBcpDcp = false;
    public class CustomException extends Exception {}
    
    @AuraEnabled
    public static List<ARTL_Pincode__c> getPincodeDetails(String searchKey){
        String key = '%'+searchKey+'%';
        return [Select Id, Name, ARTL_Pincode_City__c, ARTL_City__c, ARTL_State__c, ARTL_Country__c 
               FROM ARTL_Pincode__c where ARTL_Pincode_City__c like :key LIMIT 50];
    }

    @AuraEnabled
    public static List<ContactPremiseRelation__c> getContactRecords(String nbaAccountId){
        try {
            System.debug('DEBUGG nbaAccountId '+ nbaAccountId);
            if(!String.isBlank(nbaAccountId)){
                List<ContactPremiseRelation__c> listOfContactPremiseRelation = [Select Id, ARTL_BCP_DCP_Search_String__c 
                                                                                from ContactPremiseRelation__c 
                                                                                where ARTL_NBA_Account__c = :nbaAccountId];
                return listOfContactPremiseRelation; 
            }
            if(Test.isRunningTest()){
                throw new AuraHandledException('Test Class.');
            }
            return null;
            
        } catch (Exception ex) {
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_UpdateBcpDcpLwcController:getContactRecords', '', new Map<String, Object>{'Exception' => ex.getMessage(), 'LineNumber' => ex.getLineNumber()}, ex);
            return null;
        }
    }
    
    @AuraEnabled
    public static List<ContactPremiseRelation__c> getRecordDetails(String selectedRecordId){
        try {
            System.debug('DEBUGG selectedRecordId '+ selectedRecordId);
            if(!String.isBlank(selectedRecordId)){
                List<ContactPremiseRelation__c> recordList = [Select Id, Contact__c, Contact__r.Salutation, Contact__r.FirstName, Contact__r.ARTL_Designation__c, 
                                                              Contact__r.MiddleName, Contact__r.LastName, Contact__r.Email, Contact__r.ARTL_Alternate_Email__c, 
                                                              Contact__r.MobilePhone, Contact__r.Phone, Contact__r.Fax, Contact__r.ARTL_Contact_Role__c, Role__c, Premises__c,
                                                              Contact__r.vlocity_cmt__Status__c, ARTL_GST_Applicable__c, ARTL_Standard_Reason__c,
                                                              ARTL_NBA_Account__c, ARTL_NBA_Account__r.ParentId, 
                                                              Premises__r.ARTL_Pincode__c,
                                                              Premises__r.vlocity_cmt__StreetAddress__c, 
                                                              Premises__r.vlocity_cmt__City__c, 
                                                              Premises__r.vlocity_cmt__State__c, 
                                                              Premises__r.vlocity_cmt__PostalCode__c, 
                                                              Premises__r.vlocity_cmt__Country__c,
                                                              GST__c, GST__r.Name
                                                              from ContactPremiseRelation__c 
                                                              where Id = :selectedRecordId];
                if(!recordList.isEmpty()){
                    return recordList;
                }
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void updateRecords(Map<String, String> recordDetailsOld, Map<String, String> recordDetails){
        Savepoint sp = Database.setSavepoint();
        try {
            isUpdateBcpDcp = true;
            System.debug('DEBUGG update bcp dcp '+ isUpdateBcpDcp);
            List<ContactPremiseRelation__c> contactPremiseRelationList = new List<ContactPremiseRelation__c>();
            List<vlocity_cmt__Premises__c> premiseRecordList = new List<vlocity_cmt__Premises__c>();
            String contactRole;
            System.debug('DEBUGG recordDetails '+ recordDetails);
            // if(recordDetails.containsKey('Role__c')){
            //     contactRole = recordDetails.get('Role__c') == 'BCP' ? 'Billing Contact' : recordDetails.get('Role__c') == 'DCP' ? 'Delivery Contact' : 'Delivery/Billing Contact';
            // }
            if((recordDetailsOld.get('City') != recordDetails.get('City')) || 
               recordDetailsOld.get('StreetAddress') != recordDetails.get('StreetAddress') ||
              recordDetailsOld.get('PostalCode') != recordDetails.get('PostalCode') ){
                   premiseRecordList.add(createPremiseRecord(recordDetails)); 
               }
            
            if(!premiseRecordList.isEmpty()){
                for(Database.SaveResult sr: Database.update(premiseRecordList)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully updated premiseRecordList - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            
            List<Contact> contactUpdateList = new List<Contact>();
            contactUpdateList.add(new Contact(Id 						= recordDetails.containsKey('Id') ? recordDetails.get('Id') : null, 
                                              Salutation 				= recordDetails.containsKey('Salutation') ? recordDetails.get('Salutation') : null, 
                                              FirstName 				= recordDetails.containsKey('FirstName') ? recordDetails.get('FirstName') : null,
                                              MiddleName 				= recordDetails.containsKey('MiddleName') ? recordDetails.get('MiddleName') : null,
                                              LastName 					= recordDetails.containsKey('LastName') ? recordDetails.get('LastName') : null, 
                                              Email 					= recordDetails.containsKey('Email') ? recordDetails.get('Email') : null,
                                              Phone 					= recordDetails.containsKey('Phone') ? recordDetails.get('Phone') : null, 
                                              ARTL_Alternate_Email__c 	= recordDetails.containsKey('ARTL_Alternate_Email__c') ? recordDetails.get('ARTL_Alternate_Email__c') : null, 
                                              Fax 						= recordDetails.containsKey('Fax') ? recordDetails.get('Fax') : null,
                                              ARTL_Designation__c 		= recordDetails.containsKey('ARTL_Designation__c') ? recordDetails.get('ARTL_Designation__c') : null,
                                              vlocity_cmt__Status__c    = recordDetails.containsKey('vlocity_cmt__Status__c') ? recordDetails.get('vlocity_cmt__Status__c') : null));
                                              //ARTL_Contact_Role__c 		= contactRole));
            
            if(!contactUpdateList.isEmpty()){
                for(Database.SaveResult sr: Database.update(contactUpdateList)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully updated contactUpdateList - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            List<ContactPremiseRelation__c> contactPremiseRelationRecord = [Select Id from ContactPremiseRelation__c 
                                                                            where Role__c = 'DCP' 
                                                                            and Contact__c = :contactUpdateList[0].Id
                                                                            and ARTL_NBA_Account__c = :recordDetails.get('ARTL_NBA_Account__c')];
            Boolean dcpRecordExists = false;
            if(contactPremiseRelationRecord.size() > 0) dcpRecordExists = true;
            List<ContactPremiseRelation__c> contactPremiseRelationRecordBCP = [Select Id from ContactPremiseRelation__c 
                                                                               where Role__c = 'BCP' 
                                                                               and Contact__c = :contactUpdateList[0].Id
                                                                               and ARTL_NBA_Account__c = :recordDetails.get('ARTL_NBA_Account__c')];
            Boolean bcpRecordExists = false;
            if(contactPremiseRelationRecordBCP.size() > 0) bcpRecordExists = true;
            if(recordDetailsOld.get('Role__c') != recordDetails.get('Role__c')){
                if(recordDetails.get('Role__c') == 'BCP'){
                    contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, recordDetails.get('Role__c'), true));  
                }
                if(recordDetails.get('Role__c') == 'DCP'){
                    contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, recordDetails.get('Role__c'), true));
                }
                if(recordDetails.get('Role__c') == 'BCPandDCP'){
                    if(!bcpRecordExists){
                        contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, 'BCP', false));
                    }
                    else {
                        recordDetails.put('ContactPremiseId', contactPremiseRelationRecordBCP[0].Id);
                        contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, 'BCP', true));
                    }
                    if(!dcpRecordExists){
                        contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, 'DCP', false));
                    } else {
                        recordDetails.put('ContactPremiseId', contactPremiseRelationRecord[0].Id);
                        contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, 'DCP', true));
                    }
                }
            }
            else{
                contactPremiseRelationList.add(createContactPremiseRelation(recordDetails, recordDetails.get('Role__c'), true));
            }
            

            if(!contactPremiseRelationList.isEmpty()){
                for(Database.UpsertResult sr: Database.upsert(contactPremiseRelationList)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted contactPremiseRelationList - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            List<AccountContactRelation> accountContactRelationUpdateList = createAccountContactRelation(recordDetails);
            
            if(!accountContactRelationUpdateList.isEmpty()){
                for(Database.SaveResult sr: Database.update(accountContactRelationUpdateList)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully updated accountContactRelationUpdateList - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            
        } catch (Exception ex) {
            System.debug('DEBUGG exception '+ ex.getMessage()+ ' '+ ex.getLineNumber());
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_UpdateBcpDcpLwcController:updateRecord', '', new Map<String, Object>{'Exception' => ex.getMessage(), 'LineNumber' => ex.getLineNumber()}, ex);
            Database.rollback(sp);
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    public static vlocity_cmt__Premises__c createPremiseRecord(Map<String, String> recordDetails){
        try{
            System.debug('DEBUGG createPremiseRecord '+ recordDetails);
            vlocity_cmt__Premises__c premiseRecord = new vlocity_cmt__Premises__c(
                Id = recordDetails.containsKey('Premises__c') ? recordDetails.get('Premises__c') : null,
                vlocity_cmt__StreetAddress__c = recordDetails.containsKey('StreetAddress') ? recordDetails.get('StreetAddress') : null,
                vlocity_cmt__City__c 		= recordDetails.containsKey('City') ? recordDetails.get('City') : null, 
                vlocity_cmt__State__c  		= recordDetails.containsKey('State') ? recordDetails.get('State') : null, 
                vlocity_cmt__Country__c  	= recordDetails.containsKey('Country') ? recordDetails.get('Country') : null, 
                vlocity_cmt__PostalCode__c  = recordDetails.containsKey('PostalCode') ? recordDetails.get('PostalCode') : null,
                ARTL_Pincode__c             = recordDetails.containsKey('ARTL_Pincode__c') ? recordDetails.get('ARTL_Pincode__c') : null);
            return premiseRecord;
            
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    public static List<AccountContactRelation> createAccountContactRelation(Map<String, String> recordDetails){
        List<AccountContactRelation> accountContactRelationUpdateList = new List<AccountContactRelation>();
        if(recordDetails.containsKey('Id') && recordDetails.containsKey('BusinessAccountId') && recordDetails.containsKey('ARTL_NBA_Account__c')){
            for(AccountContactRelation acr: [Select Id, Roles from AccountContactRelation
                                             where ContactId = :recordDetails.get('Id')
                                             and (AccountId = :recordDetails.get('BusinessAccountId') 
                                                  or AccountId = :recordDetails.get('ARTL_NBA_Account__c'))]){
                                                      if(acr.Roles != recordDetails.get('Role__c')){
                                                          if(recordDetails.get('Role__c') == 'BCPandDCP'){
                                                              acr.Roles = 'BCP;DCP';
                                                          }
                                                          else{
                                                              acr.Roles = recordDetails.get('Role__c');
                                                          }
                                                          accountContactRelationUpdateList.add(acr);
                                                      } 
                                                 }
        }
        return accountContactRelationUpdateList;
    }
    
    public static ContactPremiseRelation__c createContactPremiseRelation(Map<String, String> recordDetails, String role, Boolean isUpdate){
        try {
            System.debug('DEBUGG createContactPremiseRelation '+ recordDetails);
            System.debug('DEBUGG createContactPremiseRelation '+ role);
            ContactPremiseRelation__c contactPremiseRelationRecord;
            if(isUpdate){
                contactPremiseRelationRecord = new ContactPremiseRelation__c(
                    Id 							= recordDetails.containsKey('ContactPremiseId') ? recordDetails.get('ContactPremiseId') : null,
                    ARTL_Standard_Reason__c 	= recordDetails.containsKey('ARTL_Standard_Reason__c') ? recordDetails.get('ARTL_Standard_Reason__c') : null,
                    ARTL_GST_Applicable__c 	    = recordDetails.containsKey('ARTL_GST_Applicable__c') ? recordDetails.get('ARTL_GST_Applicable__c') : null,
                    Role__c 					= role, //recordDetails.containsKey('Role__c') ? recordDetails.get('Role__c') : '',
                    Premises__c 				= recordDetails.containsKey('Premises__c') ? recordDetails.get('Premises__c') : null,
                    Contact__c				    = recordDetails.containsKey('Id') ? recordDetails.get('Id') : null, 
                    GST__c						= recordDetails.containsKey('GST__c') ? recordDetails.get('GST__c'): null);
                
            }
            else {
                contactPremiseRelationRecord = new ContactPremiseRelation__c(
                    ARTL_Standard_Reason__c 	= recordDetails.containsKey('ARTL_Standard_Reason__c') ? recordDetails.get('ARTL_Standard_Reason__c') : null,
                    ARTL_GST_Applicable__c 	    = recordDetails.containsKey('ARTL_GST_Applicable__c') ? recordDetails.get('ARTL_GST_Applicable__c') : null,
                    Role__c 					= role, //recordDetails.containsKey('Role__c') ? recordDetails.get('Role__c') : '',
                    Premises__c 				= recordDetails.containsKey('Premises__c') ? recordDetails.get('Premises__c') : null,
                    Contact__c				    = recordDetails.containsKey('Id') ? recordDetails.get('Id') : null,
                    ARTL_NBA_Account__c 		= recordDetails.containsKey('ARTL_NBA_Account__c') ? recordDetails.get('ARTL_NBA_Account__c'): null,
                    GST__c						= recordDetails.containsKey('GST__c') ? recordDetails.get('GST__c'): null);
                
            }
            return contactPremiseRelationRecord;
            
        } catch (Exception e) {
            System.debug('Exception '+ e.getMessage()+' '+e.getLineNumber());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
}