force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_POExpiryBatchTest.cls
@isTest
private class ARTL_POExpiryBatchTest {
    
    @isTest
    static void testARTL_POExpiryBatch() {
        // Create test data
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        List<User> userList = new List<User>();
        User user = new User(LastName = 'Jack',FirstName='Dan', Alias = 'jk', Email = 'Jack.Dan@testorg.com',
                             Username = 'Jack.Dan@testorg.com', ProfileId = profileId.id,TimeZoneSidKey = 'GMT', 
                             LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US');
        userList.add(user);
        
        User user1 = new User(LastName = 'Jack1',FirstName='Dan1', Alias = 'jk', Email = 'Jack.Dan1@testorg.com',
                              Username = 'Jack.Dan1@testorg.com', ProfileId = profileId.id,TimeZoneSidKey = 'GMT', 
                              LanguageLocaleKey = 'en_US',EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US');
        userList.add(user1);
        
        insert userList;
        
        Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId, BillingStreet='Test Street', BillingCity='Mumbai', BillingState='Maharashtra', BillingPostalCode='120006',BillingCountry='India',ARTL_Category__c='A',ARTL_Customer_Segment__c='AB', ARTL_Business_Circle_Region__c='NCR',ARTL_Service_Segment__c='Bharti',ARTL_Vertical_Segment__c='BFI');		
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId, BillingStreet='Test Street', BillingCity='Mumbai', BillingState='Maharashtra', BillingPostalCode='120006',BillingCountry='India',ARTL_Category__c='A',ARTL_Customer_Segment__c='AB', ARTL_Business_Circle_Region__c='NCR',ARTL_Service_Segment__c='Bharti',ARTL_Vertical_Segment__c='BFI');
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId, BillingStreet='Test Street', BillingCity='Mumbai', BillingState='Maharashtra', BillingPostalCode='120006',BillingCountry='India',ARTL_Category__c='A',ARTL_Customer_Segment__c='AB', ARTL_Business_Circle_Region__c='NCR',ARTL_Service_Segment__c='Bharti',ARTL_Vertical_Segment__c='BFI');
        
        if(accounts.size()>0)	{
            insert accounts;    
        }																																																												
        
        
        List<AccountTeamMember> atmTestList = new List<AccountTeamMember>();
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.UserId         = userList[0].Id;
        atm.User           = userList[0];
        atm.TeamMemberRole = 'Collection Manager';
        atm.AccountId      = accounts[0].Id;
        atmTestList.add(atm);
        
        AccountTeamMember atm1 = new AccountTeamMember();
        atm1.UserId         = userList[1].Id;
        atm1.User           = userList[1];
        atm1.TeamMemberRole = 'Secondary KAM';
        atm1.AccountId      = accounts[0].Id;
        atmTestList.add(atm1);
        
        if(atmTestList.size()>0){
            insert atmTestList;    
        }
        
        
        
        List<ARTL_Purchase_Order__c> purchaseOrders = new List<ARTL_Purchase_Order__c>();
        for (Integer i = 0; i < 10; i++) {
            ARTL_Purchase_Order__c po = new ARTL_Purchase_Order__c(
                ARTL_PO_Number__c = 'Test PO ' + i,
                Start_Date__c = Date.today().addDays(-10),
                End_Date__c = Date.today().addDays(30),
                ARTL_Account__c = accounts[0].Id,
                OwnerId = UserInfo.getUserId()
            );
            purchaseOrders.add(po);
        }
        insert purchaseOrders;
        Test.startTest();
        // Start the batch
        ARTL_POExpiryBatch batch = new ARTL_POExpiryBatch();
        Database.executeBatch(batch);
        // Perform assertions based on your requirements
        // For example, check if emails were sent or records were processed as expected
        // You can query the AsyncApexJob object to get information about the batch execution
        Test.stopTest();
        System.assertEquals(0, Limits.getEmailInvocations());
    }
}