force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Pincode__c/fields/ARTL_State__c.field-meta.xml
<CustomField>
    <fullName>ARTL_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli</fullName>
            </value>
            <value>
                <fullName>Dadra and Nagar Haveli and Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Daman and Diu</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>International Cities</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
            <value>
                <fullName>Lakshadweep</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vlocity_cmt__QuoteMember__c/fields/ARTL_Feasibility_Error_Margin__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility_Error_Margin__c</fullName>
    <label>Feasibility Error Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/vlocity_cmt__QuoteMember__c/fields/Feasibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Feasibility_Status__c</fullName>
    <label>Feasibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Feasible</fullName>
            </value>
            <value>
                <fullName>Not Feasible</fullName>
            </value>
            <value>
                <fullName>Feasibility Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandlerTest.cls
@IsTest
public class TriggerHandlerTest extends TriggerHandler{
    //start
    private static final String BUSINESS = 'Business';
    private static final String AT_WORK_D_Series_ADL = 'At Work D-Series ADSL2+ 200GB';
    private static final String AT_WORK_D_Series_ADL_UNLIMITED = 'At Work D-Series ADSL2+ Unlimited';
    private static final String INITIAL_STAGE = 'Initial';
    private static final String NOT_FEASIBLE = 'Not Feasible';
    private static final Id standardBookId =  Test.getStandardPricebookId();
   
    
    @testSetup
    static void setupTestData() {
        //List<Account> testAccounts = ARTL_TestDataFactory.createAccount(BUSINESS, true, 1);
        
         Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account businessAccount = new Account(Name = 'Test Business Account',
                                              RecordTypeId = businessAccountRecordTypeId,
                                              BillingCity = 'Panchkula',
                                              BillingCountry = 'Haryana',
                                              BillingPostalCode = '134109',
                                              BillingState = 'India',
                                              BillingStreet = 'Panchkula',
                                              ARTL_IntegrationId__c = 'test', 
                                              ARTL_Category__c = 'A', 
                                              ARTL_Customer_Segment__c = 'AB',
                                              ARTL_Service_Segment__c = 'BD',
                                              ARTL_Vertical_Segment__c = 'BFI',
                                              ARTL_Business_Circle_Region__c = 'AP',
                                              ARTL_PAN__c = 'ABCDE1234F'
                                              );
        insert businessAccount;
        
        Set<String> productNames = new Set<String>{AT_WORK_D_Series_ADL, AT_WORK_D_Series_ADL_UNLIMITED};
        Set<String> productCodes = new Set<String>{AT_WORK_D_Series_ADL,AT_WORK_D_Series_ADL_UNLIMITED};
        List<Product2> testProducts = ARTL_TestDataFactory.createProduct(productNames,productCodes, true, 2);
        Map<Id, Product2> productMap = new Map<Id, Product2>(testProducts);
        Set<Id> productIds = new Set<Id>(productMap.KeySet());
        List<PriceBookEntry> testPriceBookEntries = ARTL_TestDataFactory.createPricebookEntry(productIds, standardBookId, true, 2);
        List<vlocity_cmt__PriceList__c> testVlocityPLs = ARTL_TestDataFactory.createVlocityPriceList(standardBookId, true, 1);
        List<Opportunity> testopportunities = ARTL_TestDataFactory.createOpportunity(new Set<Id>{businessAccount.Id},INITIAL_STAGE, testVlocityPLs[0].Id, true, 1);
        List<Quote> testQuotes = ARTL_TestDataFactory.createQuote(testopportunities[0].Id, testVlocityPLs[0].Id, standardBookId, true, 1);
        ARTL_Pincode__c pc= new ARTL_Pincode__c(Name='110031',
                                               ARTL_City__c='New Delhi',
                                                ARTL_State__c='Delhi',
                                                ARTL_Country__c='India'
                                               );
        insert pc;
    }
    //end
	@isTest
    static void testIntegrationMethod() {
    	Test.startTest();
     
        
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Account testAccount1 = new Account(Name = 'Test Accountabc');
        insert testAccount1;
        delete testAccount1;
        
        //testAccount.Name = 'Test Accountxyz';
        //update testAccount;
        
        
        TriggerHandler trggrHanler = new TriggerHandler();
       	trggrHanler.setTriggerContext('before insert', true);
        trggrHanler.setTriggerContext('before update', true);
        trggrHanler.setTriggerContext('before delete', true);
        trggrHanler.setTriggerContext('after insert', true);
        trggrHanler.setTriggerContext('after update', true);
        trggrHanler.setTriggerContext('after delete', true);
        trggrHanler.setTriggerContext('after undelete', true);
        
        trggrHanler.addToLoopCount();
        
        
        TriggerHandler.LoopCount lpCnt = new TriggerHandler.LoopCount();
        TriggerHandler.LoopCount lpCnt1 = new TriggerHandler.LoopCount(10);
        lpCnt.increment();
        lpCnt.exceeded();
        lpCnt.getMax();
        lpCnt.getCount();
        lpCnt.setMax(7);
        trggrHanler.setMaxLoopCount(10);
        trggrHanler.clearMaxLoopCount();
        
        TriggerHandler.bypass('ARTL_AccountTriggerHandler');
        TriggerHandler.isBypassed('ARTL_AccountTriggerHandler');
        TriggerHandler.clearBypass('ARTL_AccountTriggerHandler');
        TriggerHandler.clearAllBypasses();
       /* 
       public override void beforeInsert() {
       		System.debug('test class');
    	}
   		protected override void afterInsert() {
       
    	}
    	protected override void afterupdate() {
        
    	}*/
        
        
        
        
 		Test.stopTest();
    }
    
     @isTest
    static void qmUpdateFeasilbilityErrorMarginTest(){
        List<Quote> quoteList=[SELECT Id FROM Quote LIMIT 1];
        Test.startTest();
        vlocity_cmt__QuoteMember__c testRecord = new vlocity_cmt__QuoteMember__c(vlocity_cmt__QuoteId__c = quoteList[0].Id,
                                                                                    Name = 'Test Quote Member',
                                                                                    Feasibility_Status__c  = NOT_FEASIBLE,
                                                                                vlocity_cmt__PostalCode__c='110031',
                                                                                 vlocity_cmt__City__c='New Delhi',
                                                                                 vlocity_cmt__State__c='Delhi',
                                                                                 ARTL_Feasibility_Error_Margin__c=30
                                                                                );
        insert testRecord;
        testRecord.vlocity_cmt__State__c='Kerala';
        testRecord.ARTL_Feasibility_Error_Margin__c=10;
        update testRecord;
        
    	Test.stopTest();

    }
}