force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <label>GST Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_NBA_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NBA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NBA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_UpdateBcpDcpLwcControllerTest.cls
@isTest
public class ARTL_UpdateBcpDcpLwcControllerTest {
    @testSetup
    public static void testData(){
        System.debug('DEBUGG testData ');
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account businessAccount = new Account(Name = 'Test Business Account',
                                              RecordTypeId = businessAccountRecordTypeId,
                                              BillingCity = 'Panchkula',
                                              BillingCountry = 'Haryana',
                                              BillingPostalCode = '134109',
                                              BillingState = 'India',
                                              BillingStreet = 'Panchkula', 
                                              ARTL_IntegrationId__c = 'test', 
                                              ARTL_Category__c = 'A', 
                                              ARTL_Customer_Segment__c = 'AB',
                                              ARTL_Service_Segment__c = 'BD',
                                              ARTL_Vertical_Segment__c = 'BFI',
                                              ARTL_Business_Circle_Region__c = 'AP',
                                              ARTL_PAN__c = 'ABCDE1234F');
        insert businessAccount;
        
        Id nbaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        Account nbaAccount = new Account(Name = 'Test NBA',
                                         RecordTypeId = nbaRecordTypeId, 
                                         ParentId = businessAccount.Id, 
                                         BillingStreet = 'Panchkula',
                                         BillingCity = 'Panchkula',
                                         BillingState = 'Haryana',
                                         BillingPostalCode = '134109',
                                         BillingCountry = 'India', 
                                         ARTL_IntegrationId__c = 'test',
                                         ARTL_Category__c = 'A', 
                                         ARTL_Customer_Segment__c = 'AB',
                                         ARTL_Service_Segment__c = 'BD',
                                         ARTL_Vertical_Segment__c = 'BFI',
                                         ARTL_Business_Circle_Region__c = 'AP');
        insert nbaAccount;
        
        Contact contactRec = new Contact(FirstName 				= 'Test',
                                         LastName				= 'Test',
                                         Phone					= '9887654321', 
                                         Email					= 'test@test.com',
                                         ARTL_Designation__c 	= 'test', 
                                         ARTL_Contact_Role__c 	= 'Billing Contact', 
                                         AccountId 				= nbaAccount.Id,
                                         Country_Code__c		= '91');
        insert contactRec;
        
        vlocity_cmt__Premises__c premiseRecord = new vlocity_cmt__Premises__c(Name = 'test', 
                                                                              vlocity_cmt__StreetAddress__c = 'Panchkula',
                                                                              vlocity_cmt__City__c = 'Panchkula',
                                                                              vlocity_cmt__State__c = 'Haryana',
                                                                              vlocity_cmt__PostalCode__c = '134109',
                                                                              vlocity_cmt__Country__c = 'India');
        insert premiseRecord;
        
        ContactPremiseRelation__c contactPremiseRelationRecord = new ContactPremiseRelation__c(Contact__c = contactRec.Id, 
                                                                                               Premises__c = premiseRecord.Id,
                                                                                               ARTL_NBA_Account__c = nbaAccount.Id,
                                                                                               ARTL_GST_Applicable__c = 'Yes',
                                                                                               ARTL_Standard_Reason__c = 'Exempt',
                                                                                               Role__c = 'BCP');
        insert contactPremiseRelationRecord;
        
    }
    
    @isTest
    public static void testGetRecords(){
        Account nbaAcc = [Select Id from Account where Name = 'Test NBA'];
        List<ContactPremiseRelation__c> returnList = new List<ContactPremiseRelation__c>();
        Test.startTest();
        returnList = ARTL_UpdateBcpDcpLwcController.getContactRecords(nbaAcc.Id);
        Test.stopTest();
        System.assertEquals(returnList.size()>0, true);
    }
    
    @isTest
    public static void testGetRecords2(){
        Account nbaAcc = [Select Id from Account where Name = 'Test NBA'];
        List<ContactPremiseRelation__c> returnList = new List<ContactPremiseRelation__c>();
        Test.startTest();
        returnList = ARTL_UpdateBcpDcpLwcController.getContactRecords('');
        System.debug('DEBUGG Test '+ returnList);
        Test.stopTest();
        System.assertEquals(returnList==null, true);
    }
    
    @isTest
    public static void testGetRecordDetails(){
        List<ContactPremiseRelation__c> returnList = new List<ContactPremiseRelation__c>();
        ContactPremiseRelation__c contactPremiseRelation = [Select Id from ContactPremiseRelation__c];
        Test.startTest();
        returnList = ARTL_UpdateBcpDcpLwcController.getRecordDetails(contactPremiseRelation.Id);
        Test.stopTest();
        System.assertEquals(returnList.size()>0, true);
    }
    
    @isTest
    public static void testUpdateRecords(){
        Contact contRec = [Select Id from Contact];
        ContactPremiseRelation__c contactPremiseRelation = [Select Id from ContactPremiseRelation__c];
        vlocity_cmt__Premises__c premise = [Select Id from vlocity_cmt__Premises__c];
        Account businessAcc = [Select Id from Account where Name = 'Test Business Account'];
        Account nbaAccount = [Select Id from Account where Name = 'Test NBA'];
        Map<String, String> inputMap = new Map<String, String>();
        
        inputMap.put('Id', contRec.Id);
        inputMap.put('Role__c', 'BCP');
        inputMap.put('ContactPremiseId',contactPremiseRelation.Id);
        inputMap.put('ARTL_GST_Applicable__c', 'Yes');
        inputMap.put('Salutation', 'Mr');
        inputMap.put('FirstName', 'Test');
        inputMap.put('MiddleName', 'Test');
        inputMap.put('LastName', 'Test');
        inputMap.put('Email', 'test');
        inputMap.put('Phone', '9876543210');
        inputMap.put('vlocity_cmt__Status__c', 'Active');
        inputMap.put('ARTL_Alternate_Email__c', 'test');
        inputMap.put('Fax', '3423423423');
        inputMap.put('ARTL_Standard_Reason__c', 'Non-SEZ');
        inputMap.put('ARTL_Designation__c', 'Test');
        inputMap.put('Premises__c', premise.Id);
        inputMap.put('ARTL_NBA_Account__c', nbaAccount.Id);
        inputMap.put('BusinessAccountId', businessAcc.Id);
        
        Map<String, String> inputMapNew = new Map<String, String>();
        inputMapNew.put('Id', contRec.Id);
        inputMapNew.put('Role__c', 'BCPandDCP');
        inputMapNew.put('ContactPremiseId',contactPremiseRelation.Id);
        inputMapNew.put('ARTL_GST_Applicable__c', 'Yes');
        inputMapNew.put('Salutation', 'Mr');
        inputMapNew.put('FirstName', 'Test');
        inputMapNew.put('MiddleName', 'Test');
        inputMapNew.put('LastName', 'Test');
        inputMapNew.put('Email', 'test@test.com');
        inputMapNew.put('Phone', '9876543210');
        inputMapNew.put('vlocity_cmt__Status__c', 'Active');
        inputMapNew.put('ARTL_Alternate_Email__c', 'test@test.com');
        inputMapNew.put('Fax', '3423423423');
        inputMapNew.put('ARTL_Standard_Reason__c', 'Exempt');
        inputMapNew.put('ARTL_Designation__c', 'Test');
        inputMapNew.put('Premises__c', premise.Id);
        inputMapNew.put('ARTL_NBA_Account__c', nbaAccount.Id);
        inputMapNew.put('BusinessAccountId', businessAcc.Id);
        Test.startTest();
        ARTL_UpdateBcpDcpLwcController.updateRecords(inputMap, inputMapNew);
        Test.stopTest();
    }
    
    @isTest
    public static void testUpdateRecords2(){
        Contact contRec = [Select Id from Contact];
        ContactPremiseRelation__c contactPremiseRelation = [Select Id from ContactPremiseRelation__c];
        vlocity_cmt__Premises__c premise = [Select Id from vlocity_cmt__Premises__c];
        Account businessAcc = [Select Id from Account where Name = 'Test Business Account'];
        Account nbaAccount = [Select Id from Account where Name = 'Test NBA'];
        Map<String, String> inputMap = new Map<String, String>();
        
        inputMap.put('Id', contRec.Id);
        inputMap.put('Role__c', 'BCP');
        inputMap.put('ContactPremiseId',contactPremiseRelation.Id);
        inputMap.put('ARTL_GST_Applicable__c', 'Yes');
        inputMap.put('Salutation', 'Mr');
        inputMap.put('FirstName', 'Test');
        inputMap.put('MiddleName', 'Test');
        inputMap.put('LastName', 'Test');
        inputMap.put('Email', 'test');
        inputMap.put('Phone', '9876543210');
        inputMap.put('vlocity_cmt__Status__c', 'Active');
        inputMap.put('ARTL_Alternate_Email__c', 'test');
        inputMap.put('Fax', '3423423423');
        inputMap.put('ARTL_Standard_Reason__c', 'Exempt');
        inputMap.put('ARTL_Designation__c', 'Test');
        inputMap.put('Premises__c', premise.Id);
        inputMap.put('ARTL_NBA_Account__c', nbaAccount.Id);
        inputMap.put('BusinessAccountId', businessAcc.Id);
        inputMap.put('StreetAddress', 'Panchkula');
        inputMap.put('City', 'Panchkula');
        inputMap.put('State', 'Haryana');
        inputMap.put('PostalCode', '134109');
        inputMap.put('Country', 'India');
        
        Map<String, String> inputMapNew = new Map<String, String>();
        inputMapNew.put('Id', contRec.Id);
        inputMapNew.put('Role__c', 'DCP');
        inputMapNew.put('ContactPremiseId',contactPremiseRelation.Id);
        inputMapNew.put('ARTL_GST_Applicable__c', 'Yes');
        inputMapNew.put('Salutation', 'Mr');
        inputMapNew.put('FirstName', 'Test');
        inputMapNew.put('MiddleName', 'Test');
        inputMapNew.put('LastName', 'Test');
        inputMapNew.put('Email', 'test@test.com');
        inputMapNew.put('Phone', '9876543210');
        inputMapNew.put('vlocity_cmt__Status__c', 'Active');
        inputMapNew.put('ARTL_Alternate_Email__c', 'test@test.com');
        inputMapNew.put('Fax', '3423423423');
        inputMapNew.put('ARTL_Standard_Reason__c', 'Exempt');
        inputMapNew.put('ARTL_Designation__c', 'Test');
        inputMapNew.put('Premises__c', premise.Id);
        inputMapNew.put('ARTL_NBA_Account__c', nbaAccount.Id);
        inputMapNew.put('BusinessAccountId', businessAcc.Id);
        inputMapNew.put('StreetAddress', 'Gurgaon');
        inputMapNew.put('City', 'Gurgaon');
        inputMapNew.put('State', 'Haryana');
        inputMapNew.put('PostalCode', '121001');
        inputMapNew.put('Country', 'India');
        Test.startTest();
        ARTL_UpdateBcpDcpLwcController.updateRecords(inputMap, inputMapNew);
        Test.stopTest();
    }
    
    @isTest
    public static void testPincodeData(){
        Test.startTest();
        ARTL_UpdateBcpDcpLwcController.getPincodeDetails('Panchkula');
        Test.stopTest();
    }
}