force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Step_1_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_1_Status__c</fullName>
    <label>Account Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Step_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_2_Status__c</fullName>
    <label>FX Callout Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Step_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_3_Status__c</fullName>
    <label>Solace Callout Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Step_4_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_4_Status__c</fullName>
    <label>Solace Inbound Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerClass__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerClass__c</fullName>
    <description>Grouping of accounts by attributes and used to drive accounting processes, business logic, and validation rules (i.e. residential, SMB, C&amp;I, etc.)</description>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C&amp;I</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>EGB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_AccountTriggerTest.cls
@isTest
public class ARTL_AccountTriggerTest {
  @isTest
    static void testAfterInsertTrigger() {
         Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
		
        // Create test data
        Account testAccount = new Account(Name = 'Test Account', recordTypeId=BARecordTypeId);
		testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        // Perform the insert operation
        Test.startTest();
        insert testAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test Account'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    
    @isTest
    static void testAfterInsertTrigger1() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount.vlocity_cmt__Status__c = 'Unapproved';
        testAccount.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User user = new User(Alias = 'test', Email='samtest@airtel.com', 
                             EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='samtest@airtel.com');
        insert user;
        AccountTeamMember atm = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm;
        // Perform the insert operation
        Test.startTest();
        ARTL_AccountTriggerHandler.GetAccountTeamJSON(testAccount.Id);
        testAccount.vlocity_cmt__Status__c = 'Unapproved';
        update testAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test Account'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    
    @isTest
    static void testAfterInsertTrigger2() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        // Perform the insert operation
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'Billing', recordTypeId=BARecordTypeId);
		baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_1_Status__c = 'Error';
        baTestAccount.Step_1_Status__c = 'Error';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    
    @isTest
    static void testAfterInsertTrigger3() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        // Perform the insert operation
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'Billing', recordTypeId=BARecordTypeId);
		baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_2_Status__c = 'Error';
        baTestAccount.Step_2_Status__c = 'Error';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger4() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'Billing', recordTypeId=BARecordTypeId);
		baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_3_Status__c = 'Error';
        baTestAccount.Step_3_Status__c = 'Error';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger5() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'Billing', recordTypeId=BARecordTypeId);
		baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_4_Status__c = 'Error';
        baTestAccount.Step_4_Status__c = 'Error';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger6() {
        Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.Step_1_Status__c = 'Success';
        testAccount.Step_2_Status__c = 'Success';
        testAccount.Step_3_Status__c = 'Success';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'Billing', recordTypeId=BARecordTypeId);
		baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.Step_1_Status__c = 'Success';
        baTestAccount.Step_2_Status__c = 'Success';
        baTestAccount.Step_3_Status__c = 'Success';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_4_Status__c = 'Success';
        baTestAccount.Step_4_Status__c = 'Success';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger7() {
        Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test', recordTypeId=BusinessRecordTypeId);
		testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.Step_1_Status__c = 'Success';
        testAccount.Step_2_Status__c = 'Success';
        testAccount.Step_3_Status__c = 'Success';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        
        Id BARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        // Create test data
        Account baTestAccount = new Account(Name = 'FRESH', recordTypeId=BARecordTypeId);
		    baTestAccount.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount.Step_1_Status__c = 'Success';
        baTestAccount.Step_2_Status__c = 'Success';
        baTestAccount.Step_3_Status__c = 'Success';
        baTestAccount.BillingCity = 'Delhi';
        baTestAccount.BillingCountry = 'India';
        baTestAccount.BillingState = 'Delhi';
        baTestAccount.BillingStreet = 'Test Street';
        baTestAccount.BillingPostalCode = '110011';
        baTestAccount.ARTL_Customer_Segment__c = 'AB';
        baTestAccount.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount.ARTL_Service_Segment__c = 'BD';
        baTestAccount.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount.ARTL_Category__c = 'A';
        insert baTestAccount;
        Account baTestAccount2 = new Account(Name = 'FRESH ONES', recordTypeId=BARecordTypeId);
		    baTestAccount2.ARTL_PAN__c = 'BBBBB1234A';
        baTestAccount2.Step_1_Status__c = 'Success';
        baTestAccount2.Step_2_Status__c = 'Success';
        baTestAccount2.Step_3_Status__c = 'Success';
        baTestAccount2.BillingCity = 'Delhi';
        baTestAccount2.BillingCountry = 'India';
        baTestAccount2.BillingState = 'Delhi';
        baTestAccount2.BillingStreet = 'Test Street';
        baTestAccount2.BillingPostalCode = '110011';
        baTestAccount2.ARTL_Customer_Segment__c = 'AB';
        baTestAccount2.ARTL_Business_Circle_Region__c = 'AP';
        baTestAccount2.ARTL_Service_Segment__c = 'BD';
        baTestAccount2.ARTL_Vertical_Segment__c ='BFI';
        baTestAccount2.ARTL_Category__c = 'A';
        insert baTestAccount2;
        // Perform the insert operation
        Test.startTest();
        testAccount.Step_4_Status__c = 'Success';
        baTestAccount.Step_4_Status__c = 'Success';
        update testAccount;
        update baTestAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger8() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount.vlocity_cmt__Status__c = 'Unapproved';
        testAccount.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        // Perform the insert operation
        Test.startTest();
        ARTL_AccountTriggerHandler.GetAccountTeamJSON(testAccount.Id);
        testAccount.vlocity_cmt__Status__c = 'Unapproved';
        update testAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test Account'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger9() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount.vlocity_cmt__Status__c = 'Unapproved';
        testAccount.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User user = new User(Alias = 'test', Email='samtest@airtel.com', 
                             EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='samtest@airtel.com');
        insert user;
        User user2 = new User(Alias = 'test2', Email='samtest2@airtel.com', 
                             EmailEncodingKey='UTF-8', LastName='Test2', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='samtest2@airtel.com');
        insert user2;
        AccountTeamMember atm = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm;
        AccountTeamMember atm2 = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user2.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm2;
        // Perform the insert operation
        Test.startTest();
        ARTL_AccountTriggerHandler.GetAccountTeamJSON(testAccount.Id);
        testAccount.vlocity_cmt__Status__c = 'Unapproved';
        update testAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test Account'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
    @isTest
    static void testAfterInsertTrigger10() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data
        Account testAccount = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount.vlocity_cmt__Status__c = 'Unapproved';
        testAccount.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount.ARTL_PAN__c = 'AAAAA1234A';
        testAccount.BillingCity = 'Delhi';
        testAccount.BillingCountry = 'India';
        testAccount.BillingState = 'Delhi';
        testAccount.BillingStreet = 'Test Street';
        testAccount.BillingPostalCode = '110011';
        testAccount.ARTL_Customer_Segment__c = 'AB';
        testAccount.ARTL_Business_Circle_Region__c = 'AP';
        testAccount.ARTL_Service_Segment__c = 'BD';
        testAccount.ARTL_Vertical_Segment__c ='BFI';
        testAccount.ARTL_Category__c = 'A';
        insert testAccount;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User user = new User(Alias = 'test', Email='samtest@airtel.com', 
                             EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='samtest@airtel.com');
        insert user;
        AccountTeamMember atm = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm;
        AccountTeamMember atm2 = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm2;
        AccountTeamMember atm3 = new AccountTeamMember(AccountId = testAccount.Id, 
        UserId = user.Id, 
        TeamMemberRole = 'Secondary KAM');
        insert atm3;
        // Perform the insert operation
        Test.startTest();
        ARTL_AccountTriggerHandler.GetAccountTeamJSON(testAccount.Id);
        testAccount.vlocity_cmt__Status__c = 'Unapproved';
        update testAccount;
        Test.stopTest();

        // Verify the results
        List<Account> insertedAccounts = [SELECT Id, Name FROM Account WHERE Name = 'Test Account'];

        // Assert that the trigger logic has been applied after insert
        System.assertEquals(1, insertedAccounts.size(), 'Only one account should be inserted');
        Account insertedAccount = insertedAccounts[0];
        System.assertNotEquals(null, insertedAccount.Id, 'Account Id should not be null');
    }
}