force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/LOC.recordType-meta.xml
<RecordType>
    <fullName>LOC</fullName>
    <active>true</active>
    <label>LOC</label>
</RecordType>

force-app/main/default/classes/ARTL_CreateInflightCancelOrderTest.cls
@isTest
public class ARTL_CreateInflightCancelOrderTest {
	static testMethod void testTaskHandlerHelper(){
        
        Id recordTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account acc = new Account(Name = 'Test Account',ARTL_Business_Circle_Region__c='NCR',BillingCity = 'Panchkula',
                                  BillingCountry = 'Haryana',BillingPostalCode = '134109',BillingState = 'India',BillingStreet = 'Panchkula',
                                  ARTL_Category__c = 'A',RecordTypeId = recordTypeId1, ARTL_Customer_Segment__c ='AB', ARTL_Vertical_Segment__c ='BFI',
                                  ARTL_Service_Segment__c ='Bharti');
        insert acc;
        
        List<Product2> products = new List<Product2>();        
        Id pbId = Test.getStandardPricebookId();
        products = new Product2[2];
        products[0]=new Product2(name='NIPS_HARDWARE', ProductCode='dac49a09-9b41-4999-b7c4-cf6319ad5b44',vlocity_cmt__JSONAttribute__c = '');
        products[1]=new Product2(name='NIPS_SERVICE ', ProductCode='c09a2e70-64af-4ad6-8427-06c8489234d7', vlocity_cmt__JSONAttribute__c = '');
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        for (Integer i=0; i<products.size(); i++)        {
            pbes[i] = new PricebookEntry(product2Id = products[i].id, isActive=true,unitPrice = 10, pricebook2id = pbId, useStandardPrice = false);
        }
        insert pbes;
        
        Order order = new Order(AccountId = acc.id, effectiveDate = Date.today(), pricebook2id = pbId, status = 'Draft');
        insert order;
        
        Id recordTypeId2 = Schema.SObjectType.Task.getRecordTypeInfosByName().get('LOC').getRecordTypeId();
        List<Task> tlist = new List<Task>();
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.recordTypeId = recordTypeId2;
        t.WhatId = order.Id;
        t.ARTL_Rejection_Category__c = 'Valid';
        t.ARTL_locRejectionReason__c = 'Customer End Hardware Pending-NSG';
        t.Subject='LOC Customer';
        t.Status='Not Started';
        t.Priority='Normal';
        tlist.add(t);
        insert tlist;
        
        /*map<Id,task> taskMapNew = new map<Id, task>();
        taskMapNew.put(t.Id, t);
        
        map<Id,task> taskMapOld = new  map<Id,task>([SELECT Id, ARTL_Rejection_Category__c from task]);
        
        List<Task> tempTasks = [SELECT Id, ARTL_Rejection_Category__c from task];
        tempTasks[0].ARTL_Rejection_Category__c = 'InValid';
        update tempTasks;
        
        taskMapOld.put(tempTasks[0].Id, tempTasks[0]);*/
        List<ARTL_CreateInflightCancelOrder.IntegrationProcedureInput> lstflowinput = new List<ARTL_CreateInflightCancelOrder.IntegrationProcedureInput>();
        ARTL_CreateInflightCancelOrder.IntegrationProcedureInput flowinput = new ARTL_CreateInflightCancelOrder.IntegrationProcedureInput();
        flowinput.Input = order.Id;
        flowinput.procedureAPIName='b2bExpress_CancelSubOrder';
        lstflowinput.add(flowinput);
        Test.startTest();
        ARTL_CreateInflightCancelOrder.runIntegrationServiceInvocable(lstflowinput);
        Test.stopTest();
    }
}