force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Level__c.field-meta.xml
<CustomField>
    <fullName>Billing_Level__c</fullName>
    <label>Billing Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LSI Level</fullName>
            </value>
            <value>
                <fullName>Account Level</fullName>
            </value>
            <value>
                <fullName>PO Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__BillFrequency__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillFrequency__c</fullName>
    <description>The frequency at which bills are generated such as Monthly, Quarterly or Weekly. Part of the billing profile of a customer or billing account.</description>
    <label>Bill Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Bi Monthly</fullName>
            </value>
            <value>
                <fullName>Bi Yearly</fullName>
            </value>
            <value>
                <fullName>Ten yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility__c/ARTL_Feasibility__c.object-meta.xml
<CustomObject>
    <label>Feasibility</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Feasibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feasibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility__c/fields/ARTL_Feasibility_ID__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility_ID__c</fullName>
    <externalId>true</externalId>
    <label>Feasibility ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Task_Integration_Logs__c/ARTL_Task_Integration_Logs__c.object-meta.xml
<CustomObject>
    <label>Task Integration Logs</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Task Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Task_Integration_Logs__c/fields/ARTL_Input_Attributes__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Input_Attributes__c</fullName>
    <label>Input Attributes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Task_Integration_Logs__c/fields/ARTL_OrderId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Task_Integrations_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/ARTL_CAFNumber__c.field-meta.xml
<CustomField>
    <fullName>ARTL_CAFNumber__c</fullName>
    <label>CAF Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ARTL_OrderType__c.field-meta.xml
<CustomField>
    <fullName>ARTL_OrderType__c</fullName>
    <formula>IF(
ISPICKVAL(Type  , &quot;New&quot;),
&quot;New&quot;,
&quot;MACD&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARTL_Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ARTL_Root_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Root_ProductCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Root Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ARTL_SOMOrderId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_SOMOrderId__c</fullName>
    <label>SOMOrderId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PM_Email__c.field-meta.xml
<CustomField>
    <fullName>PM_Email__c</fullName>
    <formula>Quote.PM__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PM Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PM_Name__c.field-meta.xml
<CustomField>
    <fullName>PM_Name__c</fullName>
    <formula>Quote.PM__r.FirstName + &apos; &apos; + Quote.PM__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PM Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PM_Phone__c.field-meta.xml
<CustomField>
    <fullName>PM_Phone__c</fullName>
    <formula>Quote.PM__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PM Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARRTL_BandWidth__c.field-meta.xml
<CustomField>
    <fullName>ARRTL_BandWidth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BandWidth</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ARTL_ItemCode__c</fullName>
    <label>ARTL_ItemCode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_Latest_PO__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Latest_PO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest PO</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_LSI__c.field-meta.xml
<CustomField>
    <fullName>ARTL_LSI__c</fullName>
    <label>LSI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CND__c.field-meta.xml
<CustomField>
    <fullName>CND__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CND</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/LOC.recordType-meta.xml
<RecordType>
    <fullName>LOC</fullName>
    <active>true</active>
    <label>LOC</label>
</RecordType>

force-app/main/default/classes/ARTL_AfterLOCCreationCallout.cls
global with sharing class ARTL_AfterLOCCreationCallout {

    @InvocableMethod(label = 'Callout for LOC Task')
    global static void jsonPrepareForLOC(List<taskLOC> input){
        Id taskId = input[0].taskLOCId;
        Id orderId = input[0].orderRecId;
        if(orderId != null && taskId != null){
            jsonPrepareForLOCFuture(orderId,taskId);
        }
    }
    
    @future(callout=true)
    global static void jsonPrepareForLOCFuture(Id orderId, Id taskId){
        Map<String, Object> sitesMap = new Map<String, Object> ();
        Map<String, String> attrDataMap = new Map<String, String>();
        Task tsk = [Select Id,CreatedDate,Number_of_days_for_Deemed_LOC__c, ARTL_locAcceptanceCriteria__c from Task where Id =: taskId];
        List<ARTL_Task_Integration_Logs__c> tskIntLog = [Select id,ARTL_Input_Attributes__c from ARTL_Task_Integration_Logs__c where ARTL_OrderId__c =: orderId];
        Order ordRec = [Select Id,ARTL_SOMOrderId__c, vlocity_cmt__ParentOrderId__c, ARTL_OrderType__c, ARTL_Root_ProductCode__c, 
                        Opportunity.Owner.Name,Opportunity.Owner.Email, Opportunity.Owner.Phone,AccountId,
                        vlocity_cmt__DefaultBillingAccountId__r.vlocity_cmt__BillFrequency__c, vlocity_cmt__DefaultBillingAccountId__r.Billing_Level__c,
                        PM_Name__c, PM_Email__c, PM_Phone__c,Account.ARTL_Customer_Segment__c,Account.ARTL_Business_Circle_Region__c,Account.ARTL_Vertical_Segment__c,
                        Account.Name,Account.AccountNumber,Contract.ARTL_CAFNumber__c, Contract.ContractNumber,Contract.ContractTerm FROM Order WHERE Id =:orderId];
        Contact[] deliveryContact = [Select id,MailingAddress, MailingState, MailingCity, MailingPostalCode, Name,Email,Phone  from Contact where ARTL_Contact_Role__c = 'Delivery Contact' and AccountId =:ordRec.AccountId];
        List<OrderItem> oliRecordList = [Select Id,ARTL_Media__c, ARRTL_BandWidth__c, ARTL_PortBandwidth__c, ARTL_Latest_PO__r.ARTL_PO_Number__c, 
                                         ARTL_Feasibility__r.ARTL_Feasibility_ID__c,ARTL_LSI__c,ARTL_Service_Type__c,ARTL_ItemCode__c, 
                                         ARTL_RouterMake__c, ARTL_RouterModel__c,RFS__c, CND__c from OrderItem where orderId =: orderId];               
        for(OrderItem oi : oliRecordList){
            sitesMap.put('media', oi.ARTL_Media__c != null ? oi.ARTL_Media__c : '');
            sitesMap.put('serviceType', oi.ARTL_Service_Type__c != null ? oi.ARTL_Service_Type__c : '');
            sitesMap.put('poNumber', oi.ARTL_Latest_PO__r.ARTL_PO_Number__c != null ? oi.ARTL_Latest_PO__r.ARTL_PO_Number__c : '');
            sitesMap.put('portBandwidth', oi.ARTL_PortBandwidth__c != null ? oi.ARTL_PortBandwidth__c : '');
            sitesMap.put('accessBandwidth', oi.ARRTL_BandWidth__c != null ? oi.ARRTL_BandWidth__c : '');
            sitesMap.put('lsiId', oi.ARTL_LSI__c != null ? String.valueof(oi.ARTL_LSI__c) : '');
            sitesMap.put('feasibilityId', oi.ARTL_Feasibility__r.ARTL_Feasibility_ID__c != null ? oi.ARTL_Feasibility__r.ARTL_Feasibility_ID__c : '');
            sitesMap.put('itemCode', oi.ARTL_ItemCode__c != null ? oi.ARTL_ItemCode__c : '');
            sitesMap.put('routerMake', oi.ARTL_RouterMake__c != null ? oi.ARTL_RouterMake__c : '');
            sitesMap.put('routerModel', oi.ARTL_RouterModel__c != null ? String.valueof(oi.ARTL_RouterModel__c) : '');
            sitesMap.put('newRfsDate', oi.RFS__c != null ? String.valueof(oi.RFS__c) : '');
            sitesMap.put('originalRfsDate', oi.RFS__c != null ? String.valueof(oi.RFS__c) : '');
            sitesMap.put('customerNeedByDate', oi.CND__c != null ? String.valueof(oi.CND__c) : '');
        }
        if (deliveryContact.size() > 0){
            sitesMap.put('locCustContactName',deliveryContact[0].Name);
            sitesMap.put('locCustContactEmail',deliveryContact[0].Email);
            sitesMap.put('locCustContactPhone',deliveryContact[0].Phone);
            sitesMap.put('dcpAddress',deliveryContact[0].MailingAddress);
            sitesMap.put('dcpCity',deliveryContact[0].MailingCity);
            sitesMap.put('dcpState',deliveryContact[0].MailingState);
            sitesMap.put('dcpPincode',deliveryContact[0].MailingPostalCode);
        }
        if(tskIntLog.size() > 0){
            if(tskIntLog[0].ARTL_Input_Attributes__c != null){
                Map<String, Object> attrObject = (Map<String, Object>)JSON.deserializeUntyped(tskIntLog[0].ARTL_Input_Attributes__c);
                for (String key : attrObject.keySet()) {
                    Object innerData = attrObject.get(key);
                    List<Object> attrList = (List<Object>)innerData;
                    for (Object data : attrList) {
                        Map<String, Object> dataItem = (Map<String, Object>)data;
                        String name = (String)dataItem.get('Name');
                        String value = (String)dataItem.get('Value');
                        attrDataMap.put(name, value);
                    }
                }
                system.debug('attrDataMap--->'+attrDataMap);
            }
        }
        Map<String, Object> ipInput = new Map<String, Object> ();
        Map<String, Object> ipOutput = new Map<String, Object> ();
        Map<String, Object> ipOptions = new Map<String, Object>();
        ipOptions.put('isDebug',false);
        ipOptions.put('useQueueable',true);
        List<Object> sitesList =  new List<Object>();
        sitesMap.put('id',taskId);
        sitesMap.put('deemedLocDays',tsk.Number_of_days_for_Deemed_LOC__c);
        sitesMap.put('acceptanceCriteria',tsk.ARTL_locAcceptanceCriteria__c);
        sitesMap.put('poleTowerHeight',attrDataMap.get('CPE Customer Tower Height'));
        sitesMap.put('poleTowerType',attrDataMap.get('CPE Customer Tower Type'));
        sitesMap.put('lanIpv4',attrDataMap.get('LAN IPv4'));
        sitesMap.put('wanIpv4CE',attrDataMap.get('WAN IPv4 CE'));
        sitesMap.put('wanIpv4PE',attrDataMap.get('WAN IPv4 PE'));
        sitesMap.put('lanIpv6',attrDataMap.get('LAN IPv6'));
        sitesMap.put('wanIpv6',attrDataMap.get('WAN IPv6'));
        sitesMap.put('circuitId',attrDataMap.get('Circuit ID'));
        sitesMap.put('lanIpv4Subnet',attrDataMap.get('LAN IPv4 Subnet'));
        sitesMap.put('lanIpv6Subnet',attrDataMap.get('LAN IPv6 Subnet'));
        sitesMap.put('wanIpv4Subnet',attrDataMap.get('WAN IPv4 Subnet'));
        sitesMap.put('wanIpv6CE',attrDataMap.get('WAN IPv6 CE'));
        sitesMap.put('wanIpv6PE',attrDataMap.get('WAN IPv6 PE'));
        sitesMap.put('wanIpv6Subnet',attrDataMap.get('WAN IPv6 Subnet'));
        sitesMap.put('loopbackIpv4',attrDataMap.get('Loopback Ipv4'));
        sitesMap.put('loopbackIpv6',attrDataMap.get('Loopback IPv6'));
        sitesMap.put('businessCircle',ordRec.Account.ARTL_Business_Circle_Region__c);
        sitesMap.put('implementationCircle',ordRec.Account.ARTL_Business_Circle_Region__c);
        sitesMap.put('connectivityType','');
        sitesMap.put('customerSegment',ordRec.Account.ARTL_Customer_Segment__c);
        sitesMap.put('vertical',ordRec.Account.ARTL_Vertical_Segment__c);
        sitesMap.put('infovistaUrl',attrDataMap.get('Infovista URL'));
        sitesMap.put('infovistaUsername',attrDataMap.get('Infovista Username'));
        sitesMap.put('infovistaPassword',attrDataMap.get('Infovista Password'));
        sitesMap.put('billingStartDate','');
        sitesMap.put('contractTerm',ordRec.Contract.ContractTerm);
        sitesMap.put('billingLevel',ordRec.vlocity_cmt__DefaultBillingAccountId__r.Billing_Level__c);
        sitesMap.put('billFrequency',ordRec.vlocity_cmt__DefaultBillingAccountId__r.vlocity_cmt__BillFrequency__c);
        sitesMap.put('kamTsmName',ordRec.Opportunity.Owner.Name);
        sitesMap.put('kamTsmPhone',ordRec.Opportunity.Owner.Phone);
        sitesMap.put('kamTsmEmail',ordRec.Opportunity.Owner.Email);
        sitesMap.put('pmName',ordRec.PM_Name__c);
        sitesMap.put('pmContact',ordRec.PM_Phone__c);
        sitesMap.put('pmEmail',ordRec.PM_Email__c);
        sitesList.add(sitesMap);
        //ipInput
        ipInput.put('SOMOrderId',ordRec.ARTL_SOMOrderId__c);
        ipInput.put('MasterOrderId',ordRec.vlocity_cmt__ParentOrderId__c);
        ipInput.put('OrderType',ordRec.ARTL_OrderType__c);
        ipInput.put('RootProductName',ordRec.ARTL_Root_ProductCode__c);
        ipInput.put('AccountNumber',ordRec.Account.AccountNumber);
        ipInput.put('AccountName',ordRec.Account.Name);
        ipInput.put('ContractNumber',ordRec.Contract.ContractNumber);
        ipInput.put('TaskCreatedDate',tsk.CreatedDate);
        ipInput.put('sites',sitesList);
        System.debug('ipInput : '+JSON.serializePretty(ipInput));
        ipOutput = (Map<String, Object>)vlocity_cmt.IntegrationProcedureService.runIntegrationService('ARTLOM_LOCTaskCallout', ipInput, ipOptions);
        System.debug('ipOutput : '+JSON.serializePretty(ipOutput));
    }
    
    global class taskLOC
    {
        @InvocableVariable(label = 'LOC Task Record') global String taskLOCId;
        @InvocableVariable(label = 'Order Record') global String orderRecId;
    }
}