force-app/main/default/objects/Account/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Alternate_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/ARTL_BCP_DCP_Contact.recordType-meta.xml
<RecordType>
    <fullName>ARTL_BCP_DCP_Contact</fullName>
    <active>true</active>
    <label>BCP/DCP Contact</label>
</RecordType>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <label>GST Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_NBA_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NBA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NBA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Standard_Reason__c</fullName>
    <label>Standard Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_GST_Applicable__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>UIN</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Non-SEZ</fullName>
            </value>
            <value>
                <fullName>Applied For</fullName>
            </value>
            <value>
                <fullName>SEZ with taxes</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- FTWZ</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- Export</fullName>
            </value>
            <value>
                <fullName>Non Taxable as transactions within same Company</fullName>
            </value>
            <value>
                <fullName>Airtel- Foreign Legal Entity</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Exempt-Trust/Entities 12AA</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- SEZ</fullName>
            </value>
            <value>
                <fullName>J&amp;K delivery - Out of GST Preview</fullName>
            </value>
            <value>
                <fullName>Exempt Supply - Trust/Entities 12AA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GST#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7) OR (3 AND 8 AND 2) OR (3 AND 9 AND 7) OR (10 AND 7)</booleanFilter>
        <errorMessage>Invalid Mapping of Standard Reason and GST Type</errorMessage>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_GST_Applicable__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ with taxes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Zero Rated Supply- FTWZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non Taxable as transactions within same Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GST__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Business Account that the GST is associated with</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GSTs</relationshipLabel>
    <relationshipName>GSTs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ARTL_gstDetailsInBcpDcp.cls
/**
 * @description       : Used in IP - ARTL_CreateBCP to create BCP/DCP for a NBA account
 * @test class        : ARTL_gstDetailsInBcpDcpTest
 * @author            : Rishab Kalra
 * @last modified on  : 12-21-2023
**/
global class ARTL_gstDetailsInBcpDcp implements vlocity_cmt.VlocityOpenInterface {
    public class CustomException extends Exception {}
    private static final String CONTACT_ROLE_BILLING = 'Billing Contact';
    private static final String CONTACT_ROLE_DELIVERY = 'Delivery Contact';
    private static final String ROLE_BCP = 'BCP';
    private static final String ROLE_DCP = 'DCP';
    private static final String ROLE_BCP_DCP = 'BCPandDCP';
    
    global boolean invokeMethod(String methodName, Map<String, Object> input, Map<String, Object> output, Map<String, Object> options) {
        try {
            System.debug('DEBUGG input '+ input);
            if(methodName.equalsIgnoreCase('createBcp')){
                createBcp(methodName, input, output, options);
            }
        } catch (Exception ex) {
            // Handle exceptions appropriately, log or return an error
            return false;
        }
        return true;
    }
    
    global static void createBcp(String methodName, Map<String, Object> input, Map<String, Object> output, Map<String, Object> options){
        Savepoint sp = Database.setSavepoint();
        try{
            
            System.debug('DEBUGG input '+ input);

            String nbaAccountId = (String)input.get('ContextId');
            if(String.isBlank(nbaAccountId)){
                throw new CustomException('Account Id not found.');
            }
            //getting business account Id from NBA Id
            String parentAccountId = [SELECT Id, ParentId FROM Account WHERE Id = :nbaAccountId].ParentId;
            Map<String, Object> contactDetails = new Map<String, Object>();
            contactDetails = (Map<String, Object>)input.get('Step_ContactDetails');
            Map<String, Object> addressDetails = new Map<String, Object>();
            String role;
            if(!contactDetails.isEmpty()){
                addressDetails = (Map<String, Object>)contactDetails.get('TApincode-Block');
                role = (String)contactDetails.get('Select_Role');
            }
            //String contactRole = role.equalsIgnoreCase('BCP') ? 'Billing Contact': role.equalsIgnoreCase('DCP') ? 'Delivery Contact':'Delivery/Billing Contact';
            List<Contact> listOfContact = new List<Contact>();
            Map<Id, Contact> mapOfContact = new Map<Id, Contact>();
            List<vlocity_cmt__Premises__c> listOfPremises = new List<vlocity_cmt__Premises__c>();
            List<ContactPremiseRelation__c> listOfContactPremiseRelation = new List<ContactPremiseRelation__c>();
            List<AccountContactRelation> listOfAccountContactRelation = new List<AccountContactRelation>();
            
            if(String.isNotBlank(role) && role.equalsIgnoreCase(ROLE_BCP)){
                listOfContact.add(createContactRecord(contactDetails, CONTACT_ROLE_BILLING, nbaAccountId));
            }
            else if(String.isNotBlank(role) && role.equalsIgnoreCase(ROLE_DCP)){
                listOfContact.add(createContactRecord(contactDetails, CONTACT_ROLE_DELIVERY, nbaAccountId));
            }
            else if(String.isNotBlank(role) && role.equalsIgnoreCase(ROLE_BCP_DCP)){
                listOfContact.add(createContactRecord(contactDetails, CONTACT_ROLE_BILLING, nbaAccountId));
                listOfContact.add(createContactRecord(contactDetails, CONTACT_ROLE_DELIVERY, nbaAccountId));
            }
            
            
            
            //listOfContact.add(createContactRecord(contactDetails,contactRole, nbaAccountId));
            String insertedContactId;
            String bcpContactId;
            String dcpContactId;
            System.debug('List of contacts '+listOfContact);
            if(!listOfContact.isEmpty()){
                for(Database.SaveResult sr: Database.insert(listOfContact)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted contact - ' + sr.getId());
                        insertedContactId = sr.getId();
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            output.put('errorMessage',  err.getMessage());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            for(Contact cont: listOfContact){
                if(String.isNotBlank(cont.Id)){
                    mapOfContact.put(cont.Id, cont);
                    if(cont.ARTL_Contact_Role__c.equalsIgnoreCase(CONTACT_ROLE_BILLING)){
                        bcpContactId = cont.Id;
                    }
                    if(cont.ARTL_Contact_Role__c.equalsIgnoreCase(CONTACT_ROLE_DELIVERY)){
                        dcpContactId = cont.Id;
                    }
                    
                }
            }
            System.debug('DEBUGG map '+mapOfContact);
            String insertedPremiseId;
            listOfPremises.add(createPremiseRecord(addressDetails));
            if(!listOfPremises.isEmpty()){
                // insert listOfPremises;
                for(Database.SaveResult sr: Database.insert(listOfPremises)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted Premise - ' + sr.getId());
                        insertedPremiseId = sr.getId();
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            output.put('errorMessage',  err.getMessage());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            List<AccountContactRelation> updateListOfAccountContactRelation = new List<AccountContactRelation>();
            
            For(AccountContactRelation acr: [SELECT Id, ContactId, Contact.ARTL_Contact_Role__c, AccountId, Roles 
                                             FROM AccountContactRelation WHERE AccountId = :nbaAccountId
                                             AND (ContactId = :bcpContactId OR ContactId = :dcpContactId)]){
                                                 if(String.isBlank(acr.Roles)){
                                                     //acr.Roles = role.equalsIgnoreCase('BCP') ? 'BCP': role.equalsIgnoreCase('DCP') ? 'DCP':'BCP;DCP';
                                                     if(acr.Contact?.ARTL_Contact_Role__c?.equalsIgnoreCase(CONTACT_ROLE_BILLING)){
                                                         acr.Roles = ROLE_BCP;
                                                     }
                                                     if(acr.Contact?.ARTL_Contact_Role__c?.equalsIgnoreCase(CONTACT_ROLE_DELIVERY)){
                                                         acr.Roles = ROLE_DCP;
                                                     }
                                                     updateListOfAccountContactRelation.add(acr);
                                                 }
                                             }
            if(!String.isBlank(role)){
                if(role.equalsIgnoreCase(ROLE_BCP)){
                    //listOfAccountContactRelation.add(createAccountContactRelationRecord('BCP', insertedContactId, parentAccountId));
                    //listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, 'BCP', insertedPremiseId, insertedContactId, nbaAccountId));
                    listOfAccountContactRelation.add(createAccountContactRelationRecord(ROLE_BCP, bcpContactId, parentAccountId));
                    listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, ROLE_BCP, insertedPremiseId, bcpContactId, nbaAccountId));

                }
                else if(role.equalsIgnoreCase(ROLE_DCP)){
                    //listOfAccountContactRelation.add(createAccountContactRelationRecord('DCP', insertedContactId, parentAccountId));
                    //listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, 'DCP', insertedPremiseId, insertedContactId, nbaAccountId));
                    
                    listOfAccountContactRelation.add(createAccountContactRelationRecord(ROLE_DCP, dcpContactId, parentAccountId));
                    listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, ROLE_DCP, insertedPremiseId, dcpContactId, nbaAccountId));

                }
                else if(role.equalsIgnoreCase(ROLE_BCP_DCP)){
                    //listOfAccountContactRelation.add(createAccountContactRelationRecord('BCP;DCP', insertedContactId, parentAccountId));
                    //listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, 'BCP', insertedPremiseId, insertedContactId, nbaAccountId));
                    //listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, 'DCP', insertedPremiseId, insertedContactId, nbaAccountId));
                    
                    listOfAccountContactRelation.add(createAccountContactRelationRecord(ROLE_DCP, dcpContactId, parentAccountId));
                    listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, ROLE_DCP, insertedPremiseId, dcpContactId, nbaAccountId));
                    
                    listOfAccountContactRelation.add(createAccountContactRelationRecord(ROLE_BCP, bcpContactId, parentAccountId));
                    listOfContactPremiseRelation.add(createContactPremiseRelationRecord(contactDetails, ROLE_BCP, insertedPremiseId, bcpContactId, nbaAccountId));

                }
            }
            if(!updateListOfAccountContactRelation.isEmpty()){
                for(Database.UpsertResult sr: Database.upsert(updateListOfAccountContactRelation)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted listOfAccountContactRelation - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            output.put('errorMessage',  err.getMessage());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
                
            }
            if(!listOfAccountContactRelation.isEmpty()){
                for(Database.UpsertResult sr: Database.upsert(listOfAccountContactRelation)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted listOfAccountContactRelation - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            output.put('errorMessage',  err.getMessage());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            
            if(!listOfContactPremiseRelation.isEmpty()){
                for(Database.SaveResult sr: Database.insert(listOfContactPremiseRelation)){
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted listOfContactPremiseRelation - ' + sr.getId());
                    }
                    else {
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            System.debug('DEBUGG The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('DEBUGG ' + err.getFields());
                            output.put('errorMessage',  err.getMessage());
                            Database.rollback(sp);
                            throw new CustomException(err.getMessage()+' '+err.getFields());
                        }
                    }
                }
            }
            if(Test.isRunningTest()){
                throw new CustomException('Test Class');
            }
        }
        catch(Exception ex){
            System.debug('DEBUGG exception '+ ex.getLineNumber()+' '+ ex.getMessage());
            output.put('errorMessage',  ex.getMessage());
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_gstDetailsInBcpDcp', '', new Map<String, Object>{'Exception' => ex.getMessage(), 'LineNumber' => ex.getLineNumber()}, ex);
            Database.rollback(sp);
            throw new CustomException(ex.getLineNumber()+' '+ ex.getMessage());
        }
    }
    
    
    private static AccountContactRelation createAccountContactRelationRecord(String role, String contactId, String accountId){
        AccountContactRelation acrRecord = new AccountContactRelation(ContactId = contactId, 
                                                                      AccountId = accountId, 
                                                                      Roles 	= role);
        return acrRecord;
    }
    
    private static ContactPremiseRelation__c createContactPremiseRelationRecord(Map<String, Object> contactDetails, String role, String insertedPremiseId, String contactId, String nbaAccountId){
        ContactPremiseRelation__c contactPremiseRelationRecord = new ContactPremiseRelation__c( 
            ARTL_Standard_Reason__c = (String)contactDetails.get('standardReason'),
            ARTL_GST_Applicable__c 	= (String)contactDetails.get('gstApplicable'),
            GST__c 					= (String)contactDetails.get('gstSelectedValue'),
            Role__c 				= role, 
            Premises__c 			= insertedPremiseId, 
            Contact__c 				= contactId, 
            ARTL_NBA_Account__c 	= nbaAccountId
        );
        return contactPremiseRelationRecord;
        
    }
    
    private static Contact createContactRecord(Map<String, Object> input,String contactRole, String accountId){
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ARTL_BCP_DCP_Contact').getRecordTypeId();
        Contact contactRecord = new Contact(Salutation 					= (String)input.get('Select_Salutation'),
                                            FirstName 					= (String)input.get('TXT_FirstName'),
                                            MiddleName 					= (String)input.get('TXT_MiddleName'),
                                            LastName 					= (String)input.get('TXT_LastName'), 
                                            Email 						= (String)input.get('TXT_Email'),
                                            ARTL_Alternate_Email__c 	= (String)input.get('alternateEmail'),
                                            Phone 				        = (String)input.get('Number_Mobile'), 
                                            Fax 						= (String)input.get('fax'), 
                                            ARTL_Designation__c  		= (String)input.get('designation'),
                                            ARTL_Contact_Role__c        = contactRole,
                                            RecordTypeId 				= recordTypeId,
                                            vlocity_cmt__Status__c  	= 'Active',
                                            AccountId 					= accountId);
        return contactRecord;
    }
    
    private static vlocity_cmt__Premises__c createPremiseRecord(Map<String, Object> addressDetails){
        vlocity_cmt__Premises__c premiseRecord = new vlocity_cmt__Premises__c(
            vlocity_cmt__City__c 			= (String)addressDetails.get('city'), 
            vlocity_cmt__Country__c 		= (String)addressDetails.get('country'),
            vlocity_cmt__State__c 			= (String)addressDetails.get('state'),
            vlocity_cmt__StreetAddress__c 	= (String)addressDetails.get('street'),
            vlocity_cmt__PostalCode__c		= (String)addressDetails.get('pincode'), 
            ARTL_Pincode__c                 = (String)addressDetails.get('pincodeId')
        );
        return premiseRecord;
    }
    
    /**
    * @description : Used in ARTL_gstDetailsInBcpDcpLwc to fetch GST values on the basis of parameters.
    * @author Rishab Kalra | 12-21-2023 
    * @param state 
    * @param nbaAccountId 
    * @param gstType 
    * @return List<Map<String, String>> 
    **/
    @AuraEnabled 
    public static List<Map<String, String>> getGstDetails(String state, String nbaAccountId, String gstType){
        try{
            List<Map<String, String>> gstPicklist = new List<Map<String, String>>();
            if(String.isBlank(nbaAccountId)){
                throw new CustomException('NBA Account Id not found.');
            }
            if(!String.isBlank(nbaAccountId)){
                Map<String, Object> input = new Map<String, Object>();
                List<Object> arguments = new List<Object>{state};
                    input.put('arguments', arguments);
                // Test output data
                Map<String, Object> output = new Map<String, Object>();
                DataRaptorHelper helper = new DataRaptorHelper();
                Boolean result = helper.invokeMethod('gstGetStateCode', input, output, new Map<String, Object>());
                String stateCode = (String) output.get('result');
                String parentAccountId = [SELECT Id, ParentId FROM Account WHERE Id = :nbaAccountId].ParentId;
                if(!String.isBlank(parentAccountId)){
                    for(GST__c gst: [SELECT Id, Name FROM GST__c 
                                     WHERE ARTL_GST_Type__c = :gstType 
                                     AND Account__c = :parentAccountId
                                     AND Status__c = 'Active'
                                     AND ARTL_Address__StateCode__s = :stateCode]){
                                         Map<String, String> valueMap = new Map<String, String>();
                                         valueMap.put('label', gst.Name);
                                         valueMap.put('value', gst.Id);
                                         gstPicklist.add(valueMap);
                                     }
                }
            }
            return gstPicklist;
        }
        catch(Exception ex){
            ARTL_Logger.error(ARTL_Constants.CONTROLLER, 'ARTL_gstDetailsInBcpDcp', '', new Map<String, Object>{'Exception' => ex.getMessage(), 'LineNumber' => ex.getLineNumber()}, ex);
            System.debug('Exception ex '+ ex + ex.getLineNumber());
            throw new CustomException(ex.getLineNumber()+' '+ ex.getMessage());
        }
    }
    
}