force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bottom_Up_Construct__c/Bottom_Up_Construct__c.object-meta.xml
<CustomObject>
    <label>Bottom Up Construct</label>
    <nameField>
        <displayFormat>BUC-{0000000}</displayFormat>
        <label>Bottom Up  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bottom Up Constructs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bottom_Up_Construct__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Plan</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select only BUC&apos;s Account related Account Plans</errorMessage>
        <filterItems>
            <field>$Source.Account_Name__c</field>
            <operation>equals</operation>
            <valueField>Account_Plan__c.Account_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Fiscal_Year__c</field>
            <operation>equals</operation>
            <valueField>Account_Plan__c.Fiscal_Year__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Plan__c</referenceTo>
    <relationshipLabel>Bottom Up Constructs</relationshipLabel>
    <relationshipName>Bottom_Up_Constructs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Interaction_Level__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Interaction_Level__c</fullName>
    <label>Interaction Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Board Level</fullName>
            </value>
            <value>
                <fullName>Decision Makers/ CXOs</fullName>
            </value>
            <value>
                <fullName>Important Contacts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Stakeholder_Score__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Stakeholder_Score__c</fullName>
    <label>Stakeholder Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1.0</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2.0</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3.0</fullName>
            </value>
            <value>
                <fullName>3.5</fullName>
            </value>
            <value>
                <fullName>4.0</fullName>
            </value>
            <value>
                <fullName>4.5</fullName>
            </value>
            <value>
                <fullName>5.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/ARTL_Internal_Contact.recordType-meta.xml
<RecordType>
    <fullName>ARTL_Internal_Contact</fullName>
    <active>true</active>
    <label>Internal Contact</label>
</RecordType>

force-app/main/default/classes/ARTL_DRE_OpportunityOnAccountPlanTest.cls
@IsTest
private class ARTL_DRE_OpportunityOnAccountPlanTest {
    
    @testSetup static void testData() {
        
        User testUser = new User(FirstName = 'Test', LastName = 'User', Email = 'test.user@email.com', Username='test7864er@user.com',Alias = 'tuser', TimeZoneSidKey='Asia/Kolkata',
                                 ProfileId = '00e5j0000048gp8AAA', LocaleSidKey = 'en_IN', LanguageLocaleKey  = 'en_US', EmailEncodingKey='UTF-8');
        insert testUser;
        
        Id recordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account acc = new Account(Name = 'TestAccount',
                                              RecordTypeId = recordTypeIdAccount,
                                              BillingCity = 'Panchkula',
                                              BillingCountry = 'Haryana',
                                              BillingPostalCode = '134109',
                                              BillingState = 'India',
                                              BillingStreet = 'Panchkula', 
                                              ARTL_IntegrationId__c = 'test', 
                                              ARTL_Category__c = 'A', 
                                              ARTL_Customer_Segment__c = 'AB',
                                              ARTL_Service_Segment__c = 'BD',
                                              ARTL_Vertical_Segment__c = 'BFI',
                                              ARTL_Business_Circle_Region__c = 'AP',
                                              ARTL_PAN__c = 'ABCDE1234F');
        insert acc;
        
        List<Opportunity> lstOpps = new List<Opportunity>();
        lstOpps = new Opportunity[2];
        lstOpps[0] = new Opportunity(Name='TestOpp1', StageName='Initial', AccountId = acc.Id, Amount = 10, CloseDate = System.Today());
        lstOpps[1] = new Opportunity(Name='TestOpp2', AccountId = acc.Id, StageName='Initial', Amount = 20, CloseDate = System.Today());
        insert lstOpps;
        
        Id recordTypeIdContact = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ARTL_Internal_Contact').getRecordTypeId();
        Contact con = new Contact(FirstName='Test', LastName='Contact', AccountId=acc.Id, OwnerId= testUser.Id, Phone='1234567890',Email='test@test.com',
                                  ARTL_Interaction_Level__c='Board Level', ARTL_Designation__c='TestDesgntn', ARTL_Contact_Role__c = 'Resident Engineer',
                                  ARTL_stakeholder_score__c='2.5', RecordTypeId=recordTypeIdContact,Country_Code__c  = '1',Salutation = 'Ms.'
                                 );
        insert con;
        
        Contact con1 = new Contact(FirstName='TestName', LastName='Contact', AccountId=acc.Id, OwnerId= testUser.Id, Phone='1224567899',Email='test11@test.com',
                                   ARTL_Interaction_Level__c='Board Level', ARTL_Designation__c='TestDesgntn',  ARTL_Contact_Role__c = 'Resident Engineer',
                                   ARTL_stakeholder_score__c='2.5', RecordTypeId=recordTypeIdContact
                                  );
        insert con1;
        
        Event testEvent = new Event(
            Subject = 'Test Event',
            DurationInMinutes = 10,
            vlocity_cmt__eventstatus__c = 'Error',
            ActivityDateTime = System.now(),
            WhoId= con.id,
            WhatId = acc.Id
        );
        insert testEvent;
        
        Account_Plan__c objAP = new Account_Plan__c(Account_Plan_Status__c = 'Draft', Account_Name__c = acc.Id, CE_Head__c = testUser.Id);
        insert objAP;
        
        List<Product2> products = new List<Product2>();
        //Id pbId = Test.getStandardPricebookId();
        products = new Product2[2];
        products[0]=new Product2(name='Test Prod1', Family='Multiplay', ProductCode='VEPC_PRIMARY_LINK ',vlocity_cmt__JSONAttribute__c = '');
        products[1]=new Product2(name='Test Prod2 ', Family='Internet', ProductCode='VEPC_PRIMARY_MPLS_LINK ', vlocity_cmt__JSONAttribute__c = '');
        insert products;
        
        List<Bottom_Up_Construct__c> lstBUCs = new List<Bottom_Up_Construct__c>();
        lstBUCs = new Bottom_Up_Construct__c[2];
        string dateValue = string.valueOf((Date.today()).year()); 
        lstBUCs[0] = new Bottom_Up_Construct__c(Product_Category__c=products[0].Id, Account_Plan__c = objAP.Id,  Account_Name__c = acc.Id, Fiscal_Year__c = dateValue, Total_Competitor_Spends__c=10, Spends_with_Airtel__c=20);
        lstBUCs[1] = new Bottom_Up_Construct__c(Product_Category__c=products[1].Id, Account_Plan__c = objAP.Id, Account_Name__c = acc.Id, Fiscal_Year__c = dateValue, Total_Competitor_Spends__c=10, Spends_with_Airtel__c=20);
        insert lstBUCs; 
    }
    
    static testMethod void testDefault(){
        
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'TestAccount'];
        
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        List<object> arguments = new List<object>();
        arguments.add(acc.Id);
        arguments.add(05);
        inputs.put('arguments', arguments);
        
        ARTL_DRE_OpportunityOnAccountPlan obj = new ARTL_DRE_OpportunityOnAccountPlan();
        Test.startTest();
        obj.invokeMethod('default', inputs, output, options);
        obj.invokeMethod('Test', inputs, output, options);
        Test.stopTest();
        
        List<Map<String, Object>> lstContacts = (List<Map<String, Object>>) output.get('result');
        System.assertEquals(lstContacts.size()>0, true);
    }
    
    static testMethod void testFetchBUC(){
        
        Account_Plan__c objAP = [SELECT Id, Name FROM Account_Plan__c WHERE Account_Plan_Status__c = 'Draft'];
        
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        List<object> arguments = new List<object>();
        
        arguments.add(objAP.Id);
        inputs.put('arguments', arguments);
        
        ARTL_DRE_OpportunityOnAccountPlan obj = new ARTL_DRE_OpportunityOnAccountPlan();
        Test.startTest();
        obj.invokeMethod('fetchBUC', inputs, output, options);
        Test.stopTest();
        
        Map<String, Object> lstContacts = (Map<String, Object>) output.get('result');
        System.assertEquals(lstContacts.size()>0, true);
    }
    
    static testMethod void testFetchFiscalYrOpp(){
        
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'TestAccount'];        
        
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        List<object> arguments = new List<object>();
        arguments.add(acc.Id);
        arguments.add((Date.today()).year());
        inputs.put('arguments', arguments);
        
        ARTL_DRE_OpportunityOnAccountPlan obj = new ARTL_DRE_OpportunityOnAccountPlan();
        Test.startTest();
        obj.invokeMethod('fetchFiscalYrOpp', inputs, output, options);
        Test.stopTest(); 
        
        List<Map<String, Object>> lstContacts = (List<Map<String, Object>>) output.get('result');
        System.assertEquals(lstContacts.size()>0, true);
    }    
}