force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Business Account that the GST is associated with</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GSTs</relationshipLabel>
    <relationshipName>GSTs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GST__c/fields/ARTL_Dty_GST_API_Response__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Dty_GST_API_Response__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dty GST API Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_gstDetailsInBcpDcpTest.cls
@isTest
public class ARTL_gstDetailsInBcpDcpTest {
    @testSetup
    public static void testData(){
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id nbaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        Account businessAcc = new Account(Name = 'Test Business Account', 
                                          RecordTypeId = businessAccountRecordTypeId,
                                          //BillingLatitude = 38.8951, 
                                          //BillingLongitude = -77.0364
                                          BillingCity = 'Panchkula',
                                          BillingCountry = 'Haryana',
                                          BillingPostalCode = '134109',
                                          BillingState = 'India',
                                          BillingStreet = 'Panchkula', 
                                          ARTL_IntegrationId__c = 'test', 
                                          ARTL_Category__c = 'A', 
                                          ARTL_Customer_Segment__c = 'AB',
                                          ARTL_Service_Segment__c = 'BD',
                                          ARTL_Vertical_Segment__c = 'BFI',
                                          ARTL_Business_Circle_Region__c = 'AP',
                                          ARTL_PAN__c = 'ABCDE1234F');
        System.debug('DEBUGG '+ businessAcc.BillingStreet + businessAcc.BillingCity);
        System.debug('DEBUGG '+ businessAcc.BillingAddress);
        insert businessAcc;
        
        Account nba = new Account(Name = 'Test NBA',
                                  RecordTypeId = nbaRecordTypeId, 
                                  ParentId = businessAcc.Id, 
                                  BillingStreet = 'Panchkula',
                                  BillingCity = 'Panchkula',
                                  BillingState = 'Haryana',
                                  BillingPostalCode = '134109',
                                  BillingCountry = 'India', 
                                  ARTL_IntegrationId__c = 'test',
                                  ARTL_Category__c = 'A', 
                                  ARTL_Customer_Segment__c = 'AB',
                                  ARTL_Service_Segment__c = 'BD',
                                  ARTL_Vertical_Segment__c = 'BFI',
                                  ARTL_Business_Circle_Region__c = 'AP');
        insert nba;
        
        GST__c gstRecord = new GST__c(Name = '06ABCDE1234F1Z1',
                                      ARTL_Address__Street__s = 'Test',
                                      ARTL_Address__City__s = 'Panchkula',
                                      ARTL_Address__StateCode__s = 'HR',
                                      ARTL_Address__CountryCode__s = 'IN', 
                                      ARTL_Dty_GST_API_Response__c = 'Regular', 
                                      Account__c = businessAcc.Id, 
                                      Status__c = 'Active');
        insert gstRecord;

    }
    
    @isTest 
    public static void testGetGstDetails(){
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account businessAccount = [Select Id from Account where RecordTypeId = :businessAccountRecordTypeId];
        Account nba = [Select Id from Account where ParentId = :businessAccount.Id];
        Test.startTest();
        ARTL_gstDetailsInBcpDcp.getGstDetails('Haryana', nba.Id, 'Non-SEZ');
        Test.stopTest();
        
    }
    
    @isTest
    public static void testCreateBCP(){
        Id nbaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        Account nba = [Select Id from Account where RecordTypeId = :nbaRecordTypeId];
        Map<String, Object> addressDetails = new Map<String, Object>{
            'street' => 'test',
                'city' => 'Panchkula',
                'state' => 'Haryana',
                'country' => 'India',
                'TApincode'=> '134109',
                'pincode' => '134109'
                };
        Map<String, Object> pincodeBlock = new Map<String, Object>{
             'TApincode-Block' => addressDetails,
                 
                 'Messaging1' => null,
                 'pincodeExistFormula' => true,
                 'errorMessage' => 'Please select a GST number.',
                 'gstNumber' => null,
                 'Messaging2' => null,
                 'Select_Salutation' =>'Mr.',
                 'TXT_FirstName' => 'test',
                 'TXT_LastName' => 'test',
                 'TXT_Email' => 'test@test.com',
                 'Number_Mobile' => '0987654321',
                 'Select_Role' => 'DCP',
                 'alternateEmail' => null,
                 'fax' => null,
                 'gstApplicable' => 'Yes',
                 'standardReason' => 'Non-SEZ',
                 'gstType' => 'Non-SEZ',
                 'lwcError' => 'Please select a GST number.', 
                 'designation'=> 'test'
                 };
        Map<String, Object> input = new Map<String, Object>{
            'ContextId' => nba.Id, 
                'Step_ContactDetails' => pincodeBlock
                
        };
            Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
            System.debug('DEBUGG '+ input);
        Test.startTest();
        ARTL_gstDetailsInBcpDcp helper = new ARTL_gstDetailsInBcpDcp();
        Boolean result = helper.invokeMethod('createBcp', input, output, options);
        Test.stopTest();
    }
    
    @isTest
    public static void testCreateBCP2(){
        Id nbaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        Account nba = [Select Id from Account where RecordTypeId = :nbaRecordTypeId];
        Map<String, Object> addressDetails = new Map<String, Object>{
            'street' => 'test',
                'city' => 'Panchkula',
                'state' => 'Haryana',
                'country' => 'India',
                'TApincode'=> '134109',
                'pincode' => '134109'
                };
        Map<String, Object> pincodeBlock = new Map<String, Object>{
             'TApincode-Block' => addressDetails,
                 
                 'Messaging1' => null,
                 'pincodeExistFormula' => true,
                 'errorMessage' => 'Please select a GST number.',
                 'gstNumber' => null,
                 'Messaging2' => null,
                 'Select_Salutation' =>'Mr.',
                 'TXT_FirstName' => 'test',
                 'TXT_LastName' => 'test',
                 'TXT_Email' => 'test@test.com',
                 'Number_Mobile' => '0987654321',
                 'Select_Role' => 'BCPandDCP',
                 'alternateEmail' => null,
                 'fax' => null,
                 'gstApplicable' => 'Yes',
                 'standardReason' => 'Non-SEZ',
                 'gstType' => 'Non-SEZ',
                 'lwcError' => 'Please select a GST number.', 
                 'designation'=> 'test'
                 };
        Map<String, Object> input = new Map<String, Object>{
            'ContextId' => nba.Id, 
                'Step_ContactDetails' => pincodeBlock
                
        };
            Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
            System.debug('DEBUGG '+ input);
        Test.startTest();
        ARTL_gstDetailsInBcpDcp helper = new ARTL_gstDetailsInBcpDcp();
        Boolean result = helper.invokeMethod('createBcp', input, output, options);
        Test.stopTest();
    }
    
    @isTest
    public static void testCreateBCP3(){
        Id nbaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BillingAggregator').getRecordTypeId();
        Account nba = [Select Id from Account where RecordTypeId = :nbaRecordTypeId];
        Map<String, Object> addressDetails = new Map<String, Object>{
            'street' => 'test',
                'city' => 'Panchkula',
                'state' => 'Haryana',
                'country' => 'India',
                'TApincode'=> '134109',
                'pincode' => '134109'
                };
        Map<String, Object> pincodeBlock = new Map<String, Object>{
             'TApincode-Block' => addressDetails,
                 
                 'Messaging1' => null,
                 'pincodeExistFormula' => true,
                 'errorMessage' => 'Please select a GST number.',
                 'gstNumber' => null,
                 'Messaging2' => null,
                 'Select_Salutation' =>'Mr.',
                 'TXT_FirstName' => 'test',
                 'TXT_LastName' => 'test',
                 'TXT_Email' => 'test@test.com',
                 'Number_Mobile' => '0987654321',
                 'Select_Role' => 'BCP',
                 'alternateEmail' => null,
                 'fax' => null,
                 'gstApplicable' => 'Yes',
                 'standardReason' => 'Non-SEZ',
                 'gstType' => 'Non-SEZ',
                 'lwcError' => 'Please select a GST number.', 
                 'designation'=> 'test'
                 };
        Map<String, Object> input = new Map<String, Object>{
            'ContextId' => nba.Id, 
                'Step_ContactDetails' => pincodeBlock
                
        };
            Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
            System.debug('DEBUGG '+ input);
        Test.startTest();
        ARTL_gstDetailsInBcpDcp helper = new ARTL_gstDetailsInBcpDcp();
        Boolean result = helper.invokeMethod('createBcp', input, output, options);
        Test.stopTest();
    }


}