force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Date__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Date__c</fullName>
    <formula>TEXT(Start_Date__c)</formula>
    <label>PO Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ARTL_LSIRequired__c.field-meta.xml
<CustomField>
    <fullName>ARTL_LSIRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LSI Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ARTL_TechnicalProduct__c.field-meta.xml
<CustomField>
    <fullName>ARTL_TechnicalProduct__c</fullName>
    <label>ARTL Technical Product</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ARTL_LSI_Count__c.field-meta.xml
<CustomField>
    <fullName>ARTL_LSI_Count__c</fullName>
    <label>LSI Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ARTL_PO_Total__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Total__c</fullName>
    <label>PO Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ARTL_QNeedCapexApproval__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QNeedCapexApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Capex Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ARTL_QNeedDOAApproval__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QNeedDOAApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need DOA Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Annual_Recurring_Charge__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Charge__c</fullName>
    <label>Annual Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_ARCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_ARCFloorRate__c</fullName>
    <label>Annual Recurring Charge Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_NeedCapexApproval__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NeedCapexApproval__c</fullName>
    <formula>NOT(ISBLANK(Capex__c))  &amp;&amp; NOT(ISBLANK(Annual_Recurring_Charge__c)) &amp;&amp; Annual_Recurring_Charge__c * 3  &gt;  Capex__c</formula>
    <label>Need Capex Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_NeedDOAApproval__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NeedDOAApproval__c</fullName>
    <formula>IF(OR(Annual_Recurring_Total__c &lt; ARTL_ARCFloorRate__c, vlocity_cmt__OneTimeTotal__c &lt; ARTL_NRCFloorRate__c), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Need DOA Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_NRCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NRCFloorRate__c</fullName>
    <label>One Time Charge Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capex__c.field-meta.xml
<CustomField>
    <fullName>Capex__c</fullName>
    <label>Capex</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemTriggerTest.cls
@isTest
public class QuoteLineItemTriggerTest {
    @testSetup
    static void dataCreation() {
        try{
            
       
        Account acc = new Account(Name = 'Test Account quote trigger tst',billingCity='pune',billingState = 'Maharastra', ARTL_Legal_Entity__c = 'NXTRA DATA LIMITED',artl_customer_segment__c = 'AB',
                                  artl_business_circle_region__c = 'NCR' , artl_vertical_segment__c= 'BFI');
        insert acc; 
        
		Contact contactRec = new Contact(FirstName 				= 'Test',
                                         LastName				= 'Test',
                                         Phone					= '9887654321', 
                                         Email					= 'test@test.com',
                                         ARTL_Designation__c 	= 'test', 
                                         ARTL_Contact_Role__c 	= 'Billing Contact', 
                                         country_code__c='1',
                                         AccountId 				= acc.Id);
        insert contactRec;  
        
        Product2 prod = new Product2(Name = 'Test product1', family = 'Internet',ProductCode='VEPC_PRIMARY_LINK', ARTL_LSIRequired__c=true);
        insert prod;
        system.debug('product=>'+prod);    
            
         PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            UnitPrice = 100.00, // Set the unit price as needed
            IsActive = true
        );
        insert pbEntry;
        system.debug('pbEntry=>'+pbEntry);
    
            
        vlocity_cmt__PriceList__c priceList = new 	vlocity_cmt__PriceList__c();
        priceList.Name ='Pricelist For Test class';
        priceList.vlocity_cmt__Code__c='PricelistForTestclass';
        priceList.vlocity_cmt__Pricebook2Id__c =Test.getStandardPricebookId();
        insert priceList;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opportunity';
        opp.CloseDate= System.Today();
        opp.StageName='Prospecting';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        
        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.Name = 'Quote Test';
        q.vlocity_cmt__PriceListId__c=priceList.Id;
        q.Pricebook2Id = Test.getStandardPricebookId();
        q.Status ='Draft';
        q.ARTL_QNeedCapexApproval__c=True;
        q.ARTL_PO_Total__c = 0;
        q.ARTL_LSI_Count__c = 0;    
        insert q;
        system.debug('q=>'+q);
            
        Asset ast = new Asset();
        ast.Name = 'Test3';
        ast.AccountId = acc.Id;
        ast.vlocity_cmt__AssetReferenceId__c = '123';
        ast.vlocity_cmt__BillingAccountId__c  = acc.Id;
        ast.vlocity_cmt__ServiceAccountId__c   = acc.Id;
        
        insert ast;
       ARTL_Purchase_Order__c  po = new ARTL_Purchase_Order__c();
        po.ARTL_Account__c = acc.id;
        po.Amount__c = 10000;
        //   po.ARTL_PO_Date__c = system.today();
        po.End_Date__c = system.today() + 30 ;
        po.ARTL_PO_Number__c = '123133';
        
        Insert po;
            
        
        QuoteLineItem qli = new QuoteLineItem(
            vlocity_cmt__Product2Id__c = prod.Id,
            QuoteId = q.Id,
            PricebookEntryId = pbEntry.Id,
            UnitPrice = pbEntry.UnitPrice,
            Quantity=1,
            Capex__c=50000,
            Annual_Recurring_Charge__c=225000,
            vlocity_cmt__OneTimeCharge__c=220000,
            ARTL_ARCFloorRate__c=50000,
            ARTL_NRCFloorRate__c=50000,
            vlocity_cmt__AssetReferenceId__c = '123',
            ARTL_Purchase_Order__c = po.Id
			            
        );
               
            insert qli;
            system.debug('qli=>'+qli);

         
        
        }catch(exception e){
            System.debug('Exception in data createation @line number'+e.getLineNumber()+' ['+e.getMessage()+']');
        }
        
    }
    
    /*
    @isTest
    static void testQuoteTrigger() {
        Test.startTest();
        
        Product2 objProduct = new Product2(Name = 'Test product1', family = 'Cafe',ProductCode='XYZ_1',
                                           ARTL_TechnicalProduct__c='ABC_x');
        insert objProduct;
        Product2 objProduct2 = new Product2(Name = 'Test product11', family = 'Cafe',ProductCode='ABC_x');
        insert objProduct2;
        
        PriceBookEntry objPBE = new PriceBookEntry(UnitPrice = 300, PriceBook2Id = Test.getStandardPricebookId(),Product2Id = objProduct.Id, IsActive = true);
        insert objPBE;
        List<Quote> qList=[select id,name,AccountId,Status,Pricebook2Id from Quote];
        List<Quotelineitem> Listqli = new List<Quotelineitem>();
        for(Quote q:qList){
            Quotelineitem qli1 = new QuoteLineItem(QuoteId = q.id, PriceBookentryId = objPBE.id, Quantity = 1, UnitPrice = 1,
                                                   Product2Id=objProduct.Id);
            Listqli.add(qli1); 
        }
        insert Listqli;
        
        
        Test.stopTest();
    }
    */
        
   
    @isTest
    static void updateDOACapexFieldsFUpdateTest1() {
            
        Test.StartTest();
        
        Product2 prod = new Product2(Name = 'Test product2', family = 'Internet',ProductCode='VEPC_PRIMARY_LINK', ARTL_LSIRequired__c=true);
        insert prod;
        
        ARTL_Purchase_Order__c  po = new ARTL_Purchase_Order__c();
        po.ARTL_Account__c = [SELECT id FROM Account LIMIT 1].Id ; 
        po.Amount__c = 10000;
        //   po.ARTL_PO_Date__c = system.today();
        po.End_Date__c = system.today() + 30 ;
        po.ARTL_PO_Number__c = '12555533';
        
        Insert po;
        
        QuoteLineItem qliRet=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c,ARTL_Purchase_Order__c,vlocity_cmt__Product2Id__c FROM QuoteLineItem  ];
        system.debug('qliRet new =>'+qliRet);
        qliRet.Capex__c=10000000;
        qliRet.Annual_Recurring_Charge__c=100;
        qliRet.vlocity_cmt__OneTimeCharge__c=100;
        qliRet.ARTL_ARCFloorRate__c=500000;
        qliRet.ARTL_NRCFloorRate__c=500000;
        qliRet.ARTL_Purchase_Order__c = po.Id;
        qliRet.vlocity_cmt__Product2Id__c = prod.Id;
        update qliRet;
        
        Test.stopTest();
        
    }
    
     /*
    @isTest
    static void updateDOACapexFieldsFUpdateTest2() {
        try{
        Test.startTest();
        Account acc = new Account(Name = 'Test Account');
        insert acc; 
        
        Product2 prod = new Product2(Name = 'Test product1', family = 'Internet',ProductCode='VEPC_PRIMARY_LINK', ARTL_LSIRequired__c=true);
        insert prod;
        system.debug('product=>'+prod);
        // Create a Pricebook
        
        // Create a Pricebook Entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            UnitPrice = 100.00, // Set the unit price as needed
            IsActive = true`
        );
        insert pbEntry;
        system.debug('pbEntry=>'+pbEntry);
        
        vlocity_cmt__PriceList__c priceList=[select id from vlocity_cmt__PriceList__c limit 1];
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opportunity';
        opp.CloseDate= System.Today();
        opp.StageName='Prospecting';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        system.debug('opp=>'+opp);
        
        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.Name = 'Quote Test';
        q.vlocity_cmt__PriceListId__c=priceList.Id;
        q.Pricebook2Id = Test.getStandardPricebookId();
        q.Status ='Draft';
        //q.ARTL_QNeedCapexApproval__c=True;
        insert q;
        system.debug('q=>'+q);
        
        
        QuoteLineItem qli = new QuoteLineItem(
            Product2Id = prod.Id,
            QuoteId = q.Id,
            PricebookEntryId = pbEntry.Id,
            UnitPrice = pbEntry.UnitPrice,
            Quantity=1,
            Capex__c=1000000,
            Annual_Recurring_Charge__c=225000,
            vlocity_cmt__OneTimeCharge__c=220000,
            ARTL_ARCFloorRate__c=50000,
            ARTL_NRCFloorRate__c=50000
        );
        insert qli;
        system.debug('qli=>'+qli);
        QuoteLineItem qliCheck=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c,ARTL_NeedCapexApproval__c,ARTL_NeedDOAApproval__c FROM QuoteLineItem WHERE Id=:qli.Id];
        system.debug('qli check=>'+JSON.serializePretty(qliCheck));
        
        QuoteLineItem qliRet=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c FROM QuoteLineItem WHERE Id=:qli.Id];
        system.debug('qliRet=>'+qliRet);
        qliRet.Capex__c=10;
        qliRet.Annual_Recurring_Charge__c=100;
        qliRet.vlocity_cmt__OneTimeCharge__c=100;
        qliRet.ARTL_ARCFloorRate__c=500000;
        qliRet.ARTL_NRCFloorRate__c=500000;
        update qliRet;
        
        Test.stopTest();
            }catch(exception e){
            System.debug('Exception in  method::updateDOACapexFieldsFUpdateTest2 @line number'+e.getLineNumber()+' ['+e.getMessage()+']');
        }
    }
   
    @isTest
    static void updateDOACapexFieldsFUpdateTest3() {
        try{
        Test.startTest();
        Account acc = new Account(Name = 'Test Account');
        insert acc; 
        
        Product2 prod = new Product2(Name = 'Test product1', family = 'Internet',ProductCode='VEPC_PRIMARY_LINK', ARTL_LSIRequired__c=true);
        insert prod;
        system.debug('product=>'+prod);
        // Create a Pricebook
        
        // Create a Pricebook Entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prod.Id,
            UnitPrice = 100.00, // Set the unit price as needed
            IsActive = true
        );
        insert pbEntry;
        system.debug('pbEntry=>'+pbEntry);
        
        vlocity_cmt__PriceList__c priceList=[select id from vlocity_cmt__PriceList__c limit 1];
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opportunity';
        opp.CloseDate= System.Today();
        opp.StageName='Prospecting';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        system.debug('opp=>'+opp);
        
        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.Name = 'Quote Test';
        q.vlocity_cmt__PriceListId__c=priceList.Id;
        q.Pricebook2Id = Test.getStandardPricebookId();
        q.Status ='Draft';
        q.ARTL_QNeedCapexApproval__c=True;
        q.ARTL_QNeedDOAApproval__c=True;
        insert q;
        system.debug('q=>'+q);
        
      	      
        
        QuoteLineItem qli = new QuoteLineItem(
            Product2Id = prod.Id,
            QuoteId = q.Id,
            PricebookEntryId = pbEntry.Id,
            UnitPrice = pbEntry.UnitPrice,
            Quantity=1,
            Capex__c=1000,
            Annual_Recurring_Charge__c=225000,
            vlocity_cmt__OneTimeCharge__c=220000,
            ARTL_ARCFloorRate__c=500000,
            ARTL_NRCFloorRate__c=500000
        );
        insert qli; 
            
       ARTL_Purchase_Order__c  po = new ARTL_Purchase_Order__c();
            po.ARTL_Account__c = acc.id;
            po.Amount__c = 10000;
         //   po.ARTL_PO_Date__c = system.today();
            po.End_Date__c = system.today() + 30 ;
            po.ARTL_PO_Number__c = '123133';
            po.Quote_Line_Item__c = qli.Id;
            
            Insert po;
            
        system.debug('qli=>'+qli);
        QuoteLineItem qliCheck=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c,ARTL_NeedCapexApproval__c,ARTL_NeedDOAApproval__c FROM QuoteLineItem WHERE Id=:qli.Id];
        system.debug('qli check=>'+JSON.serializePretty(qliCheck));
        
        QuoteLineItem qliRet=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c FROM QuoteLineItem WHERE Id=:qli.Id];
        system.debug('qliRet=>'+qliRet);
        qliRet.Capex__c=10000000;
        qliRet.Annual_Recurring_Charge__c=2250000;
        qliRet.vlocity_cmt__OneTimeCharge__c=2250000;
        qliRet.ARTL_ARCFloorRate__c=500000;
        qliRet.ARTL_NRCFloorRate__c=500000;
        update qliRet;
        
        Test.stopTest();
            }catch(exception e){
            System.debug('Exception in class:: method::updateDOACapexFieldsFUpdateTest3 @line number'+e.getLineNumber()+' ['+e.getMessage()+']');
        }
    }
*/    
    /*
  
    @isTest
    static void testCreateBillingStaging() {
        
            Test.startTest();
            Account acc = new Account(Name = 'Test Account');
            insert acc; 
           
            Contact contactRec = new Contact(FirstName 				= 'Test',
                                         LastName				= 'Test',
                                         Phone					= '9887654321', 
                                         Email					= 'test@test.com',
                                         ARTL_Designation__c 	= 'test', 
                                         ARTL_Contact_Role__c 	= 'Billing Contact', 
                                         AccountId 				= acc.Id);
        insert contactRec;
            
            Product2 prod = new Product2(Name = 'Test product1', family = 'Internet',ProductCode='VEPC_PRIMARY_LINK', ARTL_LSIRequired__c=true);
            insert prod;
            system.debug('product=>'+prod);
            // Create a Pricebook
            
            // Create a Pricebook Entry
            PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = Test.getStandardPricebookId(),
                Product2Id = prod.Id,
                UnitPrice = 100.00, // Set the unit price as needed
                IsActive = true
            );
            insert pbEntry;
            system.debug('pbEntry=>'+pbEntry);
            
            vlocity_cmt__PriceList__c priceList=[select id from vlocity_cmt__PriceList__c limit 1];
            
            Opportunity opp = new Opportunity();
            opp.AccountId = acc.Id;
            opp.Name = 'Test Opportunity';
            opp.CloseDate= System.Today();
            opp.StageName='Prospecting';
            opp.Pricebook2Id = Test.getStandardPricebookId();
            insert opp;
            system.debug('opp=>'+opp);
            
            Quote q = new Quote();
            q.OpportunityId = opp.Id;
            q.Name = 'Quote Test';
            q.vlocity_cmt__PriceListId__c=priceList.Id;
            q.Pricebook2Id = Test.getStandardPricebookId();
            q.Status ='Draft';
            q.ARTL_QNeedCapexApproval__c=True;
            q.ARTL_QNeedDOAApproval__c=True;
            q.ARTL_PO_Total__c = 0;
            q.ARTL_LSI_Count__c = 0;
            insert q;
            system.debug('q=>'+q);
            Asset ast = new Asset();
            ast.Name = 'Test3';
            ast.AccountId = acc.Id;
            ast.vlocity_cmt__AssetReferenceId__c = '123';
            ast.vlocity_cmt__BillingAccountId__c  = acc.Id;
            ast.vlocity_cmt__ServiceAccountId__c   = acc.Id;
            
            insert ast;
            
        	ARTL_Purchase_Order__c  po = new ARTL_Purchase_Order__c();
            po.ARTL_Account__c = acc.id;
            po.Amount__c = 10000;
            //   po.ARTL_PO_Date__c = system.today();
            po.End_Date__c = system.today() + 30 ;
            po.ARTL_PO_Number__c = '123133';
           // po.Quote_Line_Item__c = qli.Id;
            
            Insert po;
            
            QuoteLineItem qli = new QuoteLineItem(
                Product2Id = prod.Id,
                QuoteId = q.Id,
                PricebookEntryId = pbEntry.Id,
                UnitPrice = pbEntry.UnitPrice,
                Quantity=1,
                vlocity_cmt__AssetId__c = ast.Id,
                Capex__c=1000,
                vlocity_cmt__AssetReferenceId__c = '123',
                Annual_Recurring_Charge__c=225000,
                vlocity_cmt__OneTimeCharge__c=220000,
                ARTL_ARCFloorRate__c=500000,
                ARTL_NRCFloorRate__c=500000,
                ARTL_Purchase_Order__c = po.Id
            );
            insert qli;
            
            
            
            
            system.debug('qli=>'+qli);
            QuoteLineItem qliCheck=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c,ARTL_NeedCapexApproval__c,ARTL_NeedDOAApproval__c FROM QuoteLineItem WHERE Id=:qli.Id];
            system.debug('qli check=>'+JSON.serializePretty(qliCheck));
            
            /*
            QuoteLineItem qliRet=[SELECT Id,Capex__c,Annual_Recurring_Charge__c,vlocity_cmt__OneTimeCharge__c,ARTL_Purchase_Order__c FROM QuoteLineItem WHERE Id=:qli.Id];
            system.debug('qliRet=>'+qliRet);
            qliRet.Capex__c=10000000;
            qliRet.Annual_Recurring_Charge__c=2250000;
            qliRet.vlocity_cmt__OneTimeCharge__c=2250000;
            qliRet.ARTL_ARCFloorRate__c=500000;
            qliRet.ARTL_NRCFloorRate__c=500000;
            update qliRet;
            
            Test.stopTest();
        }catch( Exception ex){
        //    System.debug('Exception createBillingStaging ex -'+ex.getMessage()+' LNo '+ex.getLineNumber());
        //}
        
    }
   */
    
    
}