force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Channel__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATB</fullName>
            </value>
            <value>
                <fullName>AirtelIQ</fullName>
            </value>
            <value>
                <fullName>ECAF</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Reve</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>Siebel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_FX_Leo_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_FX_Leo_Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FX Leo Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_GST_Non_Applicable_Reason__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Non_Applicable_Reason__c</fullName>
    <label>GST Non Applicable Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied For</fullName>
            </value>
            <value>
                <fullName>Non-SEZ</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- Export</fullName>
            </value>
            <value>
                <fullName>Non Taxable as transactions within same Company</fullName>
            </value>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>SEZ With Taxes</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- FTWZ</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>UIN</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Airtel- Foreign Legal Entity</fullName>
            </value>
            <value>
                <fullName>Exempt Supply- Trust/Entities 12AA</fullName>
            </value>
            <value>
                <fullName>Exempt Supply- UNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Origin__c.field-meta.xml
<CustomField>
    <fullName>Customer_Origin__c</fullName>
    <label>Customer Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/isMigrated__c.field-meta.xml
<CustomField>
    <fullName>isMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for Data Migration</description>
    <label>isMigrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Code__c.field-meta.xml
<CustomField>
    <fullName>Short_Code__c</fullName>
    <label>Short Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Business Account that the GST is associated with</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GSTs</relationshipLabel>
    <relationshipName>GSTs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GST__c/fields/ARTL_GST_Type__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Type__c</fullName>
    <formula>CASE(
    ARTL_Dty_GST_API_Response__c,
    &apos;Regular&apos;, &apos;Non-SEZ&apos;,
    &apos;SEZ&apos;, &apos;SEZ&apos;,
    &apos;SEZ Unit&apos;, &apos;SEZ&apos;,
    &apos;UIN&apos;, &apos;UIN&apos;,
    &apos;Tax Deductor&apos;,&apos;Tax Deductor&apos;,
    &apos;&apos;
)</formula>
    <label>GST Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_B2BFetchPartyAccount.cls
public class ARTL_B2BFetchPartyAccount {
    public static string queryPartyJSONResponse(String AccountNumber, String OrderId){
System.debug('queryPartyJSONResponse');
Account ast = new Account();
List<GST__c> gstList = new List<GST__c>();
List<Account> accList = new List<Account>();
AccountTeamMember accTeamMem = new AccountTeamMember ();
    Order ord = new Order();
System.debug('before if');
if(AccountNumber != null){
System.debug('inside if');
Account accobj = [Select id,Owner.Phone,Parent.ARTL_Collection_Manager__r.Phone,Parent.ARTL_Collection_Manager__r.LastName,Parent.vlocity_cmt__PrimaryContactId__r.LastName,Phone,Parent.ARTL_TL__r.Phone,ARTL_Channel__c,Parent.ARTL_GST_Non_Applicable_Reason__c,Parent.BillingAddress,Parent.ARTL_GST_Applicable__c,Parent.vlocity_cmt__Status__c,Parent.Owner.FirstName, parent.ARTL_PAN__c, 
Parent.Owner.FederationIdentifier,ParentId,Parent.Owner.Email,Parent.Owner.LastName, ARTL_Category__c,Parent.Project_Manager__r.FirstName,BillingPostalCode,
Parent.ARTL_Collection_Manager__r.FirstName,Parent.ARTL_TL__r.LastName, Parent.ARTL_TL__r.FirstName, ARTL_Customer_Segment__c, 
Parent.vlocity_cmt__PrimaryContactId__r.Phone, Parent.Project_Manager__r.Email, isMigrated__c,Parent.AccountNumber,Parent.ARTL_FX_Leo_Account_Number__c,
Parent.ARTL_Service_Segment__c,Parent.Name,Parent.vlocity_cmt__PrimaryContactId__r.FirstName,Parent.ARTL_TL__r.Email,Parent.ARTL_Vertical_Segment__c,
Parent.Project_Manager__r.LastName,Parent.Customer_Origin__c,BillingCountry,Parent.Project_Manager__r.Phone,ARTL_Business_Circle_Region__c                  
from Account where AccountNumber =:AccountNumber];
    
System.debug('first query');
List<GST__c> listGst = [select id,ARTL_GST_Type__c,Account__c,Name from GST__c  where Account__c =: accobj.ParentId];
System.debug('Second query');
List<Account> accountList = [select id,Short_Code__c,AccountNumber,ARTL_Customer_Segment__c,Parent.vlocity_cmt__Status__c,Phone,Name from Account where ParentId = :accobj.ParentId ]; // for non billing account .. panding work.
System.debug('third query');
List<AccountTeamMember> accTeamMember = [Select id,User.LastName, User.FederationIdentifier from AccountTeamMember where AccountId = :accobj.ParentId  AND TeamMemberRole ='SAM'];

System.debug('AccountTeamMember');
ast = accobj;
gstList = listGst;
accList = accountList;
if(!accTeamMember.isEmpty())
accTeamMem = accTeamMember[0];
}else if(AccountNumber == null && orderId != null){
 ord = [select id,AccountId,Account.ARTL_Channel__c,Account.Owner.Email,account.Project_Manager__r.FirstName, account.Owner.LastName, BillingPostalCode, account.ARTL_Collection_Manager__r.FirstName,
        account.ARTL_TL__r.LastName, account.ARTL_TL__r.FirstName, account.vlocity_cmt__PrimaryContactId__r.Phone , 
        account.Project_Manager__r.Email, account.vlocity_cmt__Status__c, account.owner.FirstName, account.ARTL_PAN__c, 
        account.ARTL_TL__r.Phone, account.vlocity_cmt__PrimaryContactId__r.LastName , account.ARTL_Collection_Manager__r.LastName,account.ARTL_GST_Applicable__c, 
        account.BillingAddress,account.ARTL_Collection_Manager__r.Phone ,account.ARTL_GST_Non_Applicable_Reason__c, account.AccountNumber, 
        Owner.Phone, Account.ARTL_FX_Leo_Account_Number__c, account.ARTL_Service_Segment__c, account.Name , 
        account.vlocity_cmt__PrimaryContactId__r.FirstName , account.ARTL_TL__r.Email, account.ARTL_Vertical_Segment__c, 
        account.Project_Manager__r.LastName, account.Customer_Origin__c, BillingCountry, account.Project_Manager__r.Phone,account.Owner.FederationIdentifier   from Order where Id = :orderId];
    
 AccountTeamMember accTeamMember = [Select id,User.LastName, User.FederationIdentifier from AccountTeamMember where AccountId = :ord.AccountId  AND TeamMemberRole ='SAM'];
 List<GST__c> listGst = [select id,Account__c,Name,ARTL_GST_Type__c from GST__c  where Account__c =: ord.AccountId];
 List<Account> accountList = [select id,Parent.vlocity_cmt__Status__c,Phone,Name, Short_Code__c , ARTL_Customer_Segment__c, AccountNumber from Account where ParentId = :ord.AccountId ];
 gstList = listGst;
 accList = accountList;
 accTeamMem = accTeamMember;
}
System.debug('AccountNumber orderId'+orderId+AccountNumber);
if(AccountNumber != null || (AccountNumber == null && orderId != null)){
ARTL_B2BFetchPartyAccount wrapper = new ARTL_B2BFetchPartyAccount();
wrapper.StatusMessage = 'Party details returned successfully';   

wrapper.SFDCMessage = new ARTL_B2BFetchPartyAccount.clsSFDCMessage();
wrapper.SFDCMessage.IntObjectName = 'B2B Party NBA Query';
wrapper.SFDCMessage.MessageType = 'Integration Object';

wrapper.SFDCMessage.B2BParty = new ARTL_B2BFetchPartyAccount.clsB2BParty(); 
wrapper.SFDCMessage.B2BParty.KAMEmail = (AccountNumber != null) ? ast.Parent.Owner.Email :ord.Account.Owner.Email;
wrapper.SFDCMessage.B2BParty.ZSMPhone = '';
wrapper.SFDCMessage.B2BParty.Category = ast.ARTL_Category__c; // not able to get in the order ..
wrapper.SFDCMessage.B2BParty.ProjectManagerFirstName = (AccountNumber != null) ? ast.Parent.Project_Manager__r.FirstName : ord.account.Project_Manager__r.FirstName;
wrapper.SFDCMessage.B2BParty.KAMLastName = (AccountNumber != null) ? ast.Parent.Owner.LastName : ord.account.Owner.LastName;
wrapper.SFDCMessage.B2BParty.OwnedBy = (AccountNumber != null) ? ast.Parent.Owner.FederationIdentifier : ord.account.Owner.FederationIdentifier;
wrapper.SFDCMessage.B2BParty.PrimaryAddressPincode = (AccountNumber != null) ? ast.BillingPostalCode : ord.BillingPostalCode;
wrapper.SFDCMessage.B2BParty.ZSMFirstName = '';
wrapper.SFDCMessage.B2BParty.TSMLastName = '';
wrapper.SFDCMessage.B2BParty.ContactEmailAddress = '';
wrapper.SFDCMessage.B2BParty.CollectionManagerFirstName = (AccountNumber != null) ? ast.Parent.ARTL_Collection_Manager__r.FirstName : ord.account.ARTL_Collection_Manager__r.FirstName; 
wrapper.SFDCMessage.B2BParty.TLLastName = (AccountNumber != null) ? ast.Parent.ARTL_TL__r.LastName : ord.account.ARTL_TL__r.LastName;
wrapper.SFDCMessage.B2BParty.TSMPhone = '';
wrapper.SFDCMessage.B2BParty.GSTCount = string.valueOf(gstList.size());
wrapper.SFDCMessage.B2BParty.SAMPhone = '';
wrapper.SFDCMessage.B2BParty.TSMFirstName = '';
wrapper.SFDCMessage.B2BParty.TLFirstName = (AccountNumber != null) ? ast.Parent.ARTL_TL__r.FirstName : ord.account.ARTL_TL__r.FirstName;
wrapper.SFDCMessage.B2BParty.ZSM = '';
wrapper.SFDCMessage.B2BParty.CustomerSegment = ast.ARTL_Customer_Segment__c;
wrapper.SFDCMessage.B2BParty.ContactPhoneNumber = (AccountNumber != null) ? ast.Parent.vlocity_cmt__PrimaryContactId__r.Phone :ord.account.vlocity_cmt__PrimaryContactId__r.Phone;
wrapper.SFDCMessage.B2BParty.ProjectManagerEmail = (AccountNumber != null) ? ast.Parent.Project_Manager__r.Email : ord.account.Project_Manager__r.Email;
wrapper.SFDCMessage.B2BParty.PartyMigrationFlag = '';
wrapper.SFDCMessage.B2BParty.SAMLastName = accTeamMem.User.LastName;  
wrapper.SFDCMessage.B2BParty.Status = (AccountNumber != null) ? ast.Parent.vlocity_cmt__Status__c : ord.account.vlocity_cmt__Status__c;
wrapper.SFDCMessage.B2BParty.KAMFirstName = (AccountNumber != null) ? ast.Parent.Owner.FirstName : ord.account.owner.FirstName;
wrapper.SFDCMessage.B2BParty.PANNumber = (AccountNumber != null) ? ast.parent.ARTL_PAN__c : ord.account.ARTL_PAN__c;
wrapper.SFDCMessage.B2BParty.TLPhone = (AccountNumber != null) ? ast.Parent.ARTL_TL__r.Phone : ord.account.ARTL_TL__r.Phone;
wrapper.SFDCMessage.B2BParty.Channel = ast.ARTL_Channel__c;
wrapper.SFDCMessage.B2BParty.ContactLastName = (AccountNumber != null) ? ast.Parent.vlocity_cmt__PrimaryContactId__r.LastName : ord.account.vlocity_cmt__PrimaryContactId__r.LastName;
wrapper.SFDCMessage.B2BParty.CollectionManagerLastName = (AccountNumber != null) ? ast.Parent.ARTL_Collection_Manager__r.LastName : ord.account.ARTL_Collection_Manager__r.LastName;
wrapper.SFDCMessage.B2BParty.SAMOLM = '';
wrapper.SFDCMessage.B2BParty.ZSMEmail = '';
wrapper.SFDCMessage.B2BParty.ProjectManager = '';//ast.Project_Manager__c.FederationId;    dont have the field...
wrapper.SFDCMessage.B2BParty.CollectionManager = '';  /// not able to get the field...
wrapper.SFDCMessage.B2BParty.TSM = '';
wrapper.SFDCMessage.B2BParty.Description = '';
wrapper.SFDCMessage.B2BParty.GSTApplicable = String.valueOf((AccountNumber != null) ? ast.Parent.ARTL_GST_Applicable__c : ord.account.ARTL_GST_Applicable__c);
wrapper.SFDCMessage.B2BParty.PrimaryAddressCity = String.valueOf((AccountNumber != null) ? ast.Parent.BillingAddress : ord.account.BillingAddress); 
wrapper.SFDCMessage.B2BParty.ORGTYPE = '';
wrapper.SFDCMessage.B2BParty.CollectionManagerPhone = (AccountNumber != null) ? ast.Parent.ARTL_Collection_Manager__r.Phone : ord.account.ARTL_Collection_Manager__r.Phone;
wrapper.SFDCMessage.B2BParty.Circle = ast.ARTL_Business_Circle_Region__c; ///don't have the field in order ...
wrapper.SFDCMessage.B2BParty.GSTNonApplicableReason = (AccountNumber != null) ? ast.Parent.ARTL_GST_Non_Applicable_Reason__c : ord.account.ARTL_GST_Non_Applicable_Reason__c;
wrapper.SFDCMessage.B2BParty.SFDCAccountNumber = (AccountNumber != null) ? ast.Parent.AccountNumber : ord.account.AccountNumber;
wrapper.SFDCMessage.B2BParty.ZSMLastName = '';
wrapper.SFDCMessage.B2BParty.eCRMAccountNumber = '';
wrapper.SFDCMessage.B2BParty.KAMPhone = (AccountNumber != null) ? ast.Owner.Phone : ord.Owner.Phone;
wrapper.SFDCMessage.B2BParty.PrimaryAddressLine5 = '';
wrapper.SFDCMessage.B2BParty.PrimaryAddressLine4 = '';
wrapper.SFDCMessage.B2BParty.PrimaryAddressLine3 = '';
wrapper.SFDCMessage.B2BParty.Id = (AccountNumber != null) ? ast.ParentId : ord.AccountId;   
wrapper.SFDCMessage.B2BParty.PrimaryAddressLine2 = '';
wrapper.SFDCMessage.B2BParty.PrimaryAddressLine1 = String.valueOf((AccountNumber != null) ? ast.Parent.BillingAddress : ord.account.BillingAddress);
wrapper.SFDCMessage.B2BParty.TSMEmail = '';
wrapper.SFDCMessage.B2BParty.SAMEmail = ''; //// not able to get the email from accountTeamMember
wrapper.SFDCMessage.B2BParty.KAM = '';   /// not getting the field..
wrapper.SFDCMessage.B2BParty.AccountNumber = (AccountNumber != null) ? ast.Parent.AccountNumber :ord.account.AccountNumber;
wrapper.SFDCMessage.B2BParty.FXLeoAccountNumber = (AccountNumber != null) ? ast.Parent.ARTL_FX_Leo_Account_Number__c : ord.Account.ARTL_FX_Leo_Account_Number__c;
wrapper.SFDCMessage.B2BParty.CustomerType = '';
wrapper.SFDCMessage.B2BParty.ServiceSegment = (AccountNumber != null) ? ast.Parent.ARTL_Service_Segment__c : ord.account.ARTL_Service_Segment__c;
wrapper.SFDCMessage.B2BParty.CustomerSegmentNew = '';
wrapper.SFDCMessage.B2BParty.Name = (AccountNumber != null) ? ast.Parent.Name : ord.account.Name;
wrapper.SFDCMessage.B2BParty.ContactFirstName = (AccountNumber != null) ? ast.Parent.vlocity_cmt__PrimaryContactId__r.FirstName : ord.account.vlocity_cmt__PrimaryContactId__r.FirstName;
wrapper.SFDCMessage.B2BParty.TLEmail = (AccountNumber != null) ? ast.Parent.ARTL_TL__r.Email : ord.account.ARTL_TL__r.Email;
wrapper.SFDCMessage.B2BParty.VerticalSegment = (AccountNumber != null) ? ast.Parent.ARTL_Vertical_Segment__c : ord.account.ARTL_Vertical_Segment__c;
wrapper.SFDCMessage.B2BParty.ProjectManagerLastName = (AccountNumber != null) ? ast.Parent.Project_Manager__r.LastName : ord.account.Project_Manager__r.LastName;
wrapper.SFDCMessage.B2BParty.CustomerOrigin = (AccountNumber != null) ? ast.Parent.Customer_Origin__c : ord.account.Customer_Origin__c;
wrapper.SFDCMessage.B2BParty.PrimaryAddressCountry = (AccountNumber != null) ? ast.BillingCountry : ord.BillingCountry;
wrapper.SFDCMessage.B2BParty.ProjectManagerPhone = (AccountNumber != null) ? ast.Parent.Project_Manager__r.Phone : ord.account.Project_Manager__r.Phone;
wrapper.SFDCMessage.B2BParty.ImplementationCircle = ast.ARTL_Business_Circle_Region__c; // not getting field on order..
wrapper.SFDCMessage.B2BParty.CollectionManagerEmail = '';  // no such field on account ...
wrapper.SFDCMessage.B2BParty.SAMFirstName = ''; // not able to get the field from AccountTeamMember..
wrapper.SFDCMessage.B2BParty.TL = '';  // not able to get the field from Account..
wrapper.SFDCMessage.B2BParty.PrimaryAddressState = '';


wrapper.SFDCMessage.B2BParty.B2BGST = new List<ARTL_B2BFetchPartyAccount.clsB2BGST>();   ///
for(GST__c con : gstList){
ARTL_B2BFetchPartyAccount.clsB2BGST newGST = new ARTL_B2BFetchPartyAccount.clsB2BGST();   //
newGST.StartDate = '';
newGST.UINFlag = '';
newGST.EndDate = '';
newGST.GSTNoUINFlag = con.ARTL_GST_Type__c;
newGST.CustomerName = '';
newGST.GSTNumber = '';
wrapper.SFDCMessage.B2BParty.B2BGST.add(newGST);
}
wrapper.SFDCMessage.B2BParty.B2BNonBillingAccount = new List<ARTL_B2BFetchPartyAccount.clsB2BNonBillingAccount>();
for(Account ops :accList){
ARTL_B2BFetchPartyAccount.clsB2BNonBillingAccount newGST1 = new ARTL_B2BFetchPartyAccount.clsB2BNonBillingAccount();
newGST1.LSTDate = '';
newGST1.CoordinatorEmail = '';
newGST1.eCRMAccountNumber = '';
newGST1.CoordinatorContactNumber = '';
newGST1.CSTNumber = '';
newGST1.ShortCode = ops.Short_Code__c;
newGST1.CusTinNumber = '';
newGST1.CustomerSegment = ops.ARTL_Customer_Segment__c;
newGST1.Name = ops.Name;
newGST1.CSTDate = '';
newGST1.Status = ops.Parent.vlocity_cmt__Status__c;
newGST1.CusTinDate = '';
newGST1.LSTNumber = '';
newGST1.CollectionManager = '';
newGST1.State = '';
newGST1.AccountNumber = ops.AccountNumber;
newGST1.CoordinatorName = '';
wrapper.SFDCMessage.B2BParty.B2BNonBillingAccount.add(newGST1);
}
system.debug( ' wrapper : ' + wrapper);
string ttsst = JSON.serialize(wrapper);
return ttsst;
}
return null;
}

public String StatusMessage;   
public clsSFDCMessage SFDCMessage;

public class clsSFDCMessage {
public String IntObjectName;   
public String MessageType;   
public clsB2BParty B2BParty;
}

public class clsB2BParty {
public String KAMEmail;   
public String ZSMPhone;   
public String Category;   
public String ProjectManagerFirstName;   
public String KAMLastName;   
public String OwnedBy;   
public String PrimaryAddressPincode;   
public String ZSMFirstName;   
public String TSMLastName;   
public String ContactEmailAddress;   
public String CollectionManagerFirstName;
public String TLLastName;   
public String TSMPhone;   
public String GSTCount;   
public String SAMPhone;   
public String TSMFirstName;   
public String TLFirstName;   
public String ZSM;   
public String CustomerSegment;   
public String ContactPhoneNumber;   
public String ProjectManagerEmail;
public String PartyMigrationFlag;   
public String SAMLastName;
public String Status;   //
public String KAMFirstName;   
public String PANNumber;
public String TLPhone;
public String Channel;   
public String ContactLastName;
public String CollectionManagerLastName;   
public String SAMOLM;   
public String ZSMEmail;   
public String ProjectManager;   
public String CollectionManager;   
public String TSM;   
public String Description;   
public String GSTApplicable;   
public String PrimaryAddressCity;   
public String ORGTYPE;   
public String CollectionManagerPhone;   
public String Circle;   
public String GSTNonApplicableReason;   
public String SFDCAccountNumber;   
public String ZSMLastName;   
public String eCRMAccountNumber;   
public String KAMPhone;   
public String PrimaryAddressLine5;   
public String PrimaryAddressLine4;   
public String PrimaryAddressLine3;   
public String Id;   
public String PrimaryAddressLine2;   
public String PrimaryAddressLine1;   
public String TSMEmail;   
public String SAMEmail;   
public String KAM;   
public String AccountNumber;   
public String FXLeoAccountNumber;   
public String CustomerType;   
public String ServiceSegment;   
public String CustomerSegmentNew;   
public String Name;   
public String ContactFirstName;   
public String TLEmail;   
public String VerticalSegment;
public String ProjectManagerLastName;
public String CustomerOrigin;   
public String PrimaryAddressCountry;   
public String ProjectManagerPhone;   
public String ImplementationCircle;   
public String CollectionManagerEmail;   
public String SAMFirstName;   
public String TL;   
public String PrimaryAddressState;   
public clsB2BGST[] B2BGST;
public clsB2BNonBillingAccount[] B2BNonBillingAccount;
}

public class clsB2BGST {
public String StartDate;   
public String UINFlag;   
public String EndDate;
public String GSTNoUINFlag;   
public String CustomerName;   
public String GSTNumber;   
}

public class clsB2BNonBillingAccount {
public String LSTDate;   
public String CoordinatorEmail;   
public String eCRMAccountNumber;   
public String CoordinatorContactNumber;   
public String CSTNumber;   
public String ShortCode;   
public String CusTinNumber;   
public String Name;   
public String CSTDate;   
public String Status;   
public String CusTinDate;   
public String CustomerSegment;   
public String LSTNumber;   
public String CollectionManager;   
public String State;   
public String AccountNumber;   
public String CoordinatorName;   
}
}