force-app/main/default/objects/Account/fields/ARTL_Fx_System_Id__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Fx_System_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fx System Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_FXSynch__c.field-meta.xml
<CustomField>
    <fullName>ARTL_FXSynch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FXSynch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/ARTL_VAN_AccountNumbers__c.object-meta.xml
<CustomObject>
    <label>Virtual Account Number</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>VAN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Account Numbers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Active__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Bank__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bank__c</fullName>
    <label>Bank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDFC Bank</fullName>
            </value>
            <value>
                <fullName>Citibank</fullName>
            </value>
            <value>
                <fullName>Axis Bank</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>C</fullName>
                <isActive>false</isActive>
                <label>C</label>
            </value>
            <value>
                <fullName>H</fullName>
                <isActive>false</isActive>
                <label>H</label>
            </value>
            <value>
                <fullName>X</fullName>
                <isActive>false</isActive>
                <label>X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Business_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>VAN_Account_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Fx_System_Id__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Fx_System_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fx System Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_FXSynch__c.field-meta.xml
<CustomField>
    <fullName>ARTL_FXSynch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FXSynch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Legal_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Legal Entity Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Legal_Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity_Description__c</fullName>
    <label>Legal Entity Description</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airtel Digital Limited</fullName>
            </value>
            <value>
                <fullName>Bharti Airtel Ltd</fullName>
            </value>
            <value>
                <fullName>Bharti Airtel Services Ltd</fullName>
            </value>
            <value>
                <fullName>Bharti Hexacom Limited</fullName>
            </value>
            <value>
                <fullName>NXTRA DATA LIMITED</fullName>
            </value>
            <value>
                <fullName>Indo Teleports Limited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AIDL</fullName>
            </value>
            <value>
                <fullName>ASCL</fullName>
            </value>
            <value>
                <fullName>BSCL</fullName>
            </value>
            <value>
                <fullName>HSCL</fullName>
            </value>
            <value>
                <fullName>NSCL</fullName>
            </value>
            <value>
                <fullName>TSCL</fullName>
            </value>
            <value>
                <fullName>BTEL</fullName>
            </value>
            <value>
                <fullName>BHEX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_AccountNumbers__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_Bank_Details__mdt/ARTL_VAN_Bank_Details__mdt.object-meta.xml
<CustomObject>
    <label>VAN Bank Details</label>
    <pluralLabel>VAN Bank Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_VAN_Bank_Details__mdt/fields/Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_Code__c</fullName>
    <label>Bank Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_Legal_Entities__mdt/ARTL_VAN_Legal_Entities__mdt.object-meta.xml
<CustomObject>
    <label>VAN Legal Entities</label>
    <pluralLabel>VAN Legal Entities</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_VAN_Legal_Entities__mdt/fields/ARTL_Active__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_Legal_Entities__mdt/fields/ARTL_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_Legal_Entities__mdt/fields/ARTL_Legal_Entity_Description__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity_Description__c</fullName>
    <label>Legal Entity Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VAN_Legal_Entities__mdt/fields/ARTL_Lob_Identifier__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Lob_Identifier__c</fullName>
    <label>Lob Identifier</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_VANLegalEntityWithBanks__mdt/ARTL_VANLegalEntityWithBanks__mdt.object-meta.xml
<CustomObject>
    <label>VAN Legal Entity With Banks</label>
    <pluralLabel>LegalEntityWithBanks</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_VANLegalEntityWithBanks__mdt/fields/ARTL_VAN_Bank_Details__c.field-meta.xml
<CustomField>
    <fullName>ARTL_VAN_Bank_Details__c</fullName>
    <label>VAN Bank Details</label>
    <referenceTo>ARTL_VAN_Bank_Details__mdt</referenceTo>
    <relationshipLabel>LegalEntityWithBanks</relationshipLabel>
    <relationshipName>LegalEntityWithBanks</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ARTL_VANLegalEntityWithBanks__mdt/fields/ARTL_VAN_Legal_Entities__c.field-meta.xml
<CustomField>
    <fullName>ARTL_VAN_Legal_Entities__c</fullName>
    <label>VAN Legal Entities</label>
    <referenceTo>ARTL_VAN_Legal_Entities__mdt</referenceTo>
    <relationshipName>LegalEntityWithBanks</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ARTL_CreateVANRecords.cls
public class ARTL_CreateVANRecords {
    
    public static void generateVAN(Map<Id,String> vanMap,Map<String,Set<Id>> panMap) {
        System.debug('vanMap '+vanMap);
        System.debug('panMap '+panMap);
        List<ARTL_VAN_AccountNumbers__c> vanRecordsToInsert = new List<ARTL_VAN_AccountNumbers__c>();
        List<ARTL_VANLegalEntityWithBanks__mdt> legalEntBank = [SELECT ARTL_VAN_Legal_Entities__r.ARTL_Legal_Entity__c, ARTL_VAN_Legal_Entities__r.ARTL_Legal_Entity_Description__c ,ARTL_VAN_Legal_Entities__r.ARTL_Lob_Identifier__c ,ARTL_VAN_Bank_Details__r.Bank_Code__c,ARTL_VAN_Bank_Details__r.Label,ARTL_VAN_Bank_Details__c,ARTL_VAN_Legal_Entities__c 
                                                                FROM ARTL_VANLegalEntityWithBanks__mdt
                                                                WHERE ARTL_VAN_Legal_Entities__r.ARTL_Active__c = TRUE];
        
        Map<String,List<ARTL_VAN_AccountNumbers__c>> panVanMap = new Map<String,List<ARTL_VAN_AccountNumbers__c>>();

        Set<Id> existingVANRecId = new Set<Id>();

        List<Account> accList = [Select id, Name,ARTL_PAN__c, (SELECT Id,Name__c,ARTL_Business_Account__c,ARTL_PAN__c,ARTL_Fx_System_Id__c,ARTL_FXSynch__c 
                                                               FROM VAN_Account_Numbers__r)
                                 FROM Account
                                 WHERE ARTL_PAN__c=:panMap.keyset() AND Id IN (SELECT ARTL_Business_Account__c FROM ARTL_VAN_AccountNumbers__c)];
        System.debug('accList '+accList);
        for(Account a: accList){
            System.debug('list of vans '+a.VAN_Account_Numbers__r);
            panVanMap.put(a.ARTL_PAN__c,a.VAN_Account_Numbers__r);
		}
        System.debug('panVanMap '+panVanMap);
        if(!accList.isEmpty()){
        
        for(String pan:panMap.keyset()){
            for(Id accountId:panMap.get(pan)){
              existingVANRecId.add(accountId);
                for(ARTL_VAN_AccountNumbers__c vanRecord:panVanMap.get(pan)){
                    System.debug('vanRecord '+vanRecord);
                   ARTL_VAN_AccountNumbers__c vanObj = vanRecord.clone(false, true, false, false);
              	   vanObj.ARTL_Business_Account__c = accountId;
                   vanRecordsToInsert.add(vanObj); 
                }
            }
          }
        }
        
        vanMap.keyset().removeAll(existingVANRecId);
        
        if(!vanMap.isEmpty()) {
        for(Id AccountId: vanMap.keyset())
        {
          for(ARTL_VANLegalEntityWithBanks__mdt metaRec : legalEntBank) {
            String sequence = metaRec.ARTL_VAN_Legal_Entities__r.ARTL_Legal_Entity__c+metaRec.ARTL_VAN_Legal_Entities__r.ARTL_Lob_Identifier__c+metaRec.ARTL_VAN_Bank_Details__r.Bank_Code__c;
            ARTL_VAN_AccountNumbers__c vanRecord = new ARTL_VAN_AccountNumbers__c(Name__c = sequence,
                                                                                  ARTL_Business_Account__c = AccountId,
                                                                             	  ARTL_PAN__c = vanMap.get(AccountId),
                                                                                  ARTL_Legal_Entity_Code__c = metaRec.ARTL_VAN_Legal_Entities__r.ARTL_Lob_Identifier__c,
                                                                                  ARTL_Legal_Entity_Description__c = metaRec.ARTL_VAN_Legal_Entities__r.ARTL_Legal_Entity_Description__c,
                                                                                  ARTL_Legal_Entity_Name__c = metaRec.ARTL_VAN_Legal_Entities__r.ARTL_Legal_Entity__c,
                                                                                  ARTL_Bank__c = metaRec.ARTL_VAN_Bank_Details__r.Label);
            vanRecordsToInsert.add(vanRecord);
			}
        }
        }
        
        if(!vanRecordsToInsert.IsEmpty()){
            insert vanRecordsToInsert;
		}
    }
    
    public static void updateVAN(Map<Id,String> accMap) {
        		System.debug('Inside VAN');
                List<Account> accList = [Select id, Name,ARTL_PAN__c, (SELECT Id,Name__c,ARTL_Business_Account__c,ARTL_PAN__c,ARTL_Fx_System_Id__c,ARTL_FXSynch__c FROM VAN_Account_Numbers__r)
                                 		 FROM Account
                                 		 WHERE Id=:accMap.keyset() AND Id IN (SELECT ARTL_Business_Account__c FROM ARTL_VAN_AccountNumbers__c)];
                System.debug('Inside VAN');
        		List<ARTL_VAN_AccountNumbers__c> vanList = new List<ARTL_VAN_AccountNumbers__c>();
        		for(Account a: accList){
                    for(ARTL_VAN_AccountNumbers__c vanRecord:a.VAN_Account_Numbers__r){
                        vanRecord.ARTL_PAN__c = accMap.get(a.Id);
                        vanList.add(vanRecord);
                        System.debug('myvan'+vanRecord);
                    }
                }
        if(!vanList.isEmpty()){
            update vanList;
        }
        
    }
}