force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_ARCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_ARCFloorRate__c</fullName>
    <label>ARC Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_NRCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NRCFloorRate__c</fullName>
    <label>NRC Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QuoteLineItemId__c</fullName>
    <label>QuoteLineItemId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__Action__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Action__c</fullName>
    <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Suspend</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/PM_User_Matrix__c.object-meta.xml
<CustomObject>
    <label>PM User Matrix</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM User Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_User_Matrix__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PM User Matrix</relationshipLabel>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CCE__c.field-meta.xml
<CustomField>
    <fullName>CCE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
            <value>
                <fullName>EMERGING</fullName>
            </value>
            <value>
                <fullName>GUJ</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>MPCG</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>NESA</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>UPU</fullName>
            </value>
            <value>
                <fullName>WBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CPH__c.field-meta.xml
<CustomField>
    <fullName>CPH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPH</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM User</description>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/TL__c.field-meta.xml
<CustomField>
    <fullName>TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM&apos;s TL</description>
    <label>TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Annual_Recurring_Charge__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Charge__c</fullName>
    <label>Annual Recurring Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_ARCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_ARCFloorRate__c</fullName>
    <label>Annual Recurring Charge Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_NRCFloorRate__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NRCFloorRate__c</fullName>
    <label>One Time Charge Floor Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capex__c.field-meta.xml
<CustomField>
    <fullName>Capex__c</fullName>
    <label>Capex</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__JSONAttribute__c</fullName>
    <description>JSON body containing Vlocity Attribute value data.</description>
    <label>JSONAttribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__PricingLogData__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PricingLogData__c</fullName>
    <description>Detailed pricing log information for this item stored as a JSON structure. The JSON records the detailed prices, adjustments and interim calculations which result in the price to the customer.</description>
    <label>Pricing Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/LOC.recordType-meta.xml
<RecordType>
    <fullName>LOC</fullName>
    <active>true</active>
    <label>LOC</label>
</RecordType>

force-app/main/default/classes/ARTL_TaskCreationControllerTest.cls
@isTest
public class ARTL_TaskCreationControllerTest {
@testSetup
   static void dataCreation() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account acc = new Account(Name = 'Test Account',ARTL_Business_Circle_Region__c='NCR',BillingCity = 'Panchkula',
                                  BillingCountry = 'Haryana',BillingPostalCode = '134109',BillingState = 'India',BillingStreet = 'Panchkula',
                                  ARTL_Category__c = 'A',RecordTypeId = recordTypeId, ARTL_Customer_Segment__c ='AB', ARTL_Vertical_Segment__c ='BFI',
                                 ARTL_Service_Segment__c ='Bharti');
        insert acc; 

        vlocity_cmt__PriceList__c priceList = new 	vlocity_cmt__PriceList__c();
        priceList.Name ='Pricelist For Test class';
        priceList.vlocity_cmt__Code__c='PricelistForTestclass';
        priceList.vlocity_cmt__Pricebook2Id__c =Test.getStandardPricebookId();
        insert priceList;
		
       PM_User_Matrix__c  userMatrix = new PM_User_Matrix__c();
       userMatrix.Circle__c = 'NCR';
       userMatrix.Business_Account__c = acc.Id;
       userMatrix.CCE__c = Userinfo.getUserId();
       userMatrix.CPH__c = Userinfo.getUserId();
       //userMatrix.PM__c = Userinfo.getUserId();
       userMatrix.TL__c = Userinfo.getUserId();
       insert userMatrix;
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opportunity';
        opp.CloseDate= System.Today();
        opp.StageName='Prospecting';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        
        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.Name = 'Quote Test';
        q.vlocity_cmt__PriceListId__c=priceList.Id;
        q.Pricebook2Id = Test.getStandardPricebookId();
        q.Status ='Draft';
        q.PM__c = Userinfo.getuserId();
        insert q;
       
       
        List<Product2> products = new List<Product2>();
        
        
        Id pbId = Test.getStandardPricebookId();
        
        products = new Product2[2];
        
        products[0]=new Product2(name='VEPC_PRIMARY_LINK', ProductCode='VEPC_PRIMARY_LINK ',vlocity_cmt__JSONAttribute__c = '');
        
        products[1]=new Product2(name='VEPC_PRIMARY_MPLS_LINK ', ProductCode='VEPC_PRIMARY_MPLS_LINK ', vlocity_cmt__JSONAttribute__c = '');
       
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        
        for (Integer i=0; i<products.size(); i++)
        {
            pbes[i] = new PricebookEntry(product2Id = products[i].id, isActive=true,unitPrice = 10, pricebook2id = pbId, useStandardPrice = false);
        }
        
        insert pbes;
        
            
        
        Order order = new Order(AccountId = acc.id, effectiveDate = Date.today(), pricebook2id = pbId, status = 'Draft');
        insert order;
        List<QuoteLineItem> lstQli = new List<QuoteLineItem>();
        QuoteLineItem qli = new QuoteLineItem(
            Product2Id = products[0].Id,
            QuoteId = q.Id,
            PricebookEntryId = pbes[0].Id,
            UnitPrice = pbes[0].UnitPrice,
            Quantity=1,
            Capex__c=100000,
            Annual_Recurring_Charge__c=225000,
            vlocity_cmt__OneTimeCharge__c=220000,
            ARTL_ARCFloorRate__c=50000,
            ARTL_NRCFloorRate__c=50000
        );
        lstQli.add(qli);
        QuoteLineItem qli2 = new QuoteLineItem(
            Product2Id = products[1].Id,
            QuoteId = q.Id,
            PricebookEntryId = pbes[1].Id,
            UnitPrice = pbes[1].UnitPrice,
            Quantity=1,
            Capex__c=100000,
            Annual_Recurring_Charge__c=225000,
            vlocity_cmt__OneTimeCharge__c=220000,
            ARTL_ARCFloorRate__c=50000,
            ARTL_NRCFloorRate__c=50000
        );
        lstQli.add(qli2);
        insert lstQli;
        
        
        OrderItem[] ois = new OrderItem[2];
        ois[0] = new OrderItem(vlocity_cmt__lineNumber__c = '0001',Product2Id = products[0].Id, OrderId = order.id, pricebookEntryId = pbes[0].id, quantity = 1, vlocity_cmt__AssetReferenceId__c = '201',
                               unitPrice = 1, vlocity_cmt__provisioningStatus__c = 'New', 
                               vlocity_cmt__JSONAttribute__c = '', vlocity_cmt__PricingLogData__c = '' ,
                               vlocity_cmt__Action__c= 'Add',ARTL_QuoteLineItemId__c = lstQli[0].Id);
        ois[1] = new OrderItem(vlocity_cmt__lineNumber__c = '0002',Product2Id = products[1].Id, OrderId = order.id, pricebookEntryId = pbes[1].id, quantity = 1, vlocity_cmt__AssetReferenceId__c = '202',
                                unitPrice = 1, vlocity_cmt__provisioningStatus__c = 'New', vlocity_cmt__JSONAttribute__c = '', 
                               vlocity_cmt__PricingLogData__c ='',ARTL_QuoteLineItemId__c = lstQli[1].Id);            
       
        insert ois;
       
       
    }
    @isTest static void CreateTaskFromFlowTest(){
        Order order = [Select Id FROm Order limit 1];
        
        Task newobjtask = new Task();
        newobjtask.Subject = 'LOC to customer';
        newobjtask.ARTL_TaskType__c = 'LOC to customer';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask.Status = 'Open';
        newobjtask.WhatId = order.Id;
        newobjtask.OwnerId = Userinfo.getUserId();
        insert newobjtask;
        
        List<ARTL_TaskCreationController.FlowInput> lstinput = new List<ARTL_TaskCreationController.FlowInput>();
        ARTL_TaskCreationController.FlowInput input = new ARTL_TaskCreationController.FlowInput();
        input.recordId = newobjtask.Id;
        lstinput.add(input);
        
        ARTL_TaskCreationController.CreateTaskFromFlow(lstinput);
    }
    @isTest static void CreateTaskFromFlowTest2(){
        Order order = [Select Id FROm Order limit 1];
        Task[] lasttask = new Task[2];
        Task newobjtask = new Task();
        newobjtask.Subject = 'LOC validation';
        newobjtask.ARTL_TaskType__c = 'LOC validation';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask.Status = 'Rejected';
        newobjtask.WhatId = order.Id;
        newobjtask.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask);
        
        Task newobjtask2 = new Task();
        newobjtask2.Subject = 'PM upload LOC';
        newobjtask2.ARTL_TaskType__c = 'PM upload LOC';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask2.Status = 'Rejected';
        newobjtask2.WhatId = order.Id;
        newobjtask2.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask2);
        
        insert newobjtask;
        
        List<ARTL_TaskCreationController.FlowInput> lstinput = new List<ARTL_TaskCreationController.FlowInput>();
        ARTL_TaskCreationController.FlowInput input = new ARTL_TaskCreationController.FlowInput();
        input.recordId = newobjtask.Id;
        lstinput.add(input);
        
        ARTL_TaskCreationController.CreateTaskFromFlow(lstinput);
    }
    
    @isTest static void CreateTaskFromFlowTest3(){
        Order order = [Select Id FROm Order limit 1];
        Task[] lasttask = new Task[2];
        Task newobjtask = new Task();
        newobjtask.Subject = 'IP Port Shut';
        newobjtask.ARTL_TaskType__c = 'IP Port Shut';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask.Status = 'Rejected';
        newobjtask.WhatId = order.Id;
        newobjtask.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask);
        
        Task newobjtask2 = new Task();
        newobjtask2.Subject = 'PM approval for LOC';
        newobjtask2.ARTL_TaskType__c = 'PM approval for LOC';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask2.Status = 'Rejected';
        newobjtask2.WhatId = order.Id;
        newobjtask2.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask2);
        
        insert newobjtask;
        
        List<ARTL_TaskCreationController.FlowInput> lstinput = new List<ARTL_TaskCreationController.FlowInput>();
        ARTL_TaskCreationController.FlowInput input = new ARTL_TaskCreationController.FlowInput();
        input.recordId = newobjtask.Id;
        lstinput.add(input);
        
        ARTL_TaskCreationController.CreateTaskFromFlow(lstinput);
    }
    @isTest static void CreateTaskFromFlowTest4(){
        Order order = [Select Id FROm Order limit 1];
        Task[] lasttask = new Task[2];
        Task newobjtask = new Task();
        newobjtask.Subject = 'IP Port Shut';
        newobjtask.ARTL_TaskType__c = 'IP Port Shut';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask.Status = 'Accepted';
        newobjtask.WhatId = order.Id;
        newobjtask.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask);
        
        Task newobjtask2 = new Task();
        newobjtask2.Subject = 'PM approval for LOC';
        newobjtask2.ARTL_TaskType__c = 'PM approval for LOC';
        //newobjtask.Quote_Line_Item__c = extrec.Quote_Line_Item__c;
        newobjtask2.Status = 'Open';
        newobjtask2.WhatId = order.Id;
        newobjtask2.OwnerId = Userinfo.getUserId();
        lasttask.add(newobjtask2);
        
        insert newobjtask;
        
        List<ARTL_TaskCreationController.FlowInput> lstinput = new List<ARTL_TaskCreationController.FlowInput>();
        ARTL_TaskCreationController.FlowInput input = new ARTL_TaskCreationController.FlowInput();
        input.recordId = newobjtask.Id;
        lstinput.add(input);
        
        ARTL_TaskCreationController.CreateTaskFromFlow(lstinput);
    }
}