force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QuoteLineItemId__c</fullName>
    <label>QuoteLineItemId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__Action__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Action__c</fullName>
    <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Disconnect</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Suspend</fullName>
            </value>
            <value>
                <fullName>Resume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/PM_User_Matrix__c.object-meta.xml
<CustomObject>
    <label>PM User Matrix</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM User Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_User_Matrix__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PM User Matrix</relationshipLabel>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CCE__c.field-meta.xml
<CustomField>
    <fullName>CCE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
            <value>
                <fullName>EMERGING</fullName>
            </value>
            <value>
                <fullName>GUJ</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>MPCG</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>NESA</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>UPU</fullName>
            </value>
            <value>
                <fullName>WBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CPH__c.field-meta.xml
<CustomField>
    <fullName>CPH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPH</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM User</description>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/TL__c.field-meta.xml
<CustomField>
    <fullName>TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM&apos;s TL</description>
    <label>TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__JSONAttribute__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__JSONAttribute__c</fullName>
    <description>JSON body containing Vlocity Attribute value data.</description>
    <label>JSONAttribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__PricingLogData__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PricingLogData__c</fullName>
    <description>Detailed pricing log information for this item stored as a JSON structure. The JSON records the detailed prices, adjustments and interim calculations which result in the price to the customer.</description>
    <label>Pricing Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/XLI_Technical_Attribute__c.object-meta.xml
<CustomObject>
    <label>XLI Technical Attribute</label>
    <nameField>
        <displayFormat>XLI-{000000}</displayFormat>
        <label>XLI Technical Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>XLI Technical Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>XLI Technical Attributes</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Technical_Attribute__c</fullName>
    <description>Same as vlocity_cmt__AttributeSelectedValues__c</description>
    <label>Technical Attribute</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Attribute_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Technical_Attribute_Metadata__c</fullName>
    <label>Technical Attribute Metadata</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/XLI_Technical_Attribute__c/fields/Technical_Product__c.field-meta.xml
<CustomField>
    <fullName>Technical_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>XLI Technical Attributes</relationshipLabel>
    <relationshipName>XLI_Technical_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderItemTriggerTest.cls
@isTest
public class OrderItemTriggerTest {
	@testSetup
   static void dataCreation() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Account acc = new Account(Name = 'Test Account',ARTL_Business_Circle_Region__c='NCR',BillingCity = 'Panchkula',
                                  BillingCountry = 'Haryana',BillingPostalCode = '134109',BillingState = 'India',BillingStreet = 'Panchkula',
                                  ARTL_Category__c = 'A',
                                  RecordTypeId = recordTypeId, ARTL_Customer_Segment__c ='AB', ARTL_Vertical_Segment__c ='BFI',
                                 ARTL_Service_Segment__c ='Bharti');
        insert acc; 

        vlocity_cmt__PriceList__c priceList = new 	vlocity_cmt__PriceList__c();
        priceList.Name ='Pricelist For Test class';
        priceList.vlocity_cmt__Code__c='PricelistForTestclass';
        priceList.vlocity_cmt__Pricebook2Id__c =Test.getStandardPricebookId();
        insert priceList;
		
       PM_User_Matrix__c  userMatrix = new PM_User_Matrix__c();
       userMatrix.Circle__c = 'NCR';
       userMatrix.Business_Account__c = acc.Id;
       userMatrix.CCE__c = Userinfo.getUserId();
       userMatrix.CPH__c = Userinfo.getUserId();
       //userMatrix.PM__c = Userinfo.getUserId();
       userMatrix.TL__c = Userinfo.getUserId();
       insert userMatrix;
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Test Opportunity';
        opp.CloseDate= System.Today();
        opp.StageName='Prospecting';
        opp.Pricebook2Id = Test.getStandardPricebookId();
        insert opp;
        
        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.Name = 'Quote Test';
        q.vlocity_cmt__PriceListId__c=priceList.Id;
        q.Pricebook2Id = Test.getStandardPricebookId();
        q.Status ='Draft';
        insert q;
    }
    @isTest static void generateOSSJClassTest(){
        Account acc = [Select id from Account limit 1];
        List<Product2> products = new List<Product2>();
        
        
        Id pbId = Test.getStandardPricebookId();
        
        products = new Product2[2];
        
        products[0]=new Product2(name='VEPC_PRIMARY_LINK', ProductCode='VEPC_PRIMARY_LINK ',vlocity_cmt__JSONAttribute__c = '');
        
        products[1]=new Product2(name='VEPC_PRIMARY_MPLS_LINK ', ProductCode='VEPC_PRIMARY_MPLS_LINK ', vlocity_cmt__JSONAttribute__c = '');
       
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        
        for (Integer i=0; i<products.size(); i++)
        {
            pbes[i] = new PricebookEntry(product2Id = products[i].id, unitPrice = 10, pricebook2id = pbId, useStandardPrice = false,isActive=true);
        }
        
        insert pbes;
        
        /*PriceBookEntry objPBE = new PriceBookEntry(UnitPrice = 300, PriceBook2Id = Test.getStandardPricebookId(),Product2Id = objProduct.Id, IsActive = true);
    insert objPBE;*/
        
        Quote q1 = [Select id FROM Quote limit 1];
        List<Quote> qList=[select id,name,AccountId,Status,Pricebook2Id from Quote];
        List<Quotelineitem> Listqli = new List<Quotelineitem>();
        for(Quote q:qList){
            Quotelineitem qli1 = new QuoteLineItem(QuoteId = q1.id, PriceBookentryId = pbes[0].id, Quantity = 1, UnitPrice = 1,
                                                   Product2Id=products[0].Id);
       		Listqli.add(qli1); 
        }
        insert Listqli;
        
        
        
        /*List<Quote> qList=[select id,name,AccountId,Status,Pricebook2Id from Quote];
        List<Quotelineitem> Listqli = new List<Quotelineitem>();
        for(Quote qte:qList){
            Quotelineitem qli1 = new QuoteLineItem(QuoteId = qte.id, PriceBookentryId = pbId, Quantity = 1, UnitPrice = 1,
                                                   Product2Id=products[0].Id);
            Listqli.add(qli1); 
        }
        insert Listqli;

        
         XLI_Technical_Attribute__c  techAttr = new XLI_Technical_Attribute__c();
         techAttr.Technical_Product__c = products[1].Id;
         techAttr.Quote_Line_Item__c = Listqli[0].Id;
         techAttr.Technical_Attribute__c = '{"ATT_TIMERS_KEEPALIVE_HOLDTIME":null,"ATT_BGP-REPLACE_AS":null,"ATT_AS_SET":null}';
         techAttr.Technical_Attribute_Metadata__c  = products[0].vlocity_cmt__AttributeMetadata__c;
         techAttr.Technical_Attribute__c = products[0].vlocity_cmt__JSONAttribute__c;
        
        insert techAttr;*/
        
        
        Order order = new Order(AccountId = acc.id, effectiveDate = Date.today(), pricebook2id = pbId, status = 'Draft',QuoteId=q1.Id);
        insert order;
        
        OrderItem[] ois = new OrderItem[2];
        ois[0] = new OrderItem(vlocity_cmt__lineNumber__c = '0001',Product2Id = products[0].Id, OrderId = order.id, pricebookEntryId = pbes[0].id, quantity = 1, vlocity_cmt__AssetReferenceId__c = '201',
                               unitPrice = 1, vlocity_cmt__provisioningStatus__c = 'New', 
                               vlocity_cmt__JSONAttribute__c = '', vlocity_cmt__PricingLogData__c = '' ,
                               vlocity_cmt__Action__c= 'Add',QuoteLineItemId=Listqli[0].Id, ARTL_QuoteLineItemId__c = Listqli[0].Id);
        ois[1] = new OrderItem(vlocity_cmt__lineNumber__c = '0002',Product2Id = products[1].Id, OrderId = order.id, pricebookEntryId = pbes[1].id, quantity = 1, vlocity_cmt__AssetReferenceId__c = '202',
                                unitPrice = 1, vlocity_cmt__provisioningStatus__c = 'New', vlocity_cmt__JSONAttribute__c = '', 
                               vlocity_cmt__PricingLogData__c ='',ARTL_QuoteLineItemId__c = Listqli[0].Id);            
       
        insert ois;
    }

}