force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OutlookEventTriggerHandlerTest.cls
@isTest
public class OutlookEventTriggerHandlerTest {

    @isTest
    static void testOutlookEventTriggerHandler() {
        
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account testAcc = new Account(name = 'Test Accountabc',BillingCity='Gurgaon', ARTL_Category__c='A',RecordTypeId = recordTypeId,
                                     BillingStreet = 'Panchkula',
                                         
                                         BillingState = 'Haryana',
                                         BillingPostalCode = '134109',
                                         BillingCountry = 'India', 
                                         ARTL_IntegrationId__c = 'test',
                                          
                                         ARTL_Customer_Segment__c = 'AB',
                                         ARTL_Service_Segment__c = 'BD',
                                         ARTL_Vertical_Segment__c = 'BFI',
                                         ARTL_Business_Circle_Region__c = 'AP');
        insert testAcc;
        
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = testAcc.Id, Email = 'test.contact@email.com', Phone= '1234567890', Salutation= 'Mr.', ARTL_Designation__c='TestDesgntn', ARTL_Contact_Role__c = 'COO', Country_Code__c = '91');
        insert testContact;
        
		Lead testLead = new Lead(FirstName = 'Test', LastName = 'Contact', Email = 'test.lead@email.com', Company='TEST',Salutation= 'Mr.',Lead_Action_Remarks__c='Lead creation');
        insert testLead;

        Lead testLeadName = new Lead(FirstName = 'Testing', LastName = 'Lead', Email = 'test.leads@email.com', Company='TEST1',Salutation= 'Mr.',Lead_Action_Remarks__c='Lead creation');
        insert testLeadName;
        
        Id p = [select id from profile where name='System Administrator'].id;

        User testUser = new User(FirstName = 'Test', LastName = 'User', Email = 'test.user@email.com', Username='test7864er@user.com',Alias = 'tuser', TimeZoneSidKey='Asia/Kolkata',
                                  ProfileId = p, LocaleSidKey = 'en_IN', LanguageLocaleKey  = 'en_US', EmailEncodingKey='UTF-8');
        insert testUser;
        
        Event testEvent = new Event(
            Subject = 'Test Event',
            StartDateTime = DateTime.now(),
            EndDateTime = DateTime.now().addHours(1),
            MS_Teams_Meeting__c = true,
            whoid= testLeadName.id,
            ARTL_Agenda__c='Test',
            CurrencyIsoCode='INR',
            External_Contacts__c='who@yah.com'
        );
        insert testEvent;

        EventRelation testEventRelation = new EventRelation(
            EventId = testEvent.Id,
            RelationId = testContact.Id
        );
        insert testEventRelation;
        EventRelation testEventRelation1 = new EventRelation(
            EventId = testEvent.Id,
            RelationId = testLead.Id
        );
        insert testEventRelation1;
        EventRelation testEventRelation2 = new EventRelation(
            EventId = testEvent.Id,
            RelationId = testUser.Id
        );
        insert testEventRelation2;
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, '{"mockResponse": "success"}'));
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(400, '{"error": "bad request"}'));


        Test.startTest();
        OutlookEventTriggerHandler.handleAfterInsert(new List<Event>{testEvent});
        Test.stopTest();
        //Event updatedEvent = [SELECT Id, vlocity_cmt__EventStatus__c, System_Error__c FROM Event WHERE Id = :testEvent.Id];
       // System.assertEquals('Scheduling', updatedEvent.vlocity_cmt__EventStatus__c, 'Event status should be "Scheduling" after successful callout');
        
        Event erroredEvent = [SELECT Id, vlocity_cmt__EventStatus__c, System_Error__c FROM Event WHERE Id = :testEvent.Id];
        System.assertEquals('Error', erroredEvent.vlocity_cmt__EventStatus__c, 'Event status should be "Error" after callout error');
        System.assert(erroredEvent.System_Error__c.contains('400'), ' Should contain HTTP status code in System error');

    }
    
}