force-app/main/default/objects/Account/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/ARTL_Bulk_Upload_Staging__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_Bulk_Upload_Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/ARTL_Bulk_Upload_Iteration__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bulk_Upload_Iteration__c</fullName>
    <label>ARTL Bulk Upload Iteration</label>
    <referenceTo>ARTL_Bulk_Upload_Iteration__c</referenceTo>
    <relationshipLabel>ARTL Bulk Upload Stagings</relationshipLabel>
    <relationshipName>ARTL_Bulk_Upload_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_Applicable__c</fullName>
    <label>GST Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_NBA_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NBA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NBA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Standard_Reason__c</fullName>
    <label>Standard Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_GST_Applicable__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>UIN</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Non-SEZ</fullName>
            </value>
            <value>
                <fullName>Applied For</fullName>
            </value>
            <value>
                <fullName>SEZ with taxes</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- FTWZ</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- Export</fullName>
            </value>
            <value>
                <fullName>Non Taxable as transactions within same Company</fullName>
            </value>
            <value>
                <fullName>Airtel- Foreign Legal Entity</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Exempt-Trust/Entities 12AA</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- SEZ</fullName>
            </value>
            <value>
                <fullName>J&amp;K delivery - Out of GST Preview</fullName>
            </value>
            <value>
                <fullName>Exempt Supply - Trust/Entities 12AA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_BCPDCPBulkUpdateBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public with sharing class ARTL_BCPDCPBulkUpdateBatchTest {
    
    @testSetup
    public static void testData(){
        System.debug('DEBUGG testData ');
        try{
            List<String> conRoleList = new List<String>{'Billing Contact', 'Delivery Contact'};

            List<Account> accRecords = ARTL_TestDataFactory.createAccount('Billing Aggregator', true, 1);

            List<Contact> conRecords = ARTL_TestDataFactory.createContact('BCP/DCP Contact', accRecords[0].Id, false, 1);
            for (Contact con : conRecords) {
                con.ARTL_Contact_Role__c = conRoleList[0];
                con.Salutation = 'Mr.';
            }
            insert conRecords;
            
            vlocity_cmt__Premises__c premiseRecord = new vlocity_cmt__Premises__c(Name = 'test', 
                                                                                vlocity_cmt__StreetAddress__c = 'Panchkula',
                                                                                vlocity_cmt__City__c = 'Panchkula',
                                                                                vlocity_cmt__State__c = 'Haryana',
                                                                                vlocity_cmt__PostalCode__c = '134109',
                                                                                vlocity_cmt__Country__c = 'India');
            insert premiseRecord;
            
            ContactPremiseRelation__c contactPremiseRelationRecord = new ContactPremiseRelation__c(Contact__c = conRecords[0].Id, 
                                                                                                Premises__c = premiseRecord.Id,
                                                                                                //ARTL_NBA_Account__c = nbaAccount.Id,
                                                                                                ARTL_GST_Applicable__c = 'No',
                                                                                                ARTL_Standard_Reason__c = 'Others',
                                                                                                Role__c = 'BCP');
            insert contactPremiseRelationRecord;
            System.debug('Finish testData ');

            ARTL_Bulk_Upload_Iteration__c iterationRecNew = new ARTL_Bulk_Upload_Iteration__c( Name = 'ARTL_BCPDCPBulkUpdateBatch' );
            Database.insert(iterationRecNew);

            ARTL_Bulk_Upload_Staging__c stagingRecNew = new ARTL_Bulk_Upload_Staging__c(Name = 'Test Staging Rec new', ARTL_Bulk_Upload_Iteration__c = iterationRecNew.Id, Record_Id__c = String.ValueOf(contactPremiseRelationRecord.Id), First_Name__c = 'Test class');
            Database.insert(stagingRecNew);

        }
        catch(Exception e){
            System.debug('ss e.msg()=' + e.getMessage());
            System.debug('e.cause=' + e.getCause());
            System.debug('e.getLineNumber=' + e.getLineNumber());
            System.debug('e.getStackTraceString=' + e.getStackTraceString());
            System.debug('e.getTypeName=' + e.getTypeName());
        }
    }
    
    @isTest
    public static void test_getBcpDcpByAccId(){
        List<ARTL_Bulk_Upload_Iteration__c> itrRecords = [Select Id From ARTL_Bulk_Upload_Iteration__c];
        System.assert(!itrRecords.isEmpty(), 'No Iteration record found');
        Id batchJobId = Database.executeBatch(new ARTL_BCPDCPBulkUpdateBatch(itrRecords[0].Id), 200); 
    }
}