force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/LOC.recordType-meta.xml
<RecordType>
    <fullName>LOC</fullName>
    <active>true</active>
    <label>LOC</label>
</RecordType>

force-app/main/default/classes/ARTL_TasksBulkUploadCtrlTest.cls
/******************************************************************************************************
* @Author       : bijaya.dutta@salesforce.com
* @Company      : Salesforce
* @Date         : 30-Jan-2024
* @Description  : Test class for ARTL_TasksBulkUploadCtrl 
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect        Developer             Date             Comment
* SFDC-3180                Bijaya Dutta        30-Jan-2024      Initial Dev
*******************************************************************************************************/
@isTest
public class ARTL_TasksBulkUploadCtrlTest {
	@testSetup 
    static void setup() {
        Account acc = new Account(Name = 'Test Account',billingCity='pune',billingState = 'Maharastra', ARTL_Legal_Entity__c = 'NXTRA DATA LIMITED',artl_customer_segment__c = 'AB',
                                  artl_business_circle_region__c = 'NCR' , artl_vertical_segment__c= 'BFI' );
        insert acc;
        Task newobjtask1 = new Task(Subject = 'PM approval task',Status = 'Completed',OwnerId =Userinfo.getUserId());
        insert newobjtask1;
        
        Task newobjtask2 = new Task(Subject = 'LOC to customer',Status = 'Open',OwnerId =Userinfo.getUserId());
        insert newobjtask2;
    }
    @isTest
    public static void testMethods() {
        List<Task> tasks = [SELECT Id, Status FROM Task];

        List<String> taskIds = new List<String>();
        List<String> emptyIds = new List<String>();
        List<Object> objList = new List<Object>();
        List<Object> emptyobjList = new List<Object>();

        for (Task task : tasks) {
            String taskId15Char = String.valueOf(task.Id).substring(0, 15);
            taskIds.add(taskId15Char);
            objList.add(new Map<String, Object>{'TaskId' => taskId15Char, 'Status' => task.Status});
        }

        //Test the method
        Test.startTest();
        String result = ARTL_TasksBulkUploadCtrl.createTaskRecordsOnBulkCartUpdate(taskIds, objList);
        String nullResult = ARTL_TasksBulkUploadCtrl.createTaskRecordsOnBulkCartUpdate(null, null);
        String emptyResult = ARTL_TasksBulkUploadCtrl.createTaskRecordsOnBulkCartUpdate(emptyIds, emptyobjList);
        Test.stopTest();
        
    }
}