force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/ARTL_Bulk_Upload_Iteration__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Iteration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL Bulk Upload Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Iterations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Iteration__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Quote Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/ARTL_Bulk_Upload_Staging__c.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Upload Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_Bulk_Upload_Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL Bulk Upload Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/ARTL_Bulk_Upload_Iteration__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Bulk_Upload_Iteration__c</fullName>
    <label>ARTL Bulk Upload Iteration</label>
    <referenceTo>ARTL_Bulk_Upload_Iteration__c</referenceTo>
    <relationshipLabel>ARTL Bulk Upload Stagings</relationshipLabel>
    <relationshipName>ARTL_Bulk_Upload_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Upload_Staging__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_AssetControllerTest.cls
@isTest
public with sharing class ARTL_AssetControllerTest {
    public ARTL_AssetControllerTest() {

    }
    @TestSetup
    static void setup(){
        Account acc = new Account(Name = 'Test Account',billingCity='pune',billingState = 'Maharastra', ARTL_Legal_Entity__c = 'NXTRA DATA LIMITED',artl_customer_segment__c = 'AB',
        artl_business_circle_region__c = 'NCR' , artl_vertical_segment__c= 'BFI' );
        Database.insert(acc);

        Opportunity oppRecNew = new Opportunity(Name = 'Opp Record', StageName = 'Initial', CloseDate = Date.Today(), Amount = 1200000, AccountId = acc.Id);
        Database.insert(oppRecNew);

        Quote quoteRecNew = new Quote(Name = 'Quote Record', OpportunityId = oppRecNew.Id);
        Database.insert(quoteRecNew);

        ARTL_Bulk_Upload_Iteration__c iterationRecNew = new ARTL_Bulk_Upload_Iteration__c( Name = 'Test Iteration Record New Opp Quote', Opportunity_Name__c = 'Test Opp Record', Opportunity_Stage__c = 'Initial',
        Opportunity_Close_Date__c = Date.Today(), Amount__c = 1200000, Quote_Name__c = 'Test Quote Record');
        Database.insert(iterationRecNew);

        ARTL_Bulk_Upload_Iteration__c iterationRecExisting = new ARTL_Bulk_Upload_Iteration__c( Name = 'Test Iteration Record Existing Opp Quote',
        Opportunity_Id__c = oppRecNew.Id, Quote_Id__c = quoteRecNew.Id);
        Database.insert(iterationRecExisting);

        Asset assetRec = new Asset(Name = 'Asset Rec Test', AccountId = acc.Id, ARTL_LSI__c = 12345678 );
        Database.insert(assetRec);
        Asset assetRec2 = new Asset(Name = 'Asset Rec Test 2', AccountId = acc.Id, ARTL_LSI__c = 12345679 );
        Database.insert(assetRec2);

        ARTL_Bulk_Upload_Staging__c stagingRecNew = new ARTL_Bulk_Upload_Staging__c(Name = 'Test Staging Rec new', ARTL_Bulk_Upload_Iteration__c = iterationRecNew.Id, Record_Id__c = String.ValueOf(assetRec.ARTL_LSI__c));
        Database.insert(stagingRecNew);

        ARTL_Bulk_Upload_Staging__c stagingRecExisting = new ARTL_Bulk_Upload_Staging__c(Name = 'Test Staging Rec existing', ARTL_Bulk_Upload_Iteration__c = iterationRecExisting.Id, Record_Id__c = String.ValueOf(assetRec.ARTL_LSI__c));
        Database.insert(stagingRecExisting);
  ARTL_Bulk_Upload_Staging__c stagingRecExisting2 = new ARTL_Bulk_Upload_Staging__c(Name = 'Test Staging Rec again', ARTL_Bulk_Upload_Iteration__c = iterationRecExisting.Id, Errors__c ='Uploading an mismatch asset', Record_Id__c = String.ValueOf(assetRec.ARTL_LSI__c));
        Database.insert(stagingRecExisting2);
    }

    @isTest
    public static void getAssetRecordsFromIterationIdNewTest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        List<ARTL_Bulk_Upload_Iteration__c> iterationRecNewList = [SELECT Id FROM ARTL_Bulk_Upload_Iteration__c WHERE Name = 'Test Iteration Record New Opp Quote' LIMIT 1];
        List<Account> accountList = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        inputs.put('iterationId',iterationRecNewList.get(0));
        inputs.put('contextId',accountList.get(0));
        Test.startTest();
        assetController.invokeMethod('BulkUploadValidationAndUpdation',inputs,output,options);
        Test.stopTest();
    }

    /* @isTest
    public static void getAssetRecordsFromIterationIdExistingTest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        List<ARTL_Bulk_Upload_Iteration__c> iterationRecNewList = [SELECT Id FROM ARTL_Bulk_Upload_Iteration__c WHERE Name = 'Test Iteration Record Existing Opp Quote' LIMIT 1];
        List<Account> accountList = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        inputs.put('iterationId',iterationRecNewList.get(0));
        inputs.put('contextId',accountList.get(0));
        Test.startTest();
        assetController.invokeMethod('BulkUploadValidationAndUpdation',inputs,output,options);
        Test.stopTest();
    }*/


    @isTest
    public static void createQuoteAndOpportunityExistingTest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        List<ARTL_Bulk_Upload_Iteration__c> iterationRecNewList = [SELECT Id, Opportunity_Name__c, Opportunity_Stage__c,Opportunity_Close_Date__c, 
        Quote_Name__c, Quote_Id__c,Opportunity_Id__c, Amount__c FROM ARTL_Bulk_Upload_Iteration__c WHERE Name = 'Test Iteration Record Existing Opp Quote' LIMIT 1];
        List<ARTL_Bulk_Upload_Staging__c> StagingValidatedList = [SELECT Id, Errors__c, ARTL_Bulk_Upload_Iteration__c, Record_Id__c FROM ARTL_Bulk_Upload_Staging__c WHERE Name = 'Test Staging Rec new' LIMIT 1];
        List<Asset> assetList = [SELECT Id, AccountId ,RootAssetId, vlocity_cmt__RootItemId__c, vlocity_cmt__ParentItemId__c, ARTL_LSI__c,
        vlocity_cmt__AssetReferenceId__c,  vlocity_cmt__LineNumber__c FROM Asset WHERE Name = 'Asset Rec Test' LIMIT 1];
        List<Id> rootAssetIds = new List<Id>();
        for(Asset assetRec : assetList) {
            rootAssetIds.add(assetRec.Id);
        }
        List<Account> accountList = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        inputs.put('accountId',accountList.get(0).Id);
        Test.startTest();
        ARTL_AssetController.createQuoteAndOpportunity(StagingValidatedList, iterationRecNewList.get(0), inputs, rootAssetIds);
        Test.stopTest();
    }

    @isTest
    public static void createQuoteAndOpportunityNewTest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        List<ARTL_Bulk_Upload_Iteration__c> iterationRecNewList = [SELECT Id, Opportunity_Name__c, Opportunity_Stage__c,Opportunity_Close_Date__c, 
        Quote_Name__c, Quote_Id__c,Opportunity_Id__c, Amount__c FROM ARTL_Bulk_Upload_Iteration__c WHERE Name = 'Test Iteration Record New Opp Quote' LIMIT 1];
        List<ARTL_Bulk_Upload_Staging__c> StagingValidatedList = [SELECT Id, Errors__c, ARTL_Bulk_Upload_Iteration__c, Record_Id__c FROM ARTL_Bulk_Upload_Staging__c WHERE Name = 'Test Staging Rec new' LIMIT 1];
        List<Asset> assetList = [SELECT Id, AccountId ,RootAssetId, vlocity_cmt__RootItemId__c, vlocity_cmt__ParentItemId__c, ARTL_LSI__c,
        vlocity_cmt__AssetReferenceId__c,  vlocity_cmt__LineNumber__c FROM Asset WHERE Name = 'Asset Rec Test' LIMIT 1];
        List<Id> rootAssetIds = new List<Id>();
        for(Asset assetRec : assetList) {
            rootAssetIds.add(assetRec.Id);
        }
        List<Account> accountList = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        inputs.put('accountId',accountList.get(0).Id);
        Test.startTest();
        ARTL_AssetController.createQuoteAndOpportunity(StagingValidatedList, iterationRecNewList.get(0), inputs, rootAssetIds);
        Test.stopTest();
    }
@isTest
    public static void InvokeAssetToQuoteAPITest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        Test.startTest();
        assetController.invokeMethod('invokeAssettoQuoteAPI',inputs,output,options);
        Test.stopTest();
    }
   @isTest
    public static void sendNotificationTest () {
        ARTL_AssetController assetController = new ARTL_AssetController();
        Map<String, Object> inputs = new Map<String, Object>();
        Map<String, Object> output = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        Test.startTest();
        assetController.invokeMethod('sendNotification',inputs,output,options);
        Test.stopTest();
    }
}