force-app/main/default/objects/Account/fields/ARTL_Category__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Customer_Segment__c</fullName>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>CHANNEL</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>NDL</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>ARTL_IntegrationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IntegrationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Service_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Service_Segment__c</fullName>
    <label>Service Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Bharti</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise Platinum</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
            </value>
            <value>
                <fullName>Transformation</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Top Account</fullName>
            </value>
            <value>
                <fullName>Growth Account</fullName>
            </value>
            <value>
                <fullName>GB Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>AB channels</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ARTL_Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_Customer_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BFI</fullName>
            </value>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
            </value>
            <value>
                <fullName>Calling Card Operator</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Digital Media</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Global Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Govt/PSU</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>ISP</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT/ITES</fullName>
            </value>
            <value>
                <fullName>IT &amp; Telecom</fullName>
            </value>
            <value>
                <fullName>ITES</fullName>
            </value>
            <value>
                <fullName>M&amp;D</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Media &amp; Services</fullName>
            </value>
            <value>
                <fullName>Mobile Operator</fullName>
            </value>
            <value>
                <fullName>MVNOs</fullName>
            </value>
            <value>
                <fullName>NDL Channels</fullName>
            </value>
            <value>
                <fullName>Next Gen</fullName>
            </value>
            <value>
                <fullName>OSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>OTT/CDN</fullName>
            </value>
            <value>
                <fullName>Satellite Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/ARTL_DataMigrationStaging__c.object-meta.xml
<CustomObject>
    <label>ARTL_DataMigrationStaging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_DataMigrationStaging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ARTL_DataMigrationStagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Alternate_Email_Addr__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Addr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternate Email Addr</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Contact_Cell_Phone__c.field-meta.xml
<CustomField>
    <fullName>Contact_Cell_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Cell Phone #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email Address</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Last Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Contact_Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Middle_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Middle Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Contact_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Contact_Parent_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Parent Account #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Fax_Phone__c.field-meta.xml
<CustomField>
    <fullName>Fax_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fax Phone #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Responsibility__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Responsibility</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_DataMigrationStaging__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Party</fullName>
            </value>
            <value>
                <fullName>Billing - BA</fullName>
            </value>
            <value>
                <fullName>NBA</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_DataMigrationContactTest.cls
@isTest
private class ARTL_DataMigrationContactTest {

    @isTest
    static void testBatchExecution() {
        Map<Id, String> errorMap = new Map<Id, String>();
        ARTL_Pincode__c pin = new ARTL_Pincode__c();
        pin.name='523356';
        insert pin;
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account testAcc = new Account(name = 'Test Accountabc', 
                                      RecordTypeId = recordTypeId,
                                      BillingCity = 'Panchkula',
                                      BillingCountry = 'Haryana',
                                      BillingPostalCode = '134109',
                                      BillingState = 'India',
                                      BillingStreet = 'Panchkula', 
                                      ARTL_IntegrationId__c = 'test', 
                                      ARTL_Category__c = 'A', 
                                      ARTL_Customer_Segment__c = 'AB',
                                      ARTL_Service_Segment__c = 'BD',
                                      ARTL_Vertical_Segment__c = 'BFI',
                                      ARTL_Business_Circle_Region__c = 'AP',
                                      ARTL_PAN__c = 'ABCDE1234F');
        insert testAcc;
        contact con = new contact();
		con.lastname= 'aarrjjunnaa';
		con.firstname='naggg';
		con.email='arjun1234@gmail.com';
		con.ARTL_Contact_Role__c='CEO';
		con.ARTL_Designation__c='randomm';
		con.phone='1234577897';
        con.AccountId = testAcc.Id;
        con.Country_Code__c		= '91';
		Database.saveResult result = database.insert(con) ;
		system.debug(con.id);
        errorMap.put(con.id,'contact inserted');
                     // Created test data
        //account Nba = new account();
        String billingAggregatorRecorTypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing Aggregator').getRecordTypeId();
        account nba = new account(name = 'Test Accountabc', 
                                      RecordTypeId = billingAggregatorRecorTypeid,
                                  	AccountNumber='31-123456',
                                  Parentid = testAcc.Id,
                                      BillingCity = 'Panchkula',
                                      BillingCountry = 'Haryana',
                                      BillingPostalCode = '134109',
                                      BillingState = 'India',
                                      BillingStreet = 'Panchkula', 
                                      ARTL_IntegrationId__c = 'test', 
                                      ARTL_Category__c = 'A', 
                                      ARTL_Customer_Segment__c = 'AB',
                                      ARTL_Service_Segment__c = 'BD',
                                      ARTL_Vertical_Segment__c = 'BFI',
                                      ARTL_Business_Circle_Region__c = 'AP',
                                      ARTL_PAN__c = 'ABCDE1234F');
        //nba.recordTypeid=billingAggregatorRecorTypeid;
        //nba.AccountNumber='31-123456';
        //nba.Parentid = testAcc.Id;
        insert nba;
        String businessRecorTypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        account Ba = new account();
        Ba.RecordTypeId=businessRecorTypeid;
        Ba.AccountNumber='11-123456';
        //sert Ba;
        List<ARTL_DataMigrationStaging__c> testData = new List<ARTL_DataMigrationStaging__c>();
        ARTL_DataMigrationStaging__c stagingRecord = new ARTL_DataMigrationStaging__c();
        stagingRecord.type__c='Contact';
        stagingRecord.Contact_Last_Name__c='testcon';
        stagingRecord.Responsibility__c='Testres';
        stagingRecord.designation__c='BCP';
        stagingRecord.Alternate_Email_Addr__c=''; 
        stagingRecord.Contact_Cell_Phone__c='';
        stagingRecord.Contact_Email_Address__c='';
        stagingRecord.Fax_Phone__c='';
        stagingRecord.Contact_Middle_Name__c='';
      	stagingRecord.Contact_Parent_Account__c=nba.id;
      	stagingRecord.NBA_Account__c=Nba.id;
        stagingRecord.Contact_Number__c='1-123456';
        stagingRecord.Contact_Phn_Code__c='91';
        stagingRecord.Responsibility__c='CEO';
        stagingRecord.Designation__c='BCP';
        stagingRecord.Active__c ='true';
        
        testData.add(stagingRecord);
        

        // Insert test data
        insert testData;

        // Start the batch
        Test.startTest();
        ARTL_DataMigrationContact batchInstance = new ARTL_DataMigrationContact();
        Database.executeBatch(batchInstance);
        Test.stopTest();

        // Perform assertions based on the expected behavior of your batch logic
        // Verify that the data has been processed as expected

        // Example assertion:
        System.assertEquals(0, batchInstance.errorMap.size(), 'No errors should be present');
    }
}