force-app/main/default/objects/Account/fields/ARTL_PAN__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PAN__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__CustomerClass__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__CustomerClass__c</fullName>
    <description>Grouping of accounts by attributes and used to drive accounting processes, business logic, and validation rules (i.e. residential, SMB, C&amp;I, etc.)</description>
    <label>Customer Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C&amp;I</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>EGB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_VANTriggerTest.cls
@isTest
public class ARTL_VANTriggerTest {
 @isTest
    static void testAfterUpdateTrigger1() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data 1
        Account testAccount1 = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount1.vlocity_cmt__Status__c = 'Unapproved';
        testAccount1.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount1.ARTL_PAN__c = 'AAAAA1234A';
        insert testAccount1;
       
        Test.startTest();
		testAccount1.vlocity_cmt__Status__c = 'Active';
        update testAccount1;
        Test.stopTest();
        
    }
     @isTest
    static void testAfterUpdateTrigger2() {
         Id BusinessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();

        // Create test data 1
        Account testAccount1 = new Account(Name = 'Test Account', recordTypeId=BusinessRecordTypeId);
		testAccount1.vlocity_cmt__Status__c = 'Active';
        testAccount1.vlocity_cmt__CustomerClass__c = 'EGB';
        testAccount1.ARTL_PAN__c = 'AAAAA1234A';
        insert testAccount1;
       
        Test.startTest();
		testAccount1.ARTL_PAN__c = 'ABAAA1234A';
        update testAccount1;
        Test.stopTest();
        
    }
}