force-app/main/default/objects/Account/fields/Bill_Franchise_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Bill_Franchise_Tax_Code__c</fullName>
    <label>Bill Franchise Tax Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Level__c.field-meta.xml
<CustomField>
    <fullName>Billing_Level__c</fullName>
    <label>Billing Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LSI Level</fullName>
            </value>
            <value>
                <fullName>Account Level</fullName>
            </value>
            <value>
                <fullName>PO Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/ARTL_Billing_Staging__c.object-meta.xml
<CustomObject>
    <label>Billing Staging</label>
    <nameField>
        <label>Billing Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/ARTL_PO_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Group_Id__c</fullName>
    <label>PO Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_Email__c.field-meta.xml
<CustomField>
    <fullName>BCP_Email__c</fullName>
    <label>BCP Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_First_Name__c.field-meta.xml
<CustomField>
    <fullName>BCP_First_Name__c</fullName>
    <label>BCP First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_Id__c.field-meta.xml
<CustomField>
    <fullName>BCP_Id__c</fullName>
    <label>BCP Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>BCP_Last_Name__c</fullName>
    <label>BCP Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_Phone__c.field-meta.xml
<CustomField>
    <fullName>BCP_Phone__c</fullName>
    <label>BCP Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Bill_Format__c.field-meta.xml
<CustomField>
    <fullName>Bill_Format__c</fullName>
    <description>Billing format that is being used for this billing account</description>
    <label>Bill Format</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Bill_Franchise_Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Bill_Franchise_Tax_Code__c</fullName>
    <label>Bill Franchise Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Id__c</fullName>
    <label>Billing Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <label>Billing Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <description>Billing Address from PO</description>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_GST_Applicable_for_Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing_GST_Applicable_for_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billing GST Applicable for Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Level__c.field-meta.xml
<CustomField>
    <fullName>Billing_Level__c</fullName>
    <label>Billing Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_PinCode__c.field-meta.xml
<CustomField>
    <fullName>Billing_PinCode__c</fullName>
    <label>Billing PinCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Credit_Period__c.field-meta.xml
<CustomField>
    <fullName>Credit_Period__c</fullName>
    <label>Credit Period</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/DCP_Email__c.field-meta.xml
<CustomField>
    <fullName>DCP_Email__c</fullName>
    <label>DCP Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/DCP_First_Name__c.field-meta.xml
<CustomField>
    <fullName>DCP_First_Name__c</fullName>
    <label>DCP First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/DCP_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>DCP_Last_Name__c</fullName>
    <label>DCP Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/DCP_Phone__c.field-meta.xml
<CustomField>
    <fullName>DCP_Phone__c</fullName>
    <label>DCP Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Delivery_GST__c.field-meta.xml
<CustomField>
    <fullName>Delivery_GST__c</fullName>
    <label>Delivery GST#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/License_Company__c.field-meta.xml
<CustomField>
    <fullName>License_Company__c</fullName>
    <label>License Company</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/NBA_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NBA_Account_Number__c</fullName>
    <label>NBA Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <label>PO#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_End_Date__c</fullName>
    <label>PO End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Group__c.field-meta.xml
<CustomField>
    <fullName>PO_Group__c</fullName>
    <label>PO Group#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Start_Date__c</fullName>
    <label>PO Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing Stagings</relationshipLabel>
    <relationshipName>Billing_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Billing Stagings</relationshipLabel>
    <relationshipName>Billing_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Service_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Id__c</fullName>
    <label>Service Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/StandardReasonforTaxExemption__c.field-meta.xml
<CustomField>
    <fullName>StandardReasonforTaxExemption__c</fullName>
    <label>Standard Reason for Tax Exemption</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Taxation__c.field-meta.xml
<CustomField>
    <fullName>Taxation__c</fullName>
    <label>Taxation</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Usage_Flag__c.field-meta.xml
<CustomField>
    <fullName>Usage_Flag__c</fullName>
    <label>Usage Flag</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/PO_Group__c.field-meta.xml
<CustomField>
    <fullName>PO_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PO Group</label>
    <referenceTo>PO_Group__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO_Group__c/PO_Group__c.object-meta.xml
<CustomObject>
    <label>PO Group</label>
    <nameField>
        <displayFormat>71-8{0000000}</displayFormat>
        <label>PO Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PO_Group__c/fields/ARTL_Legacy_No__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Legacy_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Legacy</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Group__c/fields/ARTL_PO_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Group_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PO Group Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Term__c.field-meta.xml
<CustomField>
    <fullName>PO_Term__c</fullName>
    <label>PO Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Value__c.field-meta.xml
<CustomField>
    <fullName>PO_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PO Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_BACreationPreProcessBatchTest.cls
@isTest
private class ARTL_BACreationPreProcessBatchTest  {

     
    @isTest
    static void testGetOrderRelDetails() {
        
         Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId);
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId);
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId);
        insert accounts;
        
        Product2[] products = new Product2[2];
        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();
        
        for (Integer i=0; i<products.size(); i++){
            pbes[i] = new PricebookEntry(product2Id = products[i].id, 
                                         IsActive = true, 
                                         unitPrice = 10, 
                                         pricebook2id = pbId, 
                                         useStandardPrice = false);
        }
        
        insert pbes;
        
        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, 
                                                                      vlocity_cmt__IsActive__c = true, 
                                                                      vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = accounts[0].id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;
        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
        qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
        
        PO_Group__c poGroup = new PO_Group__c();
        poGroup.ARTL_PO_Group_Number__c = '123';
        insert poGroup;
        
        PO_Group__c poGroup1 = new PO_Group__c();
        poGroup1.ARTL_PO_Group_Number__c = '1234';
        insert poGroup1;
        
        ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
        PurchaseOrder.ARTL_PO_Number__c = '111111';
        PurchaseOrder.PO_Group__c = poGroup.id;
        insert PurchaseOrder;
        
        QuoteLineItem  quoteLine1 = new QuoteLineItem ();
        quoteLine1.UnitPrice = 1;
        quoteLine1.Quantity = 1;
        quoteLine1.Product2Id = products[1].Id;
        quoteLine1.vlocity_cmt__Product2Id__c = products[1].Id;
        quoteLine1.QuoteId =qtest.Id;
        quoteLine1.PricebookEntryId=pbes[0].Id;
        quoteLine1.vlocity_cmt__Action__c='Change';
        quoteLine1.ARTL_Purchase_Order__c = PurchaseOrder.Id;
        quoteLine1.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine1.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        insert quoteLine1;
        
        QuoteLineItem  quoteLine = new QuoteLineItem ();
        quoteLine.UnitPrice = 1;
        quoteLine.Quantity = 1;
        quoteLine.Product2Id = products[0].Id;
        quoteLine.vlocity_cmt__Product2Id__c = products[0].Id;
        quoteLine.QuoteId =qtest.Id;
        quoteLine.PricebookEntryId=pbes[0].Id;
        quoteLine.vlocity_cmt__Action__c='Add';
        quoteLine.ARTL_Purchase_Order__c =null;
        quoteLine.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        
        
        ARTL_Billing_Staging__c stage = new ARTL_Billing_Staging__c();
        stage.Quote__c = qtest.Id;
        stage.Quote_Line_Item__c = quoteLine.Id;
        insert stage;
            List<ARTL_Billing_Staging__c> basaList=[SELECT Id FROM ARTL_Billing_Staging__c];
        for(ARTL_Billing_Staging__c BL : basaList)
        {
            BL.Quote__c = qtest.Id;
        BL.Status__c = 'Success';
            BL.ARTL_PO_Group_Id__c = Null;
             BL.BCP_Last_Name__c = 'Test';
        } 
        
        update basaList;
        system.debug('baselist::' + basaList);
        test.starttest();
            ARTL_BACreationPreProcessBatch testBatch = new ARTL_BACreationPreProcessBatch(new Set<Id>{qtest.Id});

        // Start the batch execution
       ID batchprocessid= Database.executeBatch(testBatch);
        system.debug('batchprocessid::' + batchprocessid);
            Test.stopTest();
    }
    
      @isTest
    static void testGetOrderRelDetails2() {
            
         Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId);
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId);
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId);
        insert accounts;
        
        Product2[] products = new Product2[2];
        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();
        
        for (Integer i=0; i<products.size(); i++){
            pbes[i] = new PricebookEntry(product2Id = products[i].id, 
                                         IsActive = true, 
                                         unitPrice = 10, 
                                         pricebook2id = pbId, 
                                         useStandardPrice = false);
        }
        
        insert pbes;
        
        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, 
                                                                      vlocity_cmt__IsActive__c = true, 
                                                                      vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = accounts[0].id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;
        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
        qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
        
        PO_Group__c poGroup = new PO_Group__c();
        poGroup.ARTL_PO_Group_Number__c = '123';
        insert poGroup;
        
        PO_Group__c poGroup1 = new PO_Group__c();
        poGroup1.ARTL_PO_Group_Number__c = '1234';
        insert poGroup1;
        
        ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
        PurchaseOrder.ARTL_PO_Number__c = '111111';
        PurchaseOrder.PO_Group__c = poGroup.id;
        insert PurchaseOrder;
        
        QuoteLineItem  quoteLine1 = new QuoteLineItem ();
        quoteLine1.UnitPrice = 1;
        quoteLine1.Quantity = 1;
        quoteLine1.Product2Id = products[1].Id;
        quoteLine1.vlocity_cmt__Product2Id__c = products[1].Id;
        quoteLine1.QuoteId =qtest.Id;
        quoteLine1.PricebookEntryId=pbes[0].Id;
        quoteLine1.vlocity_cmt__Action__c='Change';
        quoteLine1.ARTL_Purchase_Order__c = PurchaseOrder.Id;
        quoteLine1.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine1.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        insert quoteLine1;
        
        QuoteLineItem  quoteLine = new QuoteLineItem ();
        quoteLine.UnitPrice = 1;
        quoteLine.Quantity = 1;
        quoteLine.Product2Id = products[0].Id;
        quoteLine.vlocity_cmt__Product2Id__c = products[0].Id;
        quoteLine.QuoteId =qtest.Id;
        quoteLine.PricebookEntryId=pbes[0].Id;
        quoteLine.vlocity_cmt__Action__c='Add';
        quoteLine.ARTL_Purchase_Order__c =null;
        quoteLine.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        PO_Group__c POGrp= new PO_Group__c();
        POGrp.ARTL_PO_Group_Number__c='123456';
        POGrp.ARTL_Legacy_No__c='123456';
        insert POGrp;
        
        
        
        ARTL_Billing_Staging__c stage = new ARTL_Billing_Staging__c();
        stage.Quote__c = qtest.Id;
        stage.Quote_Line_Item__c = quoteLine.Id;
        stage.Shipping_Street__c = 'Test';
        
        insert stage;
            List<ARTL_Billing_Staging__c> basaList=[SELECT Id,Shipping_Street__c FROM ARTL_Billing_Staging__c];
        for(ARTL_Billing_Staging__c BL : basaList)
        {
            BL.Quote__c = qtest.Id;
        BL.Status__c = 'Success';
            BL.ARTL_PO_Group_Id__c = POGrp.id;
            BL.PO__c='TEST';
            BL.Quote_Line_Item__c = quoteLine.id;
            BL.Shipping_Street__c = 'Test';
            BL.BCP_Last_Name__c = 'Test';
            BL.BCP_Id__c =Null;
             BL.DCP_Last_Name__c = 'test';
            BL.DCP_First_Name__c ='first';
            BL.DCP_Phone__c=  '1234567890';
            BL.DCP_Email__c = 'test_12@gmail.com';
            BL.Service_Account_Id__c = accounts[2].Id;
        } 
        
        update basaList;
        system.debug('baselist::' + basaList);
        Test.starttest();
            ARTL_BACreationPreProcessBatch testBatch = new ARTL_BACreationPreProcessBatch(new Set<Id>{qtest.Id});

        // Start the batch execution
       ID batchprocessid= Database.executeBatch(testBatch);
        system.debug('batchprocessid::' + batchprocessid);
            Test.stopTest();
    
    }     
    /* @isTest
    static void testGetOrderRelDetails3() {
        
            
         Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId);
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId);
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId);
        insert accounts;
        
        Product2[] products = new Product2[2];
        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();
        
        for (Integer i=0; i<products.size(); i++){
            pbes[i] = new PricebookEntry(product2Id = products[i].id, 
                                         IsActive = true, 
                                         unitPrice = 10, 
                                         pricebook2id = pbId, 
                                         useStandardPrice = false);
        }
        
        insert pbes;
        
        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, 
                                                                      vlocity_cmt__IsActive__c = true, 
                                                                      vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = accounts[0].id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;
        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
        qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
        
        PO_Group__c poGroup = new PO_Group__c();
        insert poGroup;
        
        PO_Group__c poGroup1 = new PO_Group__c();
        insert poGroup1;
        
        ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
        PurchaseOrder.ARTL_PO_Number__c = '111111';
        PurchaseOrder.PO_Group__c = poGroup.id;
        insert PurchaseOrder;
        
        QuoteLineItem  quoteLine1 = new QuoteLineItem ();
        quoteLine1.UnitPrice = 1;
        quoteLine1.Quantity = 1;
        quoteLine1.Product2Id = products[1].Id;
        quoteLine1.vlocity_cmt__Product2Id__c = products[1].Id;
        quoteLine1.QuoteId =qtest.Id;
        quoteLine1.PricebookEntryId=pbes[0].Id;
        quoteLine1.vlocity_cmt__Action__c='Change';
        quoteLine1.ARTL_Purchase_Order__c = PurchaseOrder.Id;
        quoteLine1.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine1.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        insert quoteLine1;
        
        QuoteLineItem  quoteLine = new QuoteLineItem ();
        quoteLine.UnitPrice = 1;
        quoteLine.Quantity = 1;
        quoteLine.Product2Id = products[0].Id;
        quoteLine.vlocity_cmt__Product2Id__c = products[0].Id;
        quoteLine.QuoteId =qtest.Id;
        quoteLine.PricebookEntryId=pbes[0].Id;
        quoteLine.vlocity_cmt__Action__c='Add';
        quoteLine.ARTL_Purchase_Order__c =null;
        quoteLine.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        
        
        ARTL_Billing_Staging__c stage = new ARTL_Billing_Staging__c();
        stage.Quote__c = qtest.Id;
        stage.Quote_Line_Item__c = quoteLine.Id;
        insert stage;
            
            List<ARTL_Billing_Staging__c> basaList=[SELECT Id FROM ARTL_Billing_Staging__c];
        for(ARTL_Billing_Staging__c BL : basaList)
        {
            BL.Quote__c = qtest.Id;
        BL.Status__c = 'Success';
            BL.ARTL_PO_Group_Id__c = Null;
            BL.Quote_Line_Item__c = quoteLine.id;
            BL.Shipping_Street__c = 'Test';
            BL.BCP_Last_Name__c = 'Test1';
            BL.BCP_First_Name__c = 'First1';
            BL.BCP_Phone__c= '1234567899';
             BL.BCP_Email__c = 'test_123@gmail.com';
            BL.Billing_Account_Id__c = accounts[2].Id;
            BL.BCP_Id__c =Null;
            BL.DCP_Last_Name__c = 'test';
            BL.DCP_First_Name__c ='first';
            BL.DCP_Phone__c=  '1234567890';
            BL.DCP_Email__c = 'test_12@gmail.com';
            BL.Service_Account_Id__c = accounts[2].Id;
            //String uniqueKey = obj.BCP_First_Name__c + obj.BCP_Last_Name__c + obj.BCP_Phone__c + obj.BCP_Email__c;
        } 
        
        update basaList;
        system.debug('baselist::' + basaList);
        test.starttest();
            ARTL_BACreationPreProcessBatchHelper.createDCPContacts(basaList);
        //ARTL_BACreationPreProcessBatchHelper.createBCPContacts(basaList);
        Test.stopTest();
    
    
    }*/
    
     @isTest
    static void testGetOrderRelDetails4() {
        
            
         Account[] accounts =new Account[3];
        Id businessAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id billingAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Billing').getRecordTypeId();
        Id serviceAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        accounts[0] = new Account(Name = 'Test Business Account',RecordTypeId = businessAccountRecordTypeId);
        accounts[1] = new Account(Name = 'Test Billing Account',RecordTypeId  = billingAccountRecordTypeId);
        accounts[2] = new Account(Name = 'Test Service Account',RecordTypeId  = serviceAccountRecordTypeId);
        insert accounts;
        
        Product2[] products = new Product2[2];
        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;
        
        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();
        
        for (Integer i=0; i<products.size(); i++){
            pbes[i] = new PricebookEntry(product2Id = products[i].id, 
                                         IsActive = true, 
                                         unitPrice = 10, 
                                         pricebook2id = pbId, 
                                         useStandardPrice = false);
        }
        
        insert pbes;
        
        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, 
                                                                      vlocity_cmt__IsActive__c = true, 
                                                                      vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = accounts[0].id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;
        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
       //s qtest.AccountId=accounts[0].id;
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
        qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
        
        PO_Group__c poGroup = new PO_Group__c();
        poGroup.ARTL_PO_Group_Number__c = '123';
        insert poGroup;
        
        PO_Group__c poGroup1 = new PO_Group__c();
        poGroup1.ARTL_PO_Group_Number__c = '1234';
        insert poGroup1;
        
        ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
        PurchaseOrder.ARTL_PO_Number__c = '111111';
        PurchaseOrder.PO_Group__c = poGroup.id;
        insert PurchaseOrder;
        
        QuoteLineItem  quoteLine1 = new QuoteLineItem ();
        quoteLine1.UnitPrice = 1;
        quoteLine1.Quantity = 1;
        quoteLine1.Product2Id = products[1].Id;
        quoteLine1.vlocity_cmt__Product2Id__c = products[1].Id;
        quoteLine1.QuoteId =qtest.Id;
        quoteLine1.PricebookEntryId=pbes[0].Id;
        quoteLine1.vlocity_cmt__Action__c='Change';
        quoteLine1.ARTL_Purchase_Order__c = PurchaseOrder.Id;
        quoteLine1.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
        quoteLine1.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        
        insert quoteLine1;
        
        QuoteLineItem  quoteLine = new QuoteLineItem ();
        quoteLine.UnitPrice = 1;
        quoteLine.Quantity = 1;
        quoteLine.Product2Id = products[0].Id;
        quoteLine.vlocity_cmt__Product2Id__c = products[0].Id;
        quoteLine.QuoteId =qtest.Id;
        quoteLine.PricebookEntryId=pbes[0].Id;
        quoteLine.vlocity_cmt__Action__c='Add';
        quoteLine.ARTL_Purchase_Order__c =null;
        quoteLine.vlocity_cmt__ServiceAccountId__c =accounts[2].id;
       // quoteLine.vlocity_cmt__BillingAccountId__c =accounts[1].id;
        quoteLine.vlocity_cmt__BillingAccountId__c =Null;
        
        insert quoteLine;
        
         PO_Group__c POGrp= new PO_Group__c();
        POGrp.ARTL_PO_Group_Number__c='123456';
        POGrp.ARTL_Legacy_No__c='123456';
        insert POGrp;
        ARTL_Billing_Staging__c stage = new ARTL_Billing_Staging__c();
        stage.Quote__c = qtest.Id;
        stage.Quote_Line_Item__c = quoteLine.Id;
        stage.Shipping_Street__c = 'Test';
        insert stage;
            List<ARTL_Billing_Staging__c> basaList=[SELECT Id, Shipping_Street__c ,Quote_Line_Item__r.Quote.AccountId,Quote__c, Quote__r.Account.Name FROM ARTL_Billing_Staging__c];
        for(ARTL_Billing_Staging__c BL : basaList)
        {
            BL.Quote__c = qtest.Id;
           // BL.Quote__r= qtest.Id;
           Bl.Quote_Line_Item__c=quoteLine.id;
        BL.Status__c = 'Success';
           // BL.Quote__r.Account=accounts[2].id;
            BL.Quote__r.Account.Name='sds';
             BL.ARTL_PO_Group_Id__c = POGrp.id;
            BL.PO__c='TEST';
            BL.PO_Start_Date__c=Date.valueof('2024-01-06'); 
                BL.PO_End_Date__c=Date.valueof('2025-01-06'); 
           // BL.Quote_Line_Item__c = quoteLine.id;
            BL.Shipping_Street__c = 'Test';
            BL.BCP_Last_Name__c = 'Testtest';
            BL.BCP_First_Name__c = 'Firstfirst';
            BL.PO_Amount__c=123;
            BL.Billing_Address__c='TEST';
            Bl.Billing_State__c='test';
            bl.Billing_PinCode__c='440013';
            bl.Billing_City__c='Nagpur';
            BL.BCP_Phone__c= '1234567899';
            BL.Billing_Country__c='India';
            BL.Billing_Account_Number__c='122345';
             BL.BCP_Email__c = 'test_123@gmail.com';
            BL.Billing_Account_Id__c = accounts[1].Id;
            Bl.Billing_Street__c = 'MG Road';
            Bl.Billing_Level__c='Account Level';
            BL.Legal_Entity__c='Test';
            BL.CurrencyIsoCode ='INR';
            BL.License_Company__c='BAL Internet';
            BL.Bill_Format__c='AES - Services';
            BL.Taxation__c='';
            BL.Usage_Flag__c=Null;
            BL.Credit_Period__c = Null;
            BL.Bill_Franchise_Tax_Code__c='';
            BL.Billing_GST_Applicable_for_Billing__c=False;
            BL.StandardReasonforTaxExemption__c =Null;
             BL.Delivery_GST__c=null;
            Bl.NBA_Account_Number__c =Null;
            BL.BCP_Id__c = Null;
            Bl.Store__c= Null;
            BL.Bill_Type__c='Advance';
            BL.BCP_Id__c =Null;
            BL.DCP_Id__c=NULL;
            BL.DCP_Last_Name__c = 'test';
            BL.DCP_First_Name__c ='first';
            BL.DCP_Phone__c=  '1234567890';
            BL.DCP_Email__c = 'test_12@gmail.com';
            BL.Service_Account_Id__c = accounts[1].Id;
            //String uniqueKey = obj.BCP_First_Name__c + obj.BCP_Last_Name__c + obj.BCP_Phone__c + obj.BCP_Email__c;
        } 
        
        update basaList;
        system.debug('baselist::' + basaList);
        test.starttest();
        //ARTL_BACreationPreProcessBatchHelper BAClass = new ARTL_BACreationPreProcessBatchHelper();
           ARTL_BACreationPreProcessBatchHelper.createBillingAccounts(basaList,string.valueof(billingAccountRecordTypeId));
         ARTL_BACreationPreProcessBatchHelper.createBillingAccounts(basaList,string.valueof(serviceAccountRecordTypeId));
       // ARTL_BACreationPreProcessBatchHelper.getPOOrCreate(basaList);
        Test.stopTest();
        }
}