force-app/main/default/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External Id created for Data Migration Purpose only</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Short_Code__c.field-meta.xml
<CustomField>
    <fullName>Short_Code__c</fullName>
    <label>Short Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Alternate_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Integration Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Siebel_Id__c.field-meta.xml
<CustomField>
    <fullName>Siebel_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Siebel Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__IsActive__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean indicating whether the Contact is active or inactive without depending on the specific contact status. Vlocity logic determines whether this Contact should be considered active or inactive using this field. Typically inactive means the Contact will be filtered out of views and lists.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_NBA_Account__c.field-meta.xml
<CustomField>
    <fullName>ARTL_NBA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NBA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/BCP_DCP_Number__c.field-meta.xml
<CustomField>
    <fullName>BCP_DCP_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BCP/DCP Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Siebel Contact Number</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GST#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7) OR (3 AND 8 AND 2) OR (3 AND 9 AND 7) OR (10 AND 7)</booleanFilter>
        <errorMessage>Invalid Mapping of Standard Reason and GST Type</errorMessage>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_GST_Applicable__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ with taxes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Zero Rated Supply- FTWZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non Taxable as transactions within same Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GST__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Siebel_Id__c.field-meta.xml
<CustomField>
    <fullName>Siebel_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Siebel Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GST__c/fields/ARTL_GST_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ARTL_GST_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GST State Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_B2BFetchBCPDCPDetails.cls
global class ARTL_B2BFetchBCPDCPDetails  {
     public static string queryB2BBCPDCPJSONResponse(String bcp, String dcp , String accNumber){
        List<ContactPremiseRelation__c> bcdc = [Select Id,BCP_DCP_Number__c,GST__r.ARTL_GST_State_Code__c,  ARTL_NBA_Account__r.Name,ARTL_NBA_Account__r.Short_Code__c, ARTL_NBA_Account__r.ARTL_Business_Circle_Region__c,Role__c,   Contact__r.Siebel_Id__c, Contact__r.Integration_Id__c, Contact__r.vlocity_cmt__IsActive__c, Contact__r.ARTL_Alternate_Email__c,Contact__r.vlocity_cmt__ContactNumber__c,Contact__r.Title,Contact__r.External_Id__c,Contact__r.Fax,Contact__r.FirstName,Contact__r.LastName,Contact__r.MailingCity,
                                                Contact__r.MailingCountry,Contact__r.MailingState,Contact__r.MailingStreet,Contact__r.MailingPostalCode,Contact__r.MiddleName,Contact__r.Email,
                                                Contact__r.Country_Code__c,Contact__r.Account.AccountNumber, Contact__r.ARTL_Contact_Role__c,Contact__r.RecordType.Name,Contact__r.Salutation,Contact__r.vlocity_cmt__Status__c,
                                                Contact__r.ARTL_Designation__c,Premises__r.vlocity_cmt__City__c,Premises__r.vlocity_cmt__Country__c,Premises__r.vlocity_cmt__State__c,Premises__r.vlocity_cmt__StreetAddress__c,
                                                Premises__r.vlocity_cmt__PostalCode__c,Premises__r.Business_Account__c,GST__r.Name,ARTL_GST_Applicable__c,ARTL_Standard_Reason__c,Name,ARTL_NBA_Account__r.AccountNumber, Premises__c, Contact__r.Account.Name from ContactPremiseRelation__c where BCP_DCP_Number__c = : bcp OR BCP_DCP_Number__c = : dcp  OR ARTL_NBA_Account__r.AccountNumber = : accNumber];
        system.debug('bcdc : ' + bcdc);
        system.debug('bcdc size : ' + bcdc.size());
        ARTL_B2BFetchBCPDCPDetails wrapper = new ARTL_B2BFetchBCPDCPDetails();
         wrapper.SiebelMessage = new ARTL_B2BFetchBCPDCPDetails.ClsSiebelMessage();
         wrapper.SiebelMessage.B2BNonBillingAccount = new ARTL_B2BFetchBCPDCPDetails.ClsB2BNonBillingAccount();
         System.debug('before bcpdcp');
         
         System.debug('after bcpdcp');
         wrapper.SiebelMessage.B2BNonBillingAccount.B2BBCPDCPBC = new List<ARTL_B2BFetchBCPDCPDetails.ClsB2BBCPDCPBC>();
         System.debug('after bcpdcp');
         //system.debug('/////'); 
        if(bcdc.size()>0){
            system.debug('inside size check');
             for(ContactPremiseRelation__c cpl :bcdc ){
            if(cpl.Role__c == 'BCP' || cpl.Role__c == 'DCP'){
                system.debug('inside if : ' + cpl.Role__c);
              //  ARTL_ErrorForCreateNBA wrapper = new ARTL_ErrorForCreateNBA();
                wrapper.StatusCode = '';
                wrapper.StatusMessage = 'Contact details returned successfully.';
                
                //wrapper.SiebelMessage = new ARTL_ErrorForCreateNBA.ClsSiebelMessage();
                SYstem.debug('debug 381');
                wrapper.SiebelMessage.IntObjectFormat = 'Siebel Hierarchical';
                wrapper.SiebelMessage.MessageId = '';
                wrapper.SiebelMessage.IntObjectName = '';
                wrapper.SiebelMessage.MessageType = 'Integration Object';
                SYstem.debug('debug 386');
                //wrapper.SiebelMessage.B2BNonBillingAccount =  new ARTL_ErrorForCreateNBA.ClsB2BNonBillingAccount();
                wrapper.SiebelMessage.B2BNonBillingAccount.Name = cpl.ARTL_NBA_Account__r.Name;
                wrapper.SiebelMessage.B2BNonBillingAccount.BCPDCPCount = '';  //// doubt..
                wrapper.SiebelMessage.B2BNonBillingAccount.GSTCount = '';      //// doubt..
                wrapper.SiebelMessage.B2BNonBillingAccount.ShortCode = cpl.ARTL_NBA_Account__r.Short_Code__c;
                wrapper.SiebelMessage.B2BNonBillingAccount.AccountNumber = cpl.ARTL_NBA_Account__r.AccountNumber;
                
                SYstem.debug('debug 394');
             //   wrapper.SiebelMessage.B2BNonBillingAccount.B2BBCPDCPBC = new List<ARTL_ErrorForCreateNBA.ClsB2BBCPDCPBC>();
                // for loop shoulb de there for iteration..
                ARTL_B2BFetchBCPDCPDetails.ClsB2BBCPDCPBC lst = new ARTL_B2BFetchBCPDCPDetails.ClsB2BBCPDCPBC();
                lst.Responsibility = cpl.Contact__r.ARTL_Contact_Role__c;
                lst.Zone = '';
                lst.Pincode =  cpl.Contact__r.MailingPostalCode;
                lst.Country = cpl.Contact__r.MailingCountry;
                lst.LastName = cpl.Contact__r.LastName;
                lst.GSTApplicable = cpl.ARTL_GST_Applicable__c;
                lst.ImplementationCircle =  cpl.ARTL_NBA_Account__r.ARTL_Business_Circle_Region__c;
                lst.Type = cpl.role__c == 'BCP' ? 'Billing Contact Person': cpl.role__c == 'DCP'?  'Dispatch Contact Person' : cpl.role__c == '' ? '' :'' ; //'Billing Contact Person';
                lst.MiddleName = cpl.Contact__r.MiddleName;
                lst.SiebelContactNumber = cpl.Contact__r.vlocity_cmt__ContactNumber__c;
                lst.Designation = cpl.Contact__r.ARTL_Designation__c;
                lst.State = cpl.Contact__r.MailingState;
                lst.PhoneAreaCode = cpl.Contact__r.Country_Code__c;
                lst.AlternateEmailAddress = cpl.Contact__r.ARTL_Alternate_Email__c;
                lst.Status = cpl.Contact__r.vlocity_cmt__Status__c;
                lst.eCRMNumber = '';
                lst.Circle = cpl.ARTL_NBA_Account__r.ARTL_Business_Circle_Region__c ;
                lst.GST = cpl.GST__r.Name;
                lst.GSTStateCode = cpl.GST__r.ARTL_GST_State_Code__c;
                lst.CellularPhone = '';
                lst.EmailAddress = cpl.Contact__r.Email;
                lst.Created = '';
                lst.GSTNonApplicableReason = cpl.ARTL_Standard_Reason__c;
                lst.FaxPhoneNumber = cpl.Contact__r.Fax;
                lst.AddressLine4 = '';
                lst.FirstName = cpl.Contact__r.FirstName;
                lst.AddressLine3 = '';
                lst.AddressLine2 = '';
                lst.MM = '';
                lst.AddressLine1 = '';
                lst.City = cpl.Contact__r.MailingCity;
                SYstem.debug('debug 429');
                wrapper.SiebelMessage.B2BNonBillingAccount.B2BBCPDCPBC.add(lst);
                System.debug('debug 431');
                
            } /* else if(cpl.Role__c == 'DCP'){
                 system.debug('inside else if : ' + cpl.Role__c);
                //ARTL_ErrorForCreateNBA wrapper = new ARTL_ErrorForCreateNBA();
                wrapper.StatusCode = '';
                wrapper.StatusMessage = 'Contact details returned successfully.';
                
               // wrapper.SiebelMessage = new ARTL_ErrorForCreateNBA.ClsSiebelMessage();
                wrapper.SiebelMessage.IntObjectFormat = 'Siebel Hierarchical';
                wrapper.SiebelMessage.MessageId = '';
                wrapper.SiebelMessage.IntObjectName = '';
                wrapper.SiebelMessage.MessageType = 'Integration Object';
                
               // wrapper.SiebelMessage.B2BNonBillingAccount =  new ARTL_ErrorForCreateNBA.ClsB2BNonBillingAccount();
                wrapper.SiebelMessage.B2BNonBillingAccount.Name = cpl.ARTL_NBA_Account__r.Name;
                wrapper.SiebelMessage.B2BNonBillingAccount.BCPDCPCount = '';
                wrapper.SiebelMessage.B2BNonBillingAccount.GSTCount = '';
                wrapper.SiebelMessage.B2BNonBillingAccount.ShortCode = cpl.ARTL_NBA_Account__r.Short_Code__c;
                wrapper.SiebelMessage.B2BNonBillingAccount.AccountNumber = cpl.ARTL_NBA_Account__r.AccountNumber;
                
                
               // wrapper.SiebelMessage.B2BNonBillingAccount.B2BBCPDCPBC = new List<ARTL_ErrorForCreateNBA.ClsB2BBCPDCPBC>();
                // for loop shoulb de there for iteration..
                ARTL_B2BFetchBCPDCPDetails.ClsB2BBCPDCPBC lst = new ARTL_B2BFetchBCPDCPDetails.ClsB2BBCPDCPBC();
                lst.Responsibility =cpl.Contact__r.ARTL_Contact_Role__c;
                lst.Zone = '';
                lst.Pincode = cpl.Contact__r.MailingPostalCode;
                lst.Country = cpl.Contact__r.MailingCountry;
                lst.LastName =cpl.Contact__r.LastName;
                lst.GSTApplicable = cpl.ARTL_GST_Applicable__c;
                lst.ImplementationCircle = cpl.ARTL_NBA_Account__r.ARTL_Business_Circle_Region__c;
                lst.Type = 'Dispatch Contact Person';
                lst.MiddleName = '';
                lst.SiebelContactNumber = '';
                lst.Designation = '';
                lst.State = '';
                lst.PhoneAreaCode = '';
                lst.AlternateEmailAddress = '';
                lst.Status = '';
                lst.eCRMNumber = '';
                lst.Circle = '';
                lst.GST = '';
                lst.GSTStateCode = '';
                lst.CellularPhone = '';
                lst.EmailAddress = '';
                lst.Created = '';
                lst.GSTNonApplicableReason = '';
                lst.FaxPhoneNumber = '';
                lst.AddressLine4 = '';
                lst.FirstName = '';
                lst.AddressLine3 = '';
                lst.AddressLine2 = '';
                lst.MM = '';
                lst.AddressLine1 = '';
                lst.City = '';
                System.debug('debug 485');
                wrapper.SiebelMessage.B2BNonBillingAccount.B2BBCPDCPBC.add(lst);
            } */
             }
        }
        String asst = JSON.serialize(wrapper);
        system.debug('asst : ' + asst);
        return asst;
    }
    public String StatusCode;
    public String StatusMessage;
    public ClsSiebelMessage SiebelMessage;
    
    public class ClsSiebelMessage {
        public String IntObjectFormat;
        public String MessageId;
        public String IntObjectName;
        public String MessageType;
        public ClsB2BNonBillingAccount B2BNonBillingAccount;
    }
    
    public class ClsB2BNonBillingAccount {
        public String Name;
        public String BCPDCPCount;
        public String GSTCount;
        public String ShortCode;
        public String AccountNumber;
        public ClsB2BBCPDCPBC[] B2BBCPDCPBC;
    }
    
    public class ClsB2BBCPDCPBC {
        public String Responsibility;
        public String Zone;
        public String Pincode;
        public String Country;
        public String LastName;
        public String GSTApplicable;
        public String ImplementationCircle;
        public String Type;
        public String MiddleName;
        public String SiebelContactNumber;
        public String Designation;
        public String State;
        public String PhoneAreaCode;
        public String AlternateEmailAddress;
        public String Status;
        public String eCRMNumber;
        public String Circle;
        public String GST;
        public String GSTStateCode;
        public String CellularPhone;
        public String EmailAddress;
        public String Created;
        public String GSTNonApplicableReason;
        public String FaxPhoneNumber;
        public String AddressLine4;
        public String FirstName;
        public String AddressLine3;
        public String AddressLine2;
        public String MM;
        public String AddressLine1;
        public String City;
    }
   
    
}