force-app/main/default/objects/Account/fields/Step_1_Description__c.field-meta.xml
<CustomField>
    <fullName>Step_1_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Creation Sync</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Step_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_2_Status__c</fullName>
    <label>FX Callout Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Step_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_3_Status__c</fullName>
    <label>Solace Callout Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/Case_Tracking_Detail__c.object-meta.xml
<CustomObject>
    <description>This object is to capture detailed status of contact creation and updation across various channels.</description>
    <label>Case Tracking Detail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Tracking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Tracking Details</relationshipLabel>
    <relationshipName>Case_Tracking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/SF_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Record_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SF Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/Step1__c.field-meta.xml
<CustomField>
    <fullName>Step1__c</fullName>
    <label>Contact Upsert Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/Step_1_Description__c.field-meta.xml
<CustomField>
    <fullName>Step_1_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Upsert Sync</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/Step_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_2_Status__c</fullName>
    <label>Solace Callout Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Tracking_Detail__c/fields/Step_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_3_Status__c</fullName>
    <label>Solace Inbound Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_CaseTrackingDetailTriggerTest.cls
@isTest
public with sharing class ARTL_CaseTrackingDetailTriggerTest {
    public ARTL_CaseTrackingDetailTriggerTest() {
        
    }
    @TestSetup
    public static void testData(){
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account testAcc = new Account(name = 'Test Accountabc', RecordTypeId = recordTypeId);
        insert testAcc;
        Contact contactRec = new Contact(FirstName = 'Test', 
                                         LastName = 'Test',
                                         ARTL_Designation__c = 'Test', 
                                         ARTL_Contact_Role__c = 'CEO', 
                                         Phone = '9876543210', 
                                         Email = 'test@test.com',
                                         AccountId = testAcc.Id);
        insert contactRec;
        
        Case caseRec = new Case (Status = 'In-Progress', 
                                 Origin = 'Web');
        insert caseRec;
        
        Case_Tracking_Detail__c caseTrackingRec = new Case_Tracking_Detail__c(Name = 'test', 
                                                                              Case__c = caseRec.Id, 
                                                                              SF_Record_ID__c = contactRec.Id, 
                                                                              Step1__c = 'Success', 
                                                                              Step_1_Description__c = 'created'); 
        insert caseTrackingRec;
        
    }
    
    @isTest
    public static void testCaseTrackingCreation(){
        Case_Tracking_Detail__c ctdRecord = [Select Id, Name, Step_2_Status__c, Step_3_Status__c from Case_Tracking_Detail__c];
        ctdRecord.Step_2_Status__c = 'Success';
        ctdRecord.Step_3_Status__c = 'Success';
        update ctdRecord;
        
    }

    @isTest
    public static void testInvokeIntegrationProcedure1(){
        Case_Tracking_Detail__c ctdRecord = [Select Id, Name, Step_2_Status__c, Step_3_Status__c, Case__c, SF_Record_ID__c from Case_Tracking_Detail__c];
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put('recordId', ctdRecord.SF_Record_ID__c);
        inputMap.put('caseId', ctdRecord.Case__c);
        Test.startTest();
        CaseTrackingDetailStep4Handler.invokeIntegrationProcedure(JSON.serialize(inputMap), 'ARTL_Step4InvokeSolace', ctdRecord.Id);
        ARTL_CaseTrackingDetailTriggerHandler.invokeIntegrationProcedure(JSON.serialize(inputMap), 'ARTL_BCPDCPSolaceQueue', ctdRecord.Id);

        Test.stopTest();
    }
    
    @isTest
    public static void testInvokeIntegrationProcedure2(){
        Case_Tracking_Detail__c ctdRecord = [Select Id, Name, Step1__c, Step_2_Status__c, Step_3_Status__c, Case__c, SF_Record_ID__c from Case_Tracking_Detail__c];
        ctdRecord.Step1__c = 'Error';
        update ctdRecord;
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put('recordId', ctdRecord.SF_Record_ID__c);
        inputMap.put('caseId', ctdRecord.Case__c);
        Test.startTest();
        CaseTrackingDetailStep4Handler.invokeIntegrationProcedure(JSON.serialize(inputMap), 'ARTL_Step4InvokeSolace', ctdRecord.Id);
        ARTL_CaseTrackingDetailTriggerHandler.invokeIntegrationProcedure(JSON.serialize(inputMap), 'ARTL_BCPDCPSolaceQueue', ctdRecord.Id);

        Test.stopTest();
    }


    
    
}