force-app/main/default/objects/ARTL_Billing_Staging__c/ARTL_Billing_Staging__c.object-meta.xml
<CustomObject>
    <label>Billing Staging</label>
    <nameField>
        <label>Billing Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing Stagings</relationshipLabel>
    <relationshipName>Billing_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_ValidateStagingDataTest.cls
@isTest

public class ARTL_ValidateStagingDataTest {
    @isTest
    static void validateStagingDataPositiveTest(){
        User usr = ARTL_ValidateStagingDataHelper.getUser();
        String quoteId = ARTL_ValidateStagingDataHelper.getQuoteIdPos();
        String validationStatus ='Success';
        System.runAs(usr){
            Test.startTest();
            /*ARTL_ValidateStagingData obj = new ARTL_ValidateStagingData();
            DataBase.executeBatch(obj); */
            //Database.executeBatch(new ARTL_ValidateStagingData(quoteId)); 
            ARTL_ValidateStagingDataHelper.invokeARTL_ValidateStagingData(quoteId, true);
            Test.stopTest();
            List<ARTL_Billing_Staging__c> stagingRec = [select id, Status__c from ARTL_Billing_Staging__c  where Quote__c =:quoteId];
            for(ARTL_Billing_Staging__c stage : stagingRec){
                if(stage.get('Status__c')=='Failed'){
                    validationStatus = 'Failed';
                    break;
                }
            }
        }
        
    }
    
    @isTest
    static void validateStagingDataNegativeTest(){
        User usr = ARTL_ValidateStagingDataHelper.getUser();
        String quoteId = ARTL_ValidateStagingDataHelper.getQuoteIdNeg();
        String validationStatus ='Success';
        System.runAs(usr){
            Test.startTest();
            /*ARTL_ValidateStagingData obj = new ARTL_ValidateStagingData();
            DataBase.executeBatch(obj); */
            //Database.executeBatch(new ARTL_ValidateStagingData(quoteId)); 
            ARTL_ValidateStagingDataHelper.invokeARTL_ValidateStagingData(quoteId, true);
            Test.stopTest();
            List<ARTL_Billing_Staging__c> stagingRec = [select id, Status__c from ARTL_Billing_Staging__c  where Quote__c =:quoteId];
            for(ARTL_Billing_Staging__c stage : stagingRec){
                if(stage.get('Status__c')=='Failed'){
                    validationStatus = 'Failed';
                    break;
                }
            }
        }
        
    }
}