force-app/main/default/objects/ARTL_Billing_Staging__c/ARTL_Billing_Staging__c.object-meta.xml
<CustomObject>
    <label>Billing Staging</label>
    <nameField>
        <label>Billing Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/BCP_Id__c.field-meta.xml
<CustomField>
    <fullName>BCP_Id__c</fullName>
    <label>BCP Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Bill_Format__c.field-meta.xml
<CustomField>
    <fullName>Bill_Format__c</fullName>
    <description>Billing format that is being used for this billing account</description>
    <label>Bill Format</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <description>Billing Address from PO</description>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Level__c.field-meta.xml
<CustomField>
    <fullName>Billing_Level__c</fullName>
    <label>Billing Level</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/DCP_Id__c.field-meta.xml
<CustomField>
    <fullName>DCP_Id__c</fullName>
    <label>DCP Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/InvoiceShipmentAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoiceShipmentAddress__c</fullName>
    <description>Invoice Shipment address from PO</description>
    <label>Invoice Shipment Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/License_Company__c.field-meta.xml
<CustomField>
    <fullName>License_Company__c</fullName>
    <label>License Company</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/LSI__c.field-meta.xml
<CustomField>
    <fullName>LSI__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LSI Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/NBA_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>NBA_Account_Number__c</fullName>
    <label>NBA Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <label>PO#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_End_Date__c</fullName>
    <label>PO End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Group__c.field-meta.xml
<CustomField>
    <fullName>PO_Group__c</fullName>
    <label>PO Group#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/PO_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Start_Date__c</fullName>
    <label>PO Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Billing Stagings</relationshipLabel>
    <relationshipName>Billing_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Billing_Staging__c/fields/StandardReasonforTaxExemption__c.field-meta.xml
<CustomField>
    <fullName>StandardReasonforTaxExemption__c</fullName>
    <label>Standard Reason for Tax Exemption</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO_Group__c/PO_Group__c.object-meta.xml
<CustomObject>
    <label>PO Group</label>
    <nameField>
        <displayFormat>71-8{0000000}</displayFormat>
        <label>PO Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ARTL_LSIRequired__c.field-meta.xml
<CustomField>
    <fullName>ARTL_LSIRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LSI Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AttributeSelectedValues__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AttributeSelectedValues__c</fullName>
    <label>Attribute Selected Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BillingStagingData.cls
global class BillingStagingData implements vlocity_cmt.VlocityOpenInterface{

    private Static final String BILLING_STAGING = 'SELECT id, NBA_Account_Number__c, LSI__c, Legal_Entity__c, Billing_Type__c, License_Company__c, Bill_Format__c, Billing_Level__c, PO__c, PO_Amount__c, PO_Start_Date__c, PO_End_Date__c, StandardReasonforTaxExemption__c, PO_Group__c, BCP_Id__c, DCP_Id__c, Billing_Address__c, InvoiceShipmentAddress__c, Quote_Line_Item__c FROM ARTL_Billing_Staging__c WHERE Quote_Line_Item__c IN :itemIds';
    private Static final String PARENT_QLI = 'SELECT id, vlocity_cmt__RootItemId__c FROM QuoteLineItem WHERE Product2.ProductCode =: productCode AND QuoteId =: quoteId';
    private Static final String CHILD_QLI = 'SELECT id, vlocity_cmt__AttributeSelectedValues__c FROM QuoteLineItem WHERE vlocity_cmt__RootItemId__c IN : rootItemIds AND Product2.ARTL_LSIRequired__c= true AND QuoteId =: quoteId';


    global Boolean invokeMethod(String methodName, Map<String, Object> input, Map < String, Object > output, Map < String, Object > options){

        if (methodName == 'getBillingStagingData')
            getBillingStagingData(input,output);

        else
            throw new BillingStagingDataException ('Unknown method: ' + methodName );
 
        return true;
	}
    
    public static void getBillingStagingData( Map<String,Object> input, Map<String,Object> output ){


        String productCode = (String)input.get('productCode');
        String quoteId = (String)input.get('quoteId');

        List<String> rootItemIds = new List<String>();
        List<SObject> parentQLIs = Database.query(PARENT_QLI);
        System.debug('🛟🛟🛟🛟 parentQLIs '+ parentQLIs);
        for (SObject qli : parentQLIs) {
            rootItemIds.add(String.valueOf(qli.get('vlocity_cmt__RootItemId__c')));
        }
        System.debug('🛟🛟🛟🛟 rootItemIds '+ rootItemIds);

        List<String> itemIds = new List<String>();
        List<Object> selectedAttributeJSON = new List<Object>();
        List<SObject> childQLIs = Database.query(CHILD_QLI);
        System.debug('🛟🛟🛟🛟 childQLIs '+ childQLIs);
        for (SObject qli : childQLIs) {
            itemIds.add(String.valueOf(qli.get('Id')));
            Map<String,Object> attrSelectedMap = ( Map<String,Object>)JSON.deserializeUntyped((String)qli.get('vlocity_cmt__AttributeSelectedValues__c'));
            attrSelectedMap.put('Quote_Line_Item__c', qli.Id);
            selectedAttributeJSON.add(attrSelectedMap);
        }
        System.debug('🛟🛟🛟🛟 selectedAttributeJSON '+ JSON.serialize(selectedAttributeJSON));


        List<SObject> billingStagingData = Database.query(BILLING_STAGING);
        selectedAttributeJSON.addAll(billingStagingData);
        output.put('selectedAttributeJSON', JSON.deserializeUntyped(JSON.serialize(selectedAttributeJSON)));
        // output.put('billingStagingData', selectedAttributeJSON);

    }

    public class BillingStagingDataException extends Exception{}
}