force-app/main/default/objects/PM_User_Matrix__c/PM_User_Matrix__c.object-meta.xml
<CustomObject>
    <label>PM User Matrix</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM User Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_User_Matrix__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PM User Matrix</relationshipLabel>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CCE__c.field-meta.xml
<CustomField>
    <fullName>CCE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
            <value>
                <fullName>EMERGING</fullName>
            </value>
            <value>
                <fullName>GUJ</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>MPCG</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>NESA</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>UPU</fullName>
            </value>
            <value>
                <fullName>WBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CPH__c.field-meta.xml
<CustomField>
    <fullName>CPH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPH</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM User</description>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/TL__c.field-meta.xml
<CustomField>
    <fullName>TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM&apos;s TL</description>
    <label>TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_UpdatePMUserMatrixTest.cls
@isTest
public with sharing class ARTL_UpdatePMUserMatrixTest {

    @testSetup    
    static void setupData() {
        Profile p = [SELECT id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];  
        User adminUser = new User(firstname= 'Samuel',
                                  lastname='Oak',
                                  Alias='Samuel',
                                  email = 'testemail665411@email.com',
                                  username= 'testemail665411@email.com', 
                                  profileId= p.id, 
                                  emailencodingkey='UTF-8',
                                  languagelocalekey='en_US',
                                  localesidkey='en_US',
                                  timezonesidkey='America/Los_Angeles');
        System.runAs(adminUser){
            List<Account> accList = ARTL_TestDataFactory.createAccount('Business', true, 1);
            PM_User_Matrix__c pm = new PM_User_Matrix__c();
            pm.Business_Account__c = accList[0].Id;
            pm.PM__c = UserInfo.getUserId();
            pm.TL__c = UserInfo.getUserId();
            pm.CPH__c = UserInfo.getUserId();
            pm.CCE__c = UserInfo.getUserId();
            pm.Circle__c = 'KK';
            insert pm;
        }
    }

    @isTest
    static void updatePMMatrix() {
        User u1 = [SELECT Id from User where username = 'testemail665411@email.com'];
        List<List<ARTL_PMUserMatrixWrapper>> userWrapperList = new List<List<ARTL_PMUserMatrixWrapper>>();
        ARTL_PMUserMatrixWrapper wrapper1 = new ARTL_PMUserMatrixWrapper();
        wrapper1.oldUser = u1.Id;
        wrapper1.newUser = UserInfo.getUserId();
        wrapper1.userType = 'PM';

        ARTL_PMUserMatrixWrapper wrapper2 = new ARTL_PMUserMatrixWrapper();
        wrapper2.oldUser = u1.Id;
        wrapper2.newUser = UserInfo.getUserId();
        wrapper2.userType = 'TL';

        ARTL_PMUserMatrixWrapper wrapper3 = new ARTL_PMUserMatrixWrapper();
        wrapper3.oldUser = u1.Id;
        wrapper3.newUser = UserInfo.getUserId();
        wrapper3.userType = 'CPH';

        ARTL_PMUserMatrixWrapper wrapper4 = new ARTL_PMUserMatrixWrapper();
        wrapper4.oldUser = u1.Id;
        wrapper4.newUser = UserInfo.getUserId();
        wrapper4.userType = 'CCE';

        userWrapperList.add(new List<ARTL_PMUserMatrixWrapper>{wrapper1, wrapper2, wrapper3, wrapper4});
        ARTL_UpdatePMUserMatrix.updateMatrix(userWrapperList);
    }
}