force-app/main/default/objects/PM_User_Matrix__c/PM_User_Matrix__c.object-meta.xml
<CustomObject>
    <label>PM User Matrix</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM User Matrix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PM_User_Matrix__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PM User Matrix</relationshipLabel>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CCE__c.field-meta.xml
<CustomField>
    <fullName>CCE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BIHAR</fullName>
            </value>
            <value>
                <fullName>EMERGING</fullName>
            </value>
            <value>
                <fullName>GUJ</fullName>
            </value>
            <value>
                <fullName>KK</fullName>
            </value>
            <value>
                <fullName>KTN</fullName>
            </value>
            <value>
                <fullName>MPCG</fullName>
            </value>
            <value>
                <fullName>MUM</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>NESA</fullName>
            </value>
            <value>
                <fullName>RAJ</fullName>
            </value>
            <value>
                <fullName>ROM</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>UPU</fullName>
            </value>
            <value>
                <fullName>WBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/CPH__c.field-meta.xml
<CustomField>
    <fullName>CPH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPH</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM User</description>
    <label>PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PM_User_Matrix__c/fields/TL__c.field-meta.xml
<CustomField>
    <fullName>TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PM&apos;s TL</description>
    <label>TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM_User_Matrix1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_UpdatePMUserMatrix.cls
public with sharing class ARTL_UpdatePMUserMatrix {
    
    @InvocableMethod
    public static void updateMatrix(List<List<ARTL_PMUserMatrixWrapper>> userWrapperList){
        system.debug('userWrapperList--->'+userWrapperList);
        List<ARTL_PMUserMatrixWrapper> userWrapper= userWrapperList[0];
        system.debug('userWrapper--->'+userWrapper);
        system.debug('userWrapper--->'+userWrapper);

        Map<Id,Id> pmUserId = new Map<Id,Id>();
        Map<Id,Id> tlUserId = new Map<Id,Id>();
        Map<Id,Id> cphUserId = new Map<Id,Id>();
        Map<Id,Id> cceUserId = new Map<Id,Id>();
        List<PM_User_Matrix__c> pmMatrixToUpdate = new List<PM_User_Matrix__c>();
        for(ARTL_PMUserMatrixWrapper pmMatrix : userWrapper){
            if(pmMatrix.oldUser != null && pmMatrix.newUser != null && pmMatrix.oldUser != pmMatrix.newUser){
                if(pmMatrix.userType == 'PM')
                    pmUserId.put(pmMatrix.oldUser, pmMatrix.newUser);
                if(pmMatrix.userType == 'TL')
                    tlUserId.put(pmMatrix.oldUser, pmMatrix.newUser);
                if(pmMatrix.userType == 'CPH')
                    cphUserId.put(pmMatrix.oldUser, pmMatrix.newUser);
                if(pmMatrix.userType == 'CCE')
                    cceUserId.put(pmMatrix.oldUser, pmMatrix.newUser);
            }
        }

        for(PM_User_Matrix__c pmRec : [SELECT Id, PM__c, TL__c, CPH__c, CCE__c, Business_Account__c, Circle__c FROM 
                                        PM_User_Matrix__c WHERE
                                        PM__c IN :pmUserId.keySet() OR
                                        TL__c IN :tlUserId.keySet() OR
                                        CPH__c IN :cphUserId.keySet() OR
                                        CCE__c IN :cceUserId.keySet()
                                        ]){
            Boolean isChanged = false;                                
            if(pmUserId.containsKey(pmRec.PM__c)){
                pmRec.PM__c = pmUserId.get(pmRec.PM__c);
                isChanged = true;
            }
            if(tlUserId.containsKey(pmRec.TL__c)){
                pmRec.TL__c = tlUserId.get(pmRec.TL__c);
                isChanged = true;
            } 
            if(cphUserId.containsKey(pmRec.CPH__c)){
                pmRec.CPH__c = cphUserId.get(pmRec.CPH__c);
                isChanged = true;
            } 
            if(cceUserId.containsKey(pmRec.CCE__c)){
                pmRec.CCE__c = cceUserId.get(pmRec.CCE__c);
                isChanged = true;
            } 
            if(isChanged)
                pmMatrixToUpdate.add(pmRec);                                
        }

        Database.update(pmMatrixToUpdate, false);

    }

    
}