force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ARTL_UpdateOnsiteAttendanceTest.cls
/**
 * Test class for ARTL_UpdateOnsiteAttendance
 */
@isTest
public class ARTL_UpdateOnsiteAttendanceTest {
	@TestSetup
    static void createTestData(){
        List<Account> accList = ARTL_TestDataFactory.createAccount('Business',true,1);
       // List<Contact> conList = ARTL_TestDataFactory.createContact('MobilePhoneContact',(accList.get(0)).Id, true, 1);
       Contact testContact = new Contact(Firstname = 'Test',LastName = 'Contact', Email = 'testcontact@test.com',AccountId= (accList.get(0)).Id, Phone = '8765337890',ARTL_Designation__c = 'Test', ARTL_Contact_Role__c='Sales Contact', Country_Code__c = '91');
       insert testContact;
        
        Event eventObj = new Event();
        eventObj.WhatId = (accList.get(0)).Id;
        eventObj.WhoId = testContact.Id;
        eventObj.DurationInMinutes = 1;
        eventObj.ActivityDateTime = System.now();
        insert eventObj;
        
    }
    @IsTest
    static void updateAttendanceTest(){
        Test.startTest();
        Event eventObj = [SELECT Id, Meeting_Location__Latitude__s, Meeting_Location__Longitude__s from Event LIMIT 1];
        ARTL_UpdateOnsiteAttendance.updateAttendance(eventObj.Id,12.0,12.0);
        
        Test.stopTest();
        Event eventObj1 = [SELECT Id, Meeting_Location__Latitude__s, Meeting_Location__Longitude__s from Event LIMIT 1];
        
        System.assertEquals(12.0, eventObj1.Meeting_Location__Latitude__s);
        System.assertEquals(12.0, eventObj1.Meeting_Location__Longitude__s);
    }
}