force-app/main/default/objects/Contact/fields/ARTL_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Contact</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Business Head</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CTO</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>FL Coordinator</fullName>
            </value>
            <value>
                <fullName>IT Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Middle Management</fullName>
            </value>
            <value>
                <fullName>MOB Coordinator</fullName>
            </value>
            <value>
                <fullName>Network Contact</fullName>
            </value>
            <value>
                <fullName>Network Planning</fullName>
            </value>
            <value>
                <fullName>Purchase Contact</fullName>
            </value>
            <value>
                <fullName>Regional Head</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Supply Chain</fullName>
            </value>
            <value>
                <fullName>Voice co-ordinator</fullName>
            </value>
            <value>
                <fullName>Delivery Contact</fullName>
            </value>
            <value>
                <fullName>Resident Engineer</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Company Coordinator</fullName>
            </value>
            <value>
                <fullName>Local Contact Person</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Delivery/Billing Contact</fullName>
                <isActive>false</isActive>
                <label>Delivery/Billing Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ARTL_Designation__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Designation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/ARTL_BCP_DCP_Contact.recordType-meta.xml
<RecordType>
    <fullName>ARTL_BCP_DCP_Contact</fullName>
    <active>true</active>
    <label>BCP/DCP Contact</label>
</RecordType>

force-app/main/default/objects/ContactPremiseRelation__c/ContactPremiseRelation__c.object-meta.xml
<CustomObject>
    <label>Contact Premise Relation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ContactPremise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Premise Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactPremiseRelation__c/fields/ARTL_Standard_Reason__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Standard_Reason__c</fullName>
    <label>Standard Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ARTL_GST_Applicable__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SEZ</fullName>
            </value>
            <value>
                <fullName>UIN</fullName>
            </value>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Non-SEZ</fullName>
            </value>
            <value>
                <fullName>Applied For</fullName>
            </value>
            <value>
                <fullName>SEZ with taxes</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- FTWZ</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- Export</fullName>
            </value>
            <value>
                <fullName>Non Taxable as transactions within same Company</fullName>
            </value>
            <value>
                <fullName>Airtel- Foreign Legal Entity</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Exempt-Trust/Entities 12AA</fullName>
            </value>
            <value>
                <fullName>Zero Rated Supply- SEZ</fullName>
            </value>
            <value>
                <fullName>J&amp;K delivery - Out of GST Preview</fullName>
            </value>
            <value>
                <fullName>Exempt Supply - Trust/Entities 12AA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GST#</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7) OR (3 AND 8 AND 2) OR (3 AND 9 AND 7) OR (10 AND 7)</booleanFilter>
        <errorMessage>Invalid Mapping of Standard Reason and GST Type</errorMessage>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_GST_Applicable__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>UIN</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>GST__c.ARTL_GST_Type__c</field>
            <operation>equals</operation>
            <value>Non-SEZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>SEZ with taxes</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Zero Rated Supply- FTWZ</value>
        </filterItems>
        <filterItems>
            <field>$Source.ARTL_Standard_Reason__c</field>
            <operation>equals</operation>
            <value>Non Taxable as transactions within same Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GST__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Premises__c.field-meta.xml
<CustomField>
    <fullName>Premises__c</fullName>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Contact Premise Relation</relationshipLabel>
    <relationshipName>Contact_Premise_Relation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactPremiseRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BCP</fullName>
            </value>
            <value>
                <fullName>DCP</fullName>
            </value>
            <value>
                <fullName>BCP &amp; DCP</fullName>
                <isActive>false</isActive>
                <label>BCP &amp; DCP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GST__c/GST__c.object-meta.xml
<CustomObject>
    <label>GST</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>GST Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/vlocity_cmt__Premises__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises (Business Account)</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Artl_BcpDcpCtrl.cls
public with sharing class Artl_BcpDcpCtrl {

    private static string ERROR_NO_CONTACTS_FOUND = 'No recrods available';

    @AuraEnabled()
    public static List<BcpDcpContactWrapper> getBcpDcpByAccId(String accId) {
        try{
            // System.debug('accId=' + accId);
            String bcpDcpRecordTypeName = 'ARTL_BCP_DCP_Contact';
            List<String> roleList = new List<String>{'Billing Contact', 'Delivery Contact'};

            List<BcpDcpContactWrapper> bcpDcpWrapperList = new List<BcpDcpContactWrapper>();

            List<ContactPremiseRelation__c> cprList = [Select Id, ARTL_Standard_Reason__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Email, 
                                                            Contact__r.MobilePhone, Contact__r.ARTL_Designation__c, Contact__r.ARTL_Contact_Role__c,  
                                                            Contact__r.Account.Name, Contact__r.AccountId, 
                                                            Premises__r.vlocity_cmt__StreetAddress__c, Premises__r.vlocity_cmt__City__c, Premises__r.vlocity_cmt__State__c, Premises__r.vlocity_cmt__Country__c, Premises__r.vlocity_cmt__PostalCode__c, 
                                                            GST__r.Name, 
                                                            Contact__c, Premises__c, GST__c 
                                                        From ContactPremiseRelation__c 
                                                        Where Contact__r.AccountId =: accId
                                                            AND Contact__r.RecordType.DeveloperName =: bcpDcpRecordTypeName
                                                            AND Contact__r.ARTL_Contact_Role__c IN : roleList
                                                        Order By Contact__c, Role__c ];

            // System.debug('cprList=' + cprList.size());
            if (!cprList.isEmpty()) {
                for(ContactPremiseRelation__c cpr : cprList){
                    bcpDcpWrapperList.add(new BcpDcpContactWrapper(cpr));
                }
            } 
            
            return bcpDcpWrapperList;
        }
        catch (Exception e) {
            System.debug('e.getMessage()=' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class BcpDcpContactWrapper{
        @AuraEnabled public String Id{get;set;}
        @AuraEnabled public String firstName{get;set;}
        @AuraEnabled public String lastName{get;set;}
        @AuraEnabled public String email{get;set;}
        @AuraEnabled public String mobilePhone{get;set;}
        @AuraEnabled public String designation{get;set;}
        @AuraEnabled public String role{get;set;}
        @AuraEnabled public String standardReason{get;set;}
        @AuraEnabled public String streetAddress{get;set;}
        @AuraEnabled public String city{get;set;}
        @AuraEnabled public String state{get;set;}
        @AuraEnabled public String country{get;set;}
        @AuraEnabled public String postalCode{get;set;}
        @AuraEnabled public String gstNumber{get;set;}

        // @AuraEnabled public String contactId{get;set;}
        // @AuraEnabled public String premiseId{get;set;}
        // @AuraEnabled public String gstID{get;set;}
        
        public BcpDcpContactWrapper(ContactPremiseRelation__c cpr){
            this.Id = cpr.Id;

            this.firstName = cpr.Contact__r.FirstName;
            this.lastName = cpr.Contact__r.LastName;
            this.email = cpr.Contact__r.Email;
            this.mobilePhone = cpr.Contact__r.MobilePhone;
            this.designation = cpr.Contact__r.ARTL_Designation__c;
            this.role = cpr.Contact__r.ARTL_Contact_Role__c;

            this.standardReason = cpr.ARTL_Standard_Reason__c;

            this.streetAddress = cpr.Premises__r.vlocity_cmt__StreetAddress__c;
            this.city = cpr.Premises__r.vlocity_cmt__City__c;
            this.state = cpr.Premises__r.vlocity_cmt__State__c;
            this.country = cpr.Premises__r.vlocity_cmt__Country__c;
            this.postalCode = cpr.Premises__r.vlocity_cmt__PostalCode__c;

            this.gstNumber = cpr.GST__r.Name;

            // this.contactId = cpr.Contact__c;
            // this.premiseId = cpr.Premises__c;
            // this.gstID = cpr.GST__c;
        }
    }

    // Artl_BcpDcpCtrl.handleNotification('0017200000V7oB8AAJ');
    //method for handling notification
    public static void handleNotification(String targetId) {
        String reportId = System.Label.ARTL_Bulk_Update_BCP_DCP_ReportId; //'00O72000004XF2nEAG';
        String reportPageRef = '{type: "standard__webPage", attributes: { url: "https://business-force-5632--artldevp2.sandbox.lightning.force.com/lightning/r/Report/'+ reportId + '/view?queryScope=userFolders&fv0=' + targetId +'"}}';

        List<CustomNotificationType > customNotificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'ARTL_Bulk_BCP_DCP_Update'];
        
        Messaging.CustomNotification currNotification = new Messaging.CustomNotification();

        currNotification.setTitle('Bulk BCP DCP update completed');
        currNotification.setBody('Click here to see the status.');
        currNotification.setNotificationTypeId(customNotificationType[0].Id);
        //currNotification.setTargetId(targetId);
        currNotification.setTargetPageRef(reportPageRef);
        try {
            currNotification.send(new Set<String> { Userinfo.getUserId() });
        }
        catch (Exception ex) {
            System.debug('Notification Failed: ' + ex.getMessage());
        }
    }
}