force-app/main/default/objects/ARTL_Bulk_Process_Records__e/ARTL_Bulk_Process_Records__e.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Process Records</label>
    <pluralLabel>ARTL Bulk Process Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Request_JSON_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON_Payload__c</fullName>
    <label>Request JSON Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_BulkProcessRecordsHandlerTest.cls
/******************************************************************************************************
* @Author       : bijaya.dutta@salesforce.com
* @Company      : Salesforce
* @Date         : 30-Jan-2024
* @Description  : Test class for ARTL_BulkProcessRecordsTriggerHandler 
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect      Developer             Date             Comment
*  SFDC-3180             Bijaya Dutta        30-Jan-2024      Initial Dev
*******************************************************************************************************/
@isTest
public class ARTL_BulkProcessRecordsHandlerTest {

    @IsTest
    static void myUnitTest1() {
        // Create test data for platform event
        ARTL_Bulk_Process_Records__e e = new ARTL_Bulk_Process_Records__e();
        e.Request_JSON_Payload__c = '{"TaskId":"00T720000059JBtEAM","Status":"Completed"}';
        e.Record_ID__c = '0Q0720000006atdCAA';    
        e.Transaction_Type__c = 'Task Update';
        // Publish test event
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(e);  
        // Process the published event in the trigger handler
        List<ARTL_Bulk_Process_Records__e> eventList = new List<ARTL_Bulk_Process_Records__e>{e};
        List<ARTL_Bulk_Process_Records__e> emptyEventList = new List<ARTL_Bulk_Process_Records__e>{null};
        ARTL_BulkProcessRecordsTriggerHandler.processAfterInsert(eventList);
        ARTL_BulkProcessRecordsTriggerHandler.processAfterInsert(emptyEventList);
        Test.stopTest();
    }
}