force-app/main/default/objects/ARTL_Bulk_Process_Records__e/ARTL_Bulk_Process_Records__e.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Process Records</label>
    <pluralLabel>ARTL Bulk Process Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Request_JSON_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON_Payload__c</fullName>
    <label>Request JSON Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/ARTL_BulkCartUpdate__c.object-meta.xml
<CustomObject>
    <label>Bulk Cart Update</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_BulkCartUpdate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Cart Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Business_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Account_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Request_JSON_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON_Payload__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Request JSON Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>Task Record Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Transaction Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Transaction Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_TasksBulkUploadCtrl.cls
/******************************************************************************************************
* @Author       : bijaya.dutta@salesforce.com
* @Company      : Salesforce
* @Date         : 30-Jan-2024
* @Test Class   : ARTL_TasksBulkUploadCtrlTest
* @Description  : Controller for ArtlFileUploadModal LWC
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect      Developer             Date             Comment
*  SFDC-3180             Bijaya Dutta        30-Jan-2024      Initial Dev
*******************************************************************************************************/
public with sharing class ARTL_TasksBulkUploadCtrl {
    

    @AuraEnabled
    public static string createTaskRecordsOnBulkCartUpdate(List<String> taskIds ,List<Object> objList){
        List<sObject> lstStageToInsert = new List<sObject>();
        List<ARTL_Bulk_Process_Records__e> lstBulkProcessRecords = new List<ARTL_Bulk_Process_Records__e>();
        Map<String,String> taskStatusMap = new Map<String,String>();
       
        try {
            if(!(objList.isEmpty())){       
                for(Object obj : objList){
                    Map<String, Object> objRow = new Map<String, Object>();
                    objRow = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(obj));
                    String taskId=(String)objRow.get('TaskId');
                    String taskStatus=(String)objRow.get('Status');
                    taskStatusMap.put(taskId,taskStatus);
                }
            }
        if(!taskIds.isEmpty()) {
            for(Task taskRecord : [SELECT Id, AccountId FROM Task WHERE Id IN :taskIds]) {
                String taskId15Char = String.valueOf(taskRecord.Id).substring(0, 15);
                if (taskStatusMap.containsKey(taskId15Char)) {
                    // Retrieve the status from the map
                    String status = taskStatusMap.get(taskId15Char);

                ARTL_BulkCartUpdate__c objRec = new ARTL_BulkCartUpdate__c();
                objRec.Transaction_Id__c = taskRecord.Id;
                objRec.Business_Account_Id__c = taskRecord.AccountId;
                String jsonPayload = '{"TaskId":"' + taskRecord.Id + '","Status":"' + status + '"}';
                objRec.put('Request_JSON_Payload__c', jsonPayload);
                objRec.Status__c = 'In progress';
                objRec.Transaction_Type__c = 'Task Update';
                lstStageToInsert.add(objRec);

                ARTL_Bulk_Process_Records__e bulkProcessRecord = new ARTL_Bulk_Process_Records__e(
                        Transaction_Type__c = 'Task Update',
                        Request_JSON_Payload__c = jsonPayload
                    );
                    lstBulkProcessRecords.add(bulkProcessRecord);
            }
        }
        }
        if (!lstStageToInsert.isEmpty()) {
            // Insert the ARTL_BulkCartUpdate__c records
            Database.insert(lstStageToInsert);
            
            //Update Bulk Process Records with Transaction Record IDs
            for (Integer i = 0; i < lstStageToInsert.size(); i++) {
                ARTL_Bulk_Process_Records__e bulkProcessRecord = lstBulkProcessRecords[i];
                bulkProcessRecord.Record_Id__c = lstStageToInsert[i].Id;
                
            }
            EventBus.publish(lstBulkProcessRecords) ;

            return 'success';
        }
        return 'No records to process';
        } catch (Exception e) {
            System.debug('error msg=' + e.getMessage());
            return 'error = ' + e.getMessage();
        }
    }
}