force-app/main/default/objects/ARTL_Bulk_Process_Records__e/ARTL_Bulk_Process_Records__e.object-meta.xml
<CustomObject>
    <label>ARTL Bulk Process Records</label>
    <pluralLabel>ARTL Bulk Process Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Request_JSON_Payload__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON_Payload__c</fullName>
    <label>Request JSON Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ARTL_Bulk_Process_Records__e/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARTL_BulkProcessRecordsTriggerHandler.cls
/******************************************************************************************************
* @Author       : bijaya.dutta@salesforce.com
* @Company      : Salesforce
* @Date         : 30-Jan-2024
* @Test Class   : ARTL_BulkProcessRecordsHandlerTest
* @Description  : platformEventTrigger Handler to process the bulk records stored in that event.
* ----------------------- Changes Implemented / Modification Log --------------------------------------
* UserStory / Defect      Developer             Date             Comment
*  SFDC-3180             Bijaya Dutta        30-Jan-2024      Initial Dev
*******************************************************************************************************/
public class ARTL_BulkProcessRecordsTriggerHandler {
    public static void processAfterInsert(List<ARTL_Bulk_Process_Records__e> platformEventRecords){
        try{
    	for(ARTL_Bulk_Process_Records__e platformEventRec : platformEventRecords){
            Map<String,Object> payload = (Map<String,Object>) JSON.deserializeUntyped(platformEventRec.Request_JSON_Payload__c);
            Map<String, Object> ipInput = new Map<String, Object>();
            Map<String, Object> ipOutput = new Map<String, Object>();
            Map<String, Object> ipOptions = new Map<String, Object>();
            
            ipOptions.put('isDebug',false);
            ipInput.put('payload', payload);
            ipInput.put('Record_ID__c', platformEventRec.Record_ID__c );
            ipInput.put('Transaction_Type__c', platformEventRec.Transaction_Type__c );
            string ipInputString = JSON.serialize(ipInput);
            ipOutput = (Map<String,Object>)vlocity_cmt.IntegrationProcedureService.runIntegrationService('ARTL_BulkTaskUpdate', ipInput, ipOptions);
        }
        }
        catch (Exception e) {
            System.debug('error msg### ' + e.getMessage());
        }
    }

}