force-app/main/default/objects/ARTL_Feasibility__c/ARTL_Feasibility__c.object-meta.xml
<CustomObject>
    <label>Feasibility</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Feasibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feasibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility__c/fields/ARTL_Feasibility_Status__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility_Status__c</fullName>
    <label>Feasibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FEASIBLE</fullName>
                <label>Feasible</label>
            </value>
            <value>
                <fullName>NOT_FEASIBLE</fullName>
                <label>Not Feasible</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>MANUAL_INTERVENTION_REQUIRED</fullName>
                <label>Manual Intervention Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Annual_Recurring_Total__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Total__c</fullName>
    <label>Annual Recurring Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Annual_Recurring_Total__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Total__c</fullName>
    <label>Annual Recurring Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_OpportunityTriggerHelper.cls
/**
* @Description: Class to implement the trigger helper for Opportunity Object
* @Author:  Salesforce (Sagar)
* @CreatedDate: 17th Oct 2023
*/
public with Sharing class ARTL_OpportunityTriggerHelper {
    
    private static final String NOT_FEASIBLE = 'NOT_FEASIBLE';
    private static final String INITIAL_STAGE = 'Initial';
    
    /**
     * Name: partialWonOpportunities
     * Description: used to create child opportunity and opportunity products for non feasible products(bundle)
     * Author: Sagar Sadhnani
     */
    public static void partialWonOpportunities(Map<Id, Opportunity> partialWinOppMap) {
        
        
        
        Map<String, OpportunityLineItem> uniqueOLIMap = new Map<String, OpportunityLineItem>();
        Map<String, Opportunity> oldNewOppMap = new Map<String, Opportunity>();

        for(QuoteLineItem qli : [SELECT Product2Id, vlocity_cmt__OneTimeTotal__c, Annual_Recurring_Total__c, Quantity, Quote.OpportunityId 
                                FROM quotelineitem 
                                WHERE ARTL_Feasibility__r.ARTL_Feasibility_Status__c = :NOT_FEASIBLE AND Quote.OpportunityId IN :partialWinOppMap.keySet() AND vlocity_cmt__ParentItemId__c = null]
        )
        {
            //Opportunity newOpp;
            OpportunityLineItem newOLI;
            //KB: Creating Child Opp
            if(!oldNewOppMap.containsKey(qli.Quote.OpportunityId)){
                oldNewOppMap.put(qli.Quote.OpportunityId, new Opportunity( name = partialWinOppMap.get(qli.Quote.OpportunityId).name, 
                                accountId = partialWinOppMap.get(qli.Quote.OpportunityId).accountid, stagename = INITIAL_STAGE, 
                                CloseDate = System.today().addYears(1), vlocity_cmt__PriceListId__c = partialWinOppMap.get(qli.Quote.OpportunityId).vlocity_cmt__PriceListId__c,
                                Parent_Opportunity__c = qli.Quote.OpportunityId, Pricebook2Id = partialWinOppMap.get(qli.Quote.OpportunityId).Pricebook2Id)
                );
            }
            Decimal aggregatedPrice = (qli.vlocity_cmt__OneTimeTotal__c != null ? qli.vlocity_cmt__OneTimeTotal__c : 0) + (qli.Annual_Recurring_Total__c != null ? qli.Annual_Recurring_Total__c : 0);
            
            if(!uniqueOLIMap.containsKey(qli.Quote.OpportunityId + '___' + qli.Product2Id)){
                
                newOLI = new OpportunityLineItem(Opportunity = oldNewOppMap.get(qli.Quote.OpportunityId), UnitPrice = aggregatedPrice,
                                                Product2Id = qli.Product2Id, Quantity = qli.Quantity                                
                );
                
            }else{//KB: Here we need to create only unique products with rolled up quantities and price
                
                newOLI = uniqueOLIMap.get(qli.Quote.OpportunityId + '___' + qli.Product2Id);
                newOLI.Quantity += qli.Quantity;
                newOLI.UnitPrice += aggregatedPrice;
            }
            uniqueOLIMap.put(qli.Quote.OpportunityId + '___' + qli.Product2Id, newOLI);
        }
        if(!uniqueOLIMap.isEmpty()){
            insert oldNewOppMap.values();

            for(String key : uniqueOLIMap.keySet()){
                uniqueOLIMap.get(key).OpportunityId = uniqueOLIMap.get(key).Opportunity.Id;
            }

            insert uniqueOLIMap.values();
        }
        
    }
    
    public static void defaultOpportunityStage(List<Opportunity> oppList){
        try{
            system.debug('beforeInsert opportunity trigger::defaultOpportunityStage');
            for(Opportunity oppRecord:oppList){
                system.debug('oppRecord=>'+JSON.serializePretty(oppRecord));
                System.debug(' StageName =>'+oppRecord.StageName);
                oppRecord.StageName='Qualified';
                system.debug('oppRecord=>'+JSON.serializePretty(oppRecord));
            }
            system.debug('oppList=>'+JSON.serializePretty(oppList));
        }catch(Exception e){
            System.debug('Exception in class::ARTL_OpportunityTriggerHelper and method::defaultOpportunityStage @line number'+e.getLineNumber()+' ['+e.getMessage()+']');
        }
    }
    
}