force-app/main/default/objects/ARTL_Feasibility__c/ARTL_Feasibility__c.object-meta.xml
<CustomObject>
    <label>Feasibility</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Feasibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feasibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility__c/fields/ARTL_Feasibility_Status__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility_Status__c</fullName>
    <label>Feasibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FEASIBLE</fullName>
                <label>Feasible</label>
            </value>
            <value>
                <fullName>NOT_FEASIBLE</fullName>
                <label>Not Feasible</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
                <label>Pending</label>
            </value>
            <value>
                <fullName>MANUAL_INTERVENTION_REQUIRED</fullName>
                <label>Manual Intervention Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility__c/fields/ARTL_QLI__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Feasibilities</relationshipLabel>
    <relationshipName>Feasibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/ARTL_Feasibility_Attribute__c.object-meta.xml
<CustomObject>
    <label>Feasibility Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feasibility Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Feasibility Attributes</relationshipLabel>
    <relationshipName>Feasibility_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/fields/ARTL_Feasibility_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility_Line_Item__c</fullName>
    <label>Feasibility Line Item</label>
    <referenceTo>ARTL_Feasibility_Line_Item__c</referenceTo>
    <relationshipLabel>Feasibility Attributes</relationshipLabel>
    <relationshipName>Feasibility_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/fields/ARTL_QLI__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Feasibility Attributes</relationshipLabel>
    <relationshipName>Feasibility_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Line_Item__c/ARTL_Feasibility_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Feasibility Line Item</label>
    <nameField>
        <label>Feasibility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feasibility Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility_Line_Item__c/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <label>Feasibility</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Feasibility Line Items</relationshipLabel>
    <relationshipName>Feasibility_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Line_Item__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent ID</label>
    <referenceTo>ARTL_Feasibility_Line_Item__c</referenceTo>
    <relationshipLabel>Feasibility Line Items</relationshipLabel>
    <relationshipName>Feasibility_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/ARTL_Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/ARTL_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>ARTL_PO_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchase Order Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_Purchase_Order__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Term__c.field-meta.xml
<CustomField>
    <fullName>PO_Term__c</fullName>
    <label>PO Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PO_Value__c.field-meta.xml
<CustomField>
    <fullName>PO_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PO Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>ARTL_Purchase_Order__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AssetId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AssetId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For quotes of changes to existing Assets, this identifies the Asset that is being changed by this line item.</description>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quoted Changes</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__BillingAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__BillingAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account responsible for paying for the line item.</description>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>BillingAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__ServiceAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
    <label>Service Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>ServiceAccountQuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARTL_FeasibilityUtilityTest.cls
@isTest
private class ARTL_FeasibilityUtilityTest {

    @isTest
   private static void testTransformRequestAndUpdateQLI() {
          Profile p = [SELECT id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];  
        User adminUser = new User(firstname= 'Samuel',
                                  lastname='Oak',
                                  Alias='Samuel',
                                  email = 'testemail665411@email.com',
                                  username= 'testemail665411@email.com', 
                                  profileId= p.id, 
                                  emailencodingkey='UTF-8',
                                  languagelocalekey='en_US',
                                  localesidkey='en_US',
                                  timezonesidkey='America/Los_Angeles');
        System.runAs(adminUser){
           // create test data for order, Account, Quote, Opportunity
        Account acc = new Account();
        acc.name='Parent Test';
        acc.BillingStreet = '3022  Strother Street';
        acc.BillingCity = 'Into';
        acc.BillingState = 'Alabama';
        acc.BillingPostalCode = '35222';
        acc.BillingCountry = 'US';
        
        insert acc ;
        
        Product2[] products = new Product2[2];

        products[0]=new Product2(name='Test Product1', ProductCode='VEPC_ENTERPRISE_ICONNECTIVITY_ROUTERS');
        products[1]=new Product2(name='Test Product2', ProductCode='VEPC_PRIMARY_LINK');
        
        insert products;

        PricebookEntry[] pbes = new PricebookEntry[products.size()];
        Id pbId = Test.getStandardPricebookId();

        for (Integer i=0; i<products.size(); i++)
        {
            pbes[i] = new PricebookEntry(product2Id = products[i].id, IsActive = true, unitPrice = 10, pricebook2id = pbId, useStandardPrice = false);
        }

        insert pbes;

        
        vlocity_cmt__PriceList__c pl1 = new vlocity_cmt__PriceList__c(vlocity_cmt__Pricebook2Id__c = pbId, vlocity_cmt__IsActive__c = true, vlocity_cmt__Code__c = 'TestPricebook5');
        insert pl1;
        
        Opportunity  opp = new Opportunity ();
        opp.name= 'EPC Deal AA';
        opp.accountId = acc.id;
        opp.vlocity_cmt__PriceListId__c = pl1.Id;
        opp.CloseDate = System.today();
        opp.StageName = 'Initial';
        opp.Pricebook2Id = pbId;
        insert opp;


        
        Quote qtest = new Quote();
        qtest.name = 'Quote - EPC Deal AA';
        qtest.Status = 'Draft';
        qtest.OpportunityId = opp.Id;
        qtest.Pricebook2Id = pbId;
        qtest.vlocity_cmt__PriceListId__c = pl1.Id;
        qtest.vlocity_cmt__PoDate__c = Date.today();
        qtest.vlocity_cmt__PoNumber__c = '12345';
        qtest.PO_Term__c = '12';
        qtest.PO_Value__c = 1222;
       	qtest.RecordTypeId =  [SELECT Id FROM RecordType WHERE DeveloperName= 'EnterpriseQuote' AND SobjectType= 'Quote' LIMIT 1].Id;
        insert qtest;
            
            
            
        
        QuoteLineItem  qouteLine = new QuoteLineItem ();
        qouteLine.UnitPrice = 1;
        qouteLine.Quantity = 1;
        qouteLine.Product2Id = products[0].Id;
        qouteLine.vlocity_cmt__Product2Id__c = products[0].Id;
        qouteLine.QuoteId =qtest.Id;
        qouteLine.PricebookEntryId=pbes[0].Id;
        qouteLine.vlocity_cmt__ServiceAccountId__c =acc.id;
        insert qouteLine;
            
            
           ARTL_Feasibility__c fea = new ARTL_Feasibility__c(ARTL_Feasibility_Status__c='Feasible');
        insert fea;
            ARTL_Feasibility_Line_Item__c FeasibilityParentLineItem = new ARTL_Feasibility_Line_Item__c(
            ARTL_Feasibility__c = fea.Id, Name= 'Test');
            insert FeasibilityParentLineItem;
            
            List<ARTL_Feasibility_Line_Item__c> FeasibilityParentLineItemList = new list<ARTL_Feasibility_Line_Item__c>();
            FeasibilityParentLineItemList.add(FeasibilityParentLineItem);
            
             ARTL_Feasibility_Line_Item__c FeasibilityLineItem2 = new ARTL_Feasibility_Line_Item__c(
            ARTL_Feasibility__c = fea.Id, Name= 'Test',ParentId__c=FeasibilityParentLineItem.id);
            insert FeasibilityLineItem2;
            
              ARTL_Feasibility_Attribute__c attributeRecord5 = new ARTL_Feasibility_Attribute__c(
            ARTL_Feasibility__c = fea.Id,
            Name = 'city',
            Value__c = 'value2',
            ARTL_QLI__c = qouteLine.Id,
            ARTL_Feasibility_Line_Item__c = FeasibilityParentLineItem.id
        );
        insert attributeRecord5;
            
            list<ARTL_Feasibility_Attribute__c> fAttrInsertList = new list<ARTL_Feasibility_Attribute__c>();
            fAttrInsertList.add(attributeRecord5);
            
            
              ARTL_Purchase_Order__c PurchaseOrder = new ARTL_Purchase_Order__c();
            PurchaseOrder.ARTL_PO_Number__c = '111111';
            PurchaseOrder.Quote_Line_Item__c = qouteLine.id;
            insert PurchaseOrder;
            
             Asset ast = new Asset();
            ast.Name = 'MyNewAssetforTestClass';
            ast.AccountId = acc.Id;
            ast.vlocity_cmt__AssetReferenceId__c = '123';
            ast.vlocity_cmt__BillingAccountId__c  = acc.Id;
             ast.vlocity_cmt__ServiceAccountId__c   = acc.Id;
            ast.ARTL_Purchase_Order__c = PurchaseOrder.id;
            insert ast;  
        QuoteLineItem  qouteLine2 = new QuoteLineItem ();
        qouteLine2.UnitPrice = 1;
        qouteLine2.Quantity = 1;
        qouteLine2.vlocity_cmt__AssetId__c = ast.id;
        qouteLine2.Product2Id = products[1].Id;
        qouteLine2.vlocity_cmt__Product2Id__c = products[1].Id;
        qouteLine2.QuoteId =qtest.Id;
        qouteLine2.PricebookEntryId=pbes[0].Id;
        insert qouteLine2;
            
          
        
        List<Order> orderList = new List<Order>();
        Order ord = new Order(AccountId = acc.id,vlocity_cmt__QuoteId__c = qtest.Id ,
                effectiveDate = Date.today(), pricebook2id = pbId, status = 'Draft',
                vlocity_cmt__PriceListId__c = pl1.Id);
        orderList.add(ord);
        insert orderList;
        
              
        
         Map<String, Object> inputMap = new Map<String, Object>{
            'request' => new List<Object>{
                new Map<String, Object>{
                    'requestId' => qtest.Id
                    // Add other required fields as needed
                }
            }
        };

        Map<String, Object> outputMap = new Map<String, Object>();

        Test.startTest(); 
        ARTL_FeasibilityUtility utility = new ARTL_FeasibilityUtility();
            
          String longString = '{' + '"RootAttribute": "' + 'This is a long string with more than 255 characters. '.repeat(10) + '"}';

        // Parse the JSON string into a nested map
        Map<String, Object> longStringMap = (Map<String, Object>)JSON.deserializeUntyped(longString);

        // Create test data for resultMap
        Map<String, Object> resultMap = new Map<String, Object>{
            'RootAttribute' => longStringMap,
            'ObjectAttribute' => '{"NestedAttribute1": "NestedValue1", "NestedAttribute2": "NestedValue2"}',
            'Attribute2' => 'Value2'
        };

        // Create lists to store inserted records
     // Call the method
     //   ARTL_FeasibilityUtility.parseInfiniteData(resultMap, 'RootAttribute', fea, FeasibilityParentLineItemList, fAttrInsertList, FeasibilityParentLineItem);
        
          //  Map<String,Object> resultMap, String level1Attr, ARTL_Feasibility__c feasibilityObj, List< ARTL_Feasibility_Line_Item__c> fLIInsertList, List< ARTL_Feasibility_Attribute__c> fAttrInsertList, ARTL_Feasibility_Line_Item__c parentFLI
            
            
          
       ARTL_FeasibilityUtility.getReportId(' ');
        utility.invokeMethod('requestTransform',inputMap, outputMap, new Map<String, Object>());
         utility.invokeMethod('addressVerificationForQuote',inputMap, outputMap, new Map<String, Object>());
        Test.stopTest();
        
        
        }}
        
    
}