force-app/main/default/objects/ARTL_Feasibility__c/ARTL_Feasibility__c.object-meta.xml
<CustomObject>
    <label>Feasibility</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>Feasibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feasibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility__c/fields/ARTL_QLI__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Feasibilities</relationshipLabel>
    <relationshipName>Feasibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/ARTL_Feasibility_Attribute__c.object-meta.xml
<CustomObject>
    <label>Feasibility Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feasibility Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Feasibility Attributes</relationshipLabel>
    <relationshipName>Feasibility_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_Feasibility_Attribute__c/fields/ARTL_QLI__c.field-meta.xml
<CustomField>
    <fullName>ARTL_QLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Feasibility Attributes</relationshipLabel>
    <relationshipName>Feasibility_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ARTL_MSU_Matrix__c/ARTL_MSU_Matrix__c.object-meta.xml
<CustomObject>
    <label>MSU Matrix</label>
    <nameField>
        <displayFormat>MSU-{0000}</displayFormat>
        <label>MSU Matrix No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSU Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_MSU_Matrix__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ARTL_MSU_Matrix__c/fields/MSUCode__c.field-meta.xml
<CustomField>
    <fullName>MSUCode__c</fullName>
    <label>MSU Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ARTL_MSU_Matrix__c/fields/NetworkCity__c.field-meta.xml
<CustomField>
    <fullName>NetworkCity__c</fullName>
    <label>Network City</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_MSU_Matrix__c/fields/RSUCode__c.field-meta.xml
<CustomField>
    <fullName>RSUCode__c</fullName>
    <label>RSU Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ARTL_MSU_Matrix__c/fields/RSUIdentifier__c.field-meta.xml
<CustomField>
    <fullName>RSUIdentifier__c</fullName>
    <label>RSU Identifier</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__AttributeSelectedValues__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AttributeSelectedValues__c</fullName>
    <label>Attribute Selected Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ARTL_Feasibility__c.field-meta.xml
<CustomField>
    <fullName>ARTL_Feasibility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FeasibilityId</label>
    <referenceTo>ARTL_Feasibility__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__AttributeSelectedValues__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__AttributeSelectedValues__c</fullName>
    <label>Attribute Selected Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/vlocity_cmt__Product2Id__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DEPRECATED, Use the standard Product2Id field.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STD_Code__mdt/STD_Code__mdt.object-meta.xml
<CustomObject>
    <label>STD Code</label>
    <pluralLabel>STD Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/STD_Code__mdt/fields/STD_Code__c.field-meta.xml
<CustomField>
    <fullName>STD_Code__c</fullName>
    <label>STD Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Artel_EnrichAtrributeFromFeasibility.cls
/***********************************************************************************************************************************
 * @Author       : Aliya Ameer
 * @Date         : 15/11/2023
 * @Test Class   : 
 * @Description  : Enrich FRL Attributes of DSL and Voice from feasibility records 
 ***********************************************************************************************************************************/
global class Artel_EnrichAtrributeFromFeasibility implements vlocity_cmt.XOMOrchestrationInterfaces.IAutoTask {
    global void executeBatch(List < vlocity_cmt__OrchestrationItem__c > items) {
        Set < String > parentLineNumbers = new Set < String > ();
        for (vlocity_cmt__OrchestrationItem__c item: items) {
            //System.debug(LoggingLevel.INFO, 'Orchestration task Id = ' + item.Id);
            enrichAttrFRL(items, parentLineNumbers);
        }
    }

    global void enrichAttrFRL(List < vlocity_cmt__OrchestrationItem__c > orchItemsList, Set < String > parentLineNumbers) {
        //System.debug('orchItemsList = ' + orchItemsList);
        List < vlocity_cmt__OrchestrationItem__c > orchItemsListQuery = new List < vlocity_cmt__OrchestrationItem__c >();
        List < Id > orderList = new List < Id > ();
        Set < Id > orchestrationPlanIds = new Set < Id > ();
        String FrId, rsuName, maxspeedrsu, maxspeed, maxspeedtechnology, city, technology;
        Map < Id, Id > orchestrationPlanIdToOrderId = new Map < Id, Id > ();
        Set < Id > quoteLineItemIdSet = new Set < Id > ();
        Set < Id > feasibilityIdSet = new Set < Id > ();
        Map < String, Decimal > cityToSTDCodeMap = new Map < String, Decimal > ();
        Map < String, Decimal > cityToMsuCodeMap = new Map < String, Decimal > ();
        Object attributeValue = null;
        
        orchItemsListQuery = [SELECT Id, 
                        vlocity_cmt__OrchestrationPlanId__r.vlocity_cmt__OrderId__c, 
                        vlocity_cmt__FulfilmentRequestLineId__r.vlocity_cmt__FulfilmentRequestID__c 
                 FROM vlocity_cmt__OrchestrationItem__c 
                 WHERE Id IN :orchItemsList];

        for (vlocity_cmt__OrchestrationItem__c orchItem: orchItemsListQuery) {
            orderList.add(orchItem.vlocity_cmt__OrchestrationPlanId__r.vlocity_cmt__OrderId__c);
            FrId = orchItem.vlocity_cmt__FulfilmentRequestLineId__r.vlocity_cmt__FulfilmentRequestID__c;
        }
        System.debug('orderList###' + orderList);
        System.debug('FrId###' + FrId);

        List < OrderItem > orderItemList = [
            SELECT Id, QuoteLineItemId, vlocity_cmt__ParentItemId__c, 
            vlocity_cmt__AttributeSelectedValues__c, QuoteLineItem.ARTL_Feasibility__c 
            FROM OrderItem WHERE OrderId IN: orderList AND vlocity_cmt__ParentItemId__c = ''
        ];

        for (OrderItem ordItem: orderItemList) {
            quoteLineItemIdSet.add(ordItem.QuoteLineItemId);
            feasibilityIdSet.add(ordItem.QuoteLineItem.ARTL_Feasibility__c);
            Map<String, Object> attributeValuesMap = (Map<String, Object>) JSON.deserializeUntyped(ordItem.vlocity_cmt__AttributeSelectedValues__c);
            attributeValue = attributeValuesMap.get('ATT_PLAN_SPEED');
        }
        System.debug('AA quoteLineItemIdSet=>'+quoteLineItemIdSet);
        System.debug('AA feasibilityIdSet=>'+feasibilityIdSet);

        List < ARTL_Feasibility_Attribute__c > feasibilityAttributeList = [
            SELECT Id, Name, Value__c, ARTL_Feasibility__c, ARTL_QLI__c
            FROM ARTL_Feasibility_Attribute__c
            WHERE ARTL_Feasibility__c IN: feasibilityIdSet
            AND ARTL_QLI__c IN: quoteLineItemIdSet
        ];

        for (ARTL_Feasibility_Attribute__c attribute: feasibilityAttributeList) {
            if (attribute.Name == 'rsuName') {
                rsuName = attribute.Value__c;
            } else if (attribute.Name == 'maxspeed') {
                maxspeed = attribute.Value__c;
            } else if (attribute.Name == 'maxspeedrsu') {
                maxspeedrsu = attribute.Value__c;
            } else if (attribute.Name == 'maxspeedtechnology') {
                maxspeedtechnology = attribute.Value__c;
            } else if (attribute.Name == 'city') {
                city = attribute.Value__c;
            } else if (attribute.Name == 'technology') {
                technology = attribute.Value__c;
            }
        }

        List < ARTL_MSU_Matrix__c > msuMatrixList = [
            SELECT Id, Circle__c, MSUCode__c, Name, NetworkCity__c, RSUCode__c, RSUIdentifier__c
            FROM ARTL_MSU_Matrix__c
            WHERE RSUCode__c =: rsuName
            AND NetworkCity__c =: city
        ];

        for (ARTL_MSU_Matrix__c msuCode: msuMatrixList) {
            cityToMsuCodeMap.put(msuCode.NetworkCity__c, msuCode.MSUCode__c);
        }

        List < STD_Code__mdt > stdCodeMetadataList = [
            SELECT Id, City__c, STD_Code__c FROM STD_Code__mdt WHERE City__c =: city
        ];

        for (STD_Code__mdt stdCode: stdCodeMetadataList) {
            cityToSTDCodeMap.put(stdCode.City__c, stdCode.STD_Code__c);
        }

        List < vlocity_cmt__FulfilmentRequestLine__c > frlList = new List < vlocity_cmt__FulfilmentRequestLine__c > ();
        List < vlocity_cmt__FulfilmentRequestLine__c > RootFrlList = [
            Select id, vlocity_cmt__Product2Id__c,vlocity_cmt__Product2Id__r.ProductCode,
            vlocity_cmt__AttributeSelectedValues__c, vlocity_cmt__FulfilmentRequestID__c, vlocity_cmt__LineNumber__c
            From vlocity_cmt__FulfilmentRequestLine__c
            Where vlocity_cmt__FulfilmentRequestID__c =: FrId AND
            (vlocity_cmt__Product2Id__r.ProductCode = 'VEPC_DSL_CFS'
                OR vlocity_cmt__Product2Id__r.ProductCode = 'VEPC_Voice_CFS')
        ];    //For DSL & voice line nos
        System.debug('AA RootFrlList=>'+RootFrlList);
        
        List < vlocity_cmt__FulfilmentRequestLine__c > ChildFrlList = [
            select id, vlocity_cmt__Product2Id__c,vlocity_cmt__Product2Id__r.ProductCode,
            vlocity_cmt__AttributeSelectedValues__c, vlocity_cmt__FulfilmentRequestID__c, vlocity_cmt__LineNumber__c
            from vlocity_cmt__FulfilmentRequestLine__c
            where vlocity_cmt__FulfilmentRequestID__c =: FrId AND
            (vlocity_cmt__Product2Id__r.ProductCode != 'VEPC_DSL_CFS'
                OR vlocity_cmt__Product2Id__r.ProductCode != 'VEPC_Voice_CFS')
        ]; 
        System.debug('AA ChildFrlList=>'+ ChildFrlList);
        
        for (vlocity_cmt__FulfilmentRequestLine__c frl: RootFrlList) {
            //String linenumber = frl.vlocity_cmt__LineNumber__c;
            if (frl.vlocity_cmt__Product2Id__r.ProductCode == 'VEPC_DSL_CFS' || frl.vlocity_cmt__Product2Id__r.ProductCode == 'VEPC_Voice_CFS') {
                parentLineNumbers.add(frl.vlocity_cmt__LineNumber__c);
                System.debug('linenumber#' + parentLineNumbers);
            } 
        }

        for (vlocity_cmt__FulfilmentRequestLine__c frl: ChildFrlList) {
            for (String parentLineNumber: parentLineNumbers) {
                if (frl.vlocity_cmt__LineNumber__c.startsWith(parentLineNumber + '.')) {
                    System.debug('frl line no inside if#' + frl.vlocity_cmt__LineNumber__c);
                    System.debug('frl inside if#' + frl.vlocity_cmt__Product2Id__r.ProductCode);
                    Map < String, Object > FRLStringMap;
                    if (frl.vlocity_cmt__AttributeSelectedValues__c != NULL)
                        FRLStringMap = (Map < String, Object > ) JSON.deserializeUntyped(frl.vlocity_cmt__AttributeSelectedValues__c);
                    else
                        FRLStringMap = new Map < String, Object > ();
                    String FRLAttString = '';

                    for (String s: FRLStringMap.keySet()) {
                        if (s == 'ATT_ RSU') {
                            FRLStringMap.put(s, rsuName);
                        }
                        if (s == 'ATT_Max_Speed') {
                            FRLStringMap.put(s, maxspeed);
                        }
                        if (s == 'ATT_Max_Speed_RSU') {
                            FRLStringMap.put(s, maxspeedrsu);
                        }
                        if (s == 'ATT_Max_Speed_Technology') {
                            FRLStringMap.put(s, maxspeedtechnology);
                        }
                        if (s == 'ATT_TECHNOLOGY') {
                            FRLStringMap.put(s, technology);
                        }
                        if (s == 'ATT_STD_Code') {
                            FRLStringMap.put(s, cityToSTDCodeMap.get(city));
                        }
                        if (s == 'ATT_MSU') {
                            FRLStringMap.put(s, cityToMsuCodeMap.get(city));
                        }
                        if (s == 'ATT_Speed') {
                        FRLStringMap.put(s, attributeValue);
                        }
                    }
                    FRLAttString = JSON.serialize(FRLStringMap);
                    frl.vlocity_cmt__AttributeSelectedValues__c = FRLAttString;
                    frlList.add(frl);
                } 
            }
        }

        if (frlList.size() > 0) {
            update frlList;
        }
    }
}