force-app/main/default/objects/ARTL_BulkCartUpdate__c/ARTL_BulkCartUpdate__c.object-meta.xml
<CustomObject>
    <label>Bulk Cart Update</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ARTL_BulkCartUpdate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Cart Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ARTL_BulkCartUpdate__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ARTL_BulkCartUpdateField.cls
global with sharing class ARTL_BulkCartUpdateField implements vlocity_cmt.VlocityOpenInterface2{
	global Object invokeMethod(String methodName, Map<String,Object> inputs, Map<String,Object> output, Map<String,Object> options) {
        try {
            Boolean success = false;
        if(methodName=='SendTaskUpdate'){
             SendTaskUpdateResponse(inputs,output,options);
        }
        
        return success;
        }
        catch(Exception ex){
            System.debug('Exception invokeMethod ------------- '+ex.getMessage()+'L No- '+ex.getLineNumber());
            return ex;
        }   
        
    }
     public static void SendTaskUpdateResponse(Map<String,Object> inputs, Map<String,Object> output, Map<String,Object> options){
        Id recordId = (Id)inputs.get('Record_ID__c');
    // Access the error message directly from the specified path
    String error = (String) ((Map<String, Object>) ((Map<String, Object>) inputs.get('DataRaptorPostAction1')).get('errorsAsJson')).get('DRError');
    
        ARTL_BulkCartUpdate__c objRec = new ARTL_BulkCartUpdate__c();
         objRec.Id = recordId;
        objRec.Errors__c = error;
        update objRec;
    }
}